// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by json_schema2dart

class AdditionalProperties {
  final String? known;
  final Map<String, double>? additionalProperties;

  const AdditionalProperties({
    this.known,
    this.additionalProperties,
  });

  factory AdditionalProperties.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final known = json['known'] as String?;
    remaining.remove('known');
    var unmatched = Map<String, dynamic>.from(remaining);
    Map<String, double>? additionalPropertiesValue;
    if (unmatched.isNotEmpty) {
      final additionalPropertiesMap = <String, double>{};
      for (final entry in unmatched.entries) {
        final value = entry.value;
        additionalPropertiesMap[entry.key] = value as double;
      }
      additionalPropertiesValue = additionalPropertiesMap.isEmpty ? null : additionalPropertiesMap;
      unmatched = <String, dynamic>{};
    } else {
      additionalPropertiesValue = null;
    }
    return AdditionalProperties(
      known: known,
      additionalProperties: additionalPropertiesValue,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (known != null) map['known'] = known;
    if (additionalProperties != null) {
      additionalProperties!.forEach((key, value) {
        map[key] = value;
      });
    }
    return map;
  }
}
