// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by json_schema2dart

class AllOfComposition {
  final int age;
  final String name;

  const AllOfComposition({
    required this.age,
    required this.name,
  });

  factory AllOfComposition.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final age = json['age'] as int;
    remaining.remove('age');
    final name = json['name'] as String;
    remaining.remove('name');
    return AllOfComposition(
      age: age,
      name: name,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['age'] = age;
    map['name'] = name;
    return map;
  }
}
