// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by json_schema2dart

class ArrayOfObjects {
  final List<User>? users;

  const ArrayOfObjects({this.users});

  factory ArrayOfObjects.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final users = json['users'] == null
        ? null
        : (json['users'] as List)
              .map((e) => User.fromJson((e as Map).cast<String, dynamic>()))
              .toList();
    remaining.remove('users');
    return ArrayOfObjects(users: users);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (users != null) map['users'] = users!.map((e) => e.toJson()).toList();
    return map;
  }
}

class User {
  final int id;
  final String name;

  const User({required this.id, required this.name});

  factory User.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final id = json['id'] as int;
    remaining.remove('id');
    final name = json['name'] as String;
    remaining.remove('name');
    return User(id: id, name: name);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['id'] = id;
    map['name'] = name;
    return map;
  }
}
