// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by json_schema2dart

class DefinitionsRefs {
  final Address? home;
  final Address? work;

  const DefinitionsRefs({
    this.home,
    this.work,
  });

  factory DefinitionsRefs.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final home = json['home'] == null ? null : Address.fromJson((json['home'] as Map).cast<String, dynamic>());
    remaining.remove('home');
    final work = json['work'] == null ? null : Address.fromJson((json['work'] as Map).cast<String, dynamic>());
    remaining.remove('work');
    return DefinitionsRefs(
      home: home,
      work: work,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (home != null) map['home'] = home!.toJson();
    if (work != null) map['work'] = work!.toJson();
    return map;
  }
}

class Address {
  final String city;
  final String street;

  const Address({
    required this.city,
    required this.street,
  });

  factory Address.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final city = json['city'] as String;
    remaining.remove('city');
    final street = json['street'] as String;
    remaining.remove('street');
    return Address(
      city: city,
      street: street,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['city'] = city;
    map['street'] = street;
    return map;
  }
}
