// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by json_schema2dart

class NestedObjects {
  final User? user;

  const NestedObjects({this.user});

  factory NestedObjects.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final user = json['user'] == null
        ? null
        : User.fromJson((json['user'] as Map).cast<String, dynamic>());
    remaining.remove('user');
    return NestedObjects(user: user);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (user != null) map['user'] = user!.toJson();
    return map;
  }
}

class UserAddress {
  final String city;
  final String street;

  const UserAddress({required this.city, required this.street});

  factory UserAddress.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final city = json['city'] as String;
    remaining.remove('city');
    final street = json['street'] as String;
    remaining.remove('street');
    return UserAddress(city: city, street: street);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['city'] = city;
    map['street'] = street;
    return map;
  }
}

class User {
  final UserAddress address;
  final String name;

  const User({required this.address, required this.name});

  factory User.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final address = UserAddress.fromJson(
      (json['address'] as Map).cast<String, dynamic>(),
    );
    remaining.remove('address');
    final name = json['name'] as String;
    remaining.remove('name');
    return User(address: address, name: name);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['address'] = address.toJson();
    map['name'] = name;
    return map;
  }
}
