// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by json_schema2dart

class UnionTypes {
  final dynamic value;

  const UnionTypes({
    this.value,
  });

  factory UnionTypes.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final value = json['value'];
    remaining.remove('value');
    return UnionTypes(
      value: value,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (value != null) map['value'] = value;
    return map;
  }
}
