// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/default_values/schema.json
// Generated by json_schema2dart

import 'config.dart';
import 'validation_error.dart';

/// Demonstrates default value handling
class DefaultValuesExample {
  /// Default: {}.
  final Config? config;

  /// Default: true.
  final bool? enabled;

  /// Server host
  ///
  /// Default: 'localhost'.
  final String? host;

  /// Server port
  ///
  /// Default: 8080.
  final int? port;

  /// Default: [default].
  final List<String>? tags;

  const DefaultValuesExample({
    this.config = const {},
    this.enabled = true,
    this.host = 'localhost',
    this.port = 8080,
    this.tags = const ['default'],
  });

  factory DefaultValuesExample.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final config =
        (json['config'] == null
            ? null
            : Config.fromJson(
                (json['config'] as Map).cast<String, dynamic>(),
              )) ??
        const {};
    remaining.remove('config');
    final enabled = (json['enabled'] as bool?) ?? true;
    remaining.remove('enabled');
    final host = (json['host'] as String?) ?? 'localhost';
    remaining.remove('host');
    final port = (json['port'] as int?) ?? 8080;
    remaining.remove('port');
    final tags =
        (json['tags'] == null
            ? null
            : (json['tags'] as List).map((e) => e as String).toList()) ??
        const ['default'];
    remaining.remove('tags');
    return DefaultValuesExample(
      config: config,
      enabled: enabled,
      host: host,
      port: port,
      tags: tags,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (config != null) map['config'] = config!.toJson();
    if (enabled != null) map['enabled'] = enabled;
    if (host != null) map['host'] = host;
    if (port != null) map['port'] = port;
    if (tags != null) map['tags'] = tags;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
