// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/default_values/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class DefaultValuesExampleConfig {
  /// Default: 30.
  final int? timeout;

  const DefaultValuesExampleConfig({
    this.timeout = 30,
  });

  factory DefaultValuesExampleConfig.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final timeout = (json['timeout'] as int?) ?? 30;
    remaining.remove('timeout');
    return DefaultValuesExampleConfig(
      timeout: timeout,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (timeout != null) map['timeout'] = timeout;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
