// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/oneof_example/schema.json
// Generated by json_schema2dart

export 'schema_generated/one_of_example.dart';
export 'schema_generated/result.dart';
export 'schema_generated/validation_error.dart';
