// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/pattern_properties/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// Demonstrates patternProperties
class PatternPropertiesExample {
  final String? name;
  final Map<String, dynamic>? patternProperties;

  const PatternPropertiesExample({
    this.name,
    this.patternProperties,
  });

  factory PatternPropertiesExample.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final name = json['name'] as String?;
    remaining.remove('name');
    var unmatched = Map<String, dynamic>.from(remaining);
    Map<String, dynamic>? patternPropertiesValue;
    {
      final patternPropertiesMap = <String, dynamic>{};
      final unmatchedAfterPattern = <String, dynamic>{};
      for (final entry in unmatched.entries) {
        final key = entry.key;
        final value = entry.value;
        var matched = false;
        if (!matched && RegExp('^S_').hasMatch(key)) {
          patternPropertiesMap[key] = value as String;
          matched = true;
        }
        if (!matched && RegExp('^I_').hasMatch(key)) {
          patternPropertiesMap[key] = value as int;
          matched = true;
        }
        if (!matched) {
          unmatchedAfterPattern[key] = value;
        }
      }
      patternPropertiesValue = patternPropertiesMap.isEmpty ? null : patternPropertiesMap;
      unmatched = unmatchedAfterPattern;
    }
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return PatternPropertiesExample(
      name: name,
      patternProperties: patternPropertiesValue,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (name != null) map['name'] = name;
    if (patternProperties != null) {
      for (final entry in patternProperties!.entries) {
        final key = entry.key;
        final value = entry.value;
        var matched = false;
        if (!matched && RegExp('^S_').hasMatch(key)) {
          map[key] = value;
          matched = true;
        }
        if (!matched && RegExp('^I_').hasMatch(key)) {
          map[key] = value;
          matched = true;
        }
        if (!matched) {
          map[key] = value;
        }
      }
    }
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
