// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/anyof_example/schema.json
// Generated by json_schema2dart

import 'complex_union.dart';
import 'string_or_number.dart';
import 'validation_error.dart';

/// Demonstrates anyOf unions
class AnyOfExample {
  final ComplexUnion? complexUnion;
  final StringOrNumber? stringOrNumber;

  const AnyOfExample({this.complexUnion, this.stringOrNumber});

  factory AnyOfExample.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final complexUnion = json['complexUnion'] == null
        ? null
        : ComplexUnion.fromJson(
            (json['complexUnion'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('complexUnion');
    final stringOrNumber = json['stringOrNumber'] == null
        ? null
        : StringOrNumber.fromJson(
            (json['stringOrNumber'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('stringOrNumber');
    return AnyOfExample(
      complexUnion: complexUnion,
      stringOrNumber: stringOrNumber,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (complexUnion != null) map['complexUnion'] = complexUnion!.toJson();
    if (stringOrNumber != null)
      map['stringOrNumber'] = stringOrNumber!.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'complexUnion');
    final _value0 = complexUnion;
    if (_value0 != null) {
      context?.markProperty(pointer, 'complexUnion');
      final _jsonp0 = _value0.toJson();
      final _constraintp0c0_0 = context == null ? null : ValidationContext();
      var _constraintp0m0_0 = false;
      try {
        final context = _constraintp0c0_0;
        final _constraintp0v0_0 = User.fromJson(
          (_jsonp0 as Map).cast<String, dynamic>(),
        );
        _constraintp0v0_0.validate(pointer: _ptr0, context: context);
        _constraintp0m0_0 = true;
      } on ValidationError {
      } catch (_) {}
      final _constraintp0c0_1 = context == null ? null : ValidationContext();
      var _constraintp0m0_1 = false;
      try {
        final context = _constraintp0c0_1;
        final _constraintp0v0_1 = Admin.fromJson(
          (_jsonp0 as Map).cast<String, dynamic>(),
        );
        _constraintp0v0_1.validate(pointer: _ptr0, context: context);
        _constraintp0m0_1 = true;
      } on ValidationError {
      } catch (_) {}
      final _constraintp0matches0 = <bool>[
        _constraintp0m0_0,
        _constraintp0m0_1,
      ];
      if (!_constraintp0matches0.any((value) => value)) {
        throwValidationError(
          _ptr0,
          'anyOf',
          'Expected at least one subschema in #/properties/complexUnion/anyOf to validate.',
        );
      }
      if (context != null && _constraintp0m0_0 && _constraintp0c0_0 != null) {
        context.mergeFrom(_constraintp0c0_0!);
      }
      if (context != null && _constraintp0m0_1 && _constraintp0c0_1 != null) {
        context.mergeFrom(_constraintp0c0_1!);
      }
    }
    final _ptr1 = appendJsonPointer(pointer, 'stringOrNumber');
    final _value1 = stringOrNumber;
    if (_value1 != null) {
      context?.markProperty(pointer, 'stringOrNumber');
      final _jsonp1 = _value1.toJson();
      final _constraintp1c0_0 = context == null ? null : ValidationContext();
      var _constraintp1m0_0 = false;
      try {
        final context = _constraintp1c0_0;
        final _constraintp1v0_0 = _jsonp1 as String;
        _constraintp1m0_0 = true;
      } on ValidationError {
      } catch (_) {}
      final _constraintp1c0_1 = context == null ? null : ValidationContext();
      var _constraintp1m0_1 = false;
      try {
        final context = _constraintp1c0_1;
        final _constraintp1v0_1 = _jsonp1 as double;
        _constraintp1m0_1 = true;
      } on ValidationError {
      } catch (_) {}
      final _constraintp1matches0 = <bool>[
        _constraintp1m0_0,
        _constraintp1m0_1,
      ];
      if (!_constraintp1matches0.any((value) => value)) {
        throwValidationError(
          _ptr1,
          'anyOf',
          'Expected at least one subschema in #/properties/stringOrNumber/anyOf to validate.',
        );
      }
      if (context != null && _constraintp1m0_0 && _constraintp1c0_0 != null) {
        context.mergeFrom(_constraintp1c0_0!);
      }
      if (context != null && _constraintp1m0_1 && _constraintp1c0_1 != null) {
        context.mergeFrom(_constraintp1c0_1!);
      }
    }
  }
}
