// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/anyof_example/schema.json
// Generated by json_schema2dart

import 'any_of_example_complex_union.dart';
import 'any_of_example_string_or_number.dart';
import 'validation_error.dart';

/// Demonstrates anyOf unions
class AnyOfExample {
  final AnyOfExampleComplexUnion? complexUnion;
  final AnyOfExampleStringOrNumber? stringOrNumber;

  const AnyOfExample({
    this.complexUnion,
    this.stringOrNumber,
  });

  factory AnyOfExample.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final complexUnion = json['complexUnion'] == null ? null : AnyOfExampleComplexUnion.fromJson((json['complexUnion'] as Map).cast<String, dynamic>());
    remaining.remove('complexUnion');
    final stringOrNumber = json['stringOrNumber'] == null ? null : AnyOfExampleStringOrNumber.fromJson((json['stringOrNumber'] as Map).cast<String, dynamic>());
    remaining.remove('stringOrNumber');
    return AnyOfExample(
      complexUnion: complexUnion,
      stringOrNumber: stringOrNumber,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (complexUnion != null) map['complexUnion'] = complexUnion!.toJson();
    if (stringOrNumber != null) map['stringOrNumber'] = stringOrNumber!.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
