// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/anyof_example/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

sealed class AnyOfExampleStringOrNumber {
  const AnyOfExampleStringOrNumber();

  void validate({String pointer = '', ValidationContext? context});

  factory AnyOfExampleStringOrNumber.fromJson(dynamic json) {
    if (json is String) return AnyOfExampleStringOrNumberString(json);
    if (json is num) return AnyOfExampleStringOrNumberNum(json);
    throw ArgumentError('Invalid AnyOfExampleStringOrNumber value type: ${json.runtimeType}');
  }

  dynamic toJson();
}
class AnyOfExampleStringOrNumberString extends AnyOfExampleStringOrNumber {
  final String value;

  const AnyOfExampleStringOrNumberString(this.value) : super();

  @override
  dynamic toJson() => value;
}
class AnyOfExampleStringOrNumberNum extends AnyOfExampleStringOrNumber {
  final double value;

  const AnyOfExampleStringOrNumberNum(this.value) : super();

  @override
  dynamic toJson() => value;
}
