// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/anyof_example/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

sealed class AnyOfExampleComplexUnion {
  const AnyOfExampleComplexUnion();

  void validate({String pointer = '', ValidationContext? context});

  factory AnyOfExampleComplexUnion.fromJson(Map<String, dynamic> json) {
    final keys = json.keys.toSet();
    final sortedKeys = keys.toList()..sort();
    final constMatches = <AnyOfExampleComplexUnion Function(Map<String, dynamic>)>[];
    final constMatchNames = <String>[];
    if (json['type'] == 'user') {
      constMatches.add(AnyOfExampleComplexUnionObject.fromJson);
      constMatchNames.add('AnyOfExampleComplexUnionObject');
    }
    if (json['type'] == 'admin') {
      constMatches.add(AnyOfExampleComplexUnionObject2.fromJson);
      constMatchNames.add('AnyOfExampleComplexUnionObject2');
    }
    if (constMatches.length == 1) {
      return constMatches.single(json);
    }
    if (constMatches.length > 1) {
      throw ArgumentError('Ambiguous AnyOfExampleComplexUnion variant matched const heuristics: ${constMatchNames.join(', ')}');
    }
    final requiredMatches = <AnyOfExampleComplexUnion Function(Map<String, dynamic>)>[];
    final requiredMatchNames = <String>[];
    if (keys.contains('type') && keys.contains('username')) {
      requiredMatches.add(AnyOfExampleComplexUnionObject.fromJson);
      requiredMatchNames.add('AnyOfExampleComplexUnionObject');
    }
    if (keys.contains('type') && keys.contains('adminLevel')) {
      requiredMatches.add(AnyOfExampleComplexUnionObject2.fromJson);
      requiredMatchNames.add('AnyOfExampleComplexUnionObject2');
    }
    if (requiredMatches.length == 1) {
      return requiredMatches.single(json);
    }
    if (requiredMatches.length > 1) {
      throw ArgumentError('Ambiguous AnyOfExampleComplexUnion variant matched required-property heuristics: ${requiredMatchNames.join(', ')}');
    }
    throw ArgumentError('No AnyOfExampleComplexUnion variant matched heuristics (keys: ${sortedKeys.join(', ')}).');
  }

  Map<String, dynamic> toJson();
}
class AnyOfExampleComplexUnionObject extends AnyOfExampleComplexUnion {
  /// Constraints: const: user
  final String type;
  final String username;

  const AnyOfExampleComplexUnionObject({
    required this.type,
    required this.username,
  }) : super();

  factory AnyOfExampleComplexUnionObject.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final type = json['type'] as String;
    remaining.remove('type');
    final username = json['username'] as String;
    remaining.remove('username');
    return AnyOfExampleComplexUnionObject(
      type: type,
      username: username,
    );
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['type'] = type;
    map['username'] = username;
    return map;
  }

  @override
  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'type');
    final _value0 = type;
    context?.markProperty(pointer, 'type');
    final _actualp0 = _value0;
    if (_actualp0 != 'user') {
      throwValidationError(_ptr0, 'const', 'Expected value equal to \'user\' but found ' + _actualp0.toString() + '.');
    }
    final _ptr1 = appendJsonPointer(pointer, 'username');
    final _value1 = username;
    context?.markProperty(pointer, 'username');
  }
}
class AnyOfExampleComplexUnionObject2 extends AnyOfExampleComplexUnion {
  final int adminLevel;
  /// Constraints: const: admin
  final String type;

  const AnyOfExampleComplexUnionObject2({
    required this.adminLevel,
    required this.type,
  }) : super();

  factory AnyOfExampleComplexUnionObject2.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final adminLevel = json['adminLevel'] as int;
    remaining.remove('adminLevel');
    final type = json['type'] as String;
    remaining.remove('type');
    return AnyOfExampleComplexUnionObject2(
      adminLevel: adminLevel,
      type: type,
    );
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['adminLevel'] = adminLevel;
    map['type'] = type;
    return map;
  }

  @override
  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'adminLevel');
    final _value0 = adminLevel;
    context?.markProperty(pointer, 'adminLevel');
    final _ptr1 = appendJsonPointer(pointer, 'type');
    final _value1 = type;
    context?.markProperty(pointer, 'type');
    final _actualp1 = _value1;
    if (_actualp1 != 'admin') {
      throwValidationError(_ptr1, 'const', 'Expected value equal to \'admin\' but found ' + _actualp1.toString() + '.');
    }
  }
}
