// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/anyof_example/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

sealed class ComplexUnion {
  const ComplexUnion();

  void validate({String pointer = '', ValidationContext? context});

  factory ComplexUnion.fromJson(Map<String, dynamic> json) {
    final keys = json.keys.toSet();
    final sortedKeys = keys.toList()..sort();
    final constMatches = <ComplexUnion Function(Map<String, dynamic>)>[];
    final constMatchNames = <String>[];
    if (json['type'] == 'user') {
      constMatches.add(User.fromJson);
      constMatchNames.add('User');
    }
    if (json['type'] == 'admin') {
      constMatches.add(Admin.fromJson);
      constMatchNames.add('Admin');
    }
    if (constMatches.length == 1) {
      return constMatches.single(json);
    }
    if (constMatches.length > 1) {
      throw ArgumentError(
        'Ambiguous ComplexUnion variant matched const heuristics: ${constMatchNames.join(', ')}',
      );
    }
    final requiredMatches = <ComplexUnion Function(Map<String, dynamic>)>[];
    final requiredMatchNames = <String>[];
    if (keys.contains('type') && keys.contains('username')) {
      requiredMatches.add(User.fromJson);
      requiredMatchNames.add('User');
    }
    if (keys.contains('type') && keys.contains('adminLevel')) {
      requiredMatches.add(Admin.fromJson);
      requiredMatchNames.add('Admin');
    }
    if (requiredMatches.length == 1) {
      return requiredMatches.single(json);
    }
    if (requiredMatches.length > 1) {
      throw ArgumentError(
        'Ambiguous ComplexUnion variant matched required-property heuristics: ${requiredMatchNames.join(', ')}',
      );
    }
    throw ArgumentError(
      'No ComplexUnion variant matched heuristics (keys: ${sortedKeys.join(', ')}).',
    );
  }

  Map<String, dynamic> toJson();
}

class User extends ComplexUnion {
  /// Constraints: const: user
  final String type;
  final String username;

  const User({required this.type, required this.username}) : super();

  factory User.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final type = json['type'] as String;
    remaining.remove('type');
    final username = json['username'] as String;
    remaining.remove('username');
    return User(type: type, username: username);
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['type'] = type;
    map['username'] = username;
    return map;
  }

  @override
  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'type');
    final _value0 = type;
    context?.markProperty(pointer, 'type');
    final _actualp0 = _value0;
    if (_actualp0 != 'user') {
      throwValidationError(
        _ptr0,
        'const',
        'Expected value equal to \'user\' but found ' +
            _actualp0.toString() +
            '.',
      );
    }
    final _ptr1 = appendJsonPointer(pointer, 'username');
    final _value1 = username;
    context?.markProperty(pointer, 'username');
  }
}

class Admin extends ComplexUnion {
  final int adminLevel;

  /// Constraints: const: admin
  final String type;

  const Admin({required this.adminLevel, required this.type}) : super();

  factory Admin.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final adminLevel = json['adminLevel'] as int;
    remaining.remove('adminLevel');
    final type = json['type'] as String;
    remaining.remove('type');
    return Admin(adminLevel: adminLevel, type: type);
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['adminLevel'] = adminLevel;
    map['type'] = type;
    return map;
  }

  @override
  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'adminLevel');
    final _value0 = adminLevel;
    context?.markProperty(pointer, 'adminLevel');
    final _ptr1 = appendJsonPointer(pointer, 'type');
    final _value1 = type;
    context?.markProperty(pointer, 'type');
    final _actualp1 = _value1;
    if (_actualp1 != 'admin') {
      throwValidationError(
        _ptr1,
        'const',
        'Expected value equal to \'admin\' but found ' +
            _actualp1.toString() +
            '.',
      );
    }
  }
}
