// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/anyof_example/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

sealed class StringOrNumber {
  const StringOrNumber();

  void validate({String pointer = '', ValidationContext? context});

  factory StringOrNumber.fromJson(dynamic json) {
    if (json is String) return StringOrNumberString(json);
    if (json is num) return StringOrNumberNum(json.toDouble());
    throw ArgumentError(
      'Invalid StringOrNumber value type: ${json.runtimeType}',
    );
  }

  dynamic toJson();
}

class StringOrNumberString extends StringOrNumber {
  final String value;

  const StringOrNumberString(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class StringOrNumberNum extends StringOrNumber {
  final double value;

  const StringOrNumberNum(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
