// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/anyof_example/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class User {
  /// Constraints: const: user
  final String type;
  final String username;

  const User({
    required this.type,
    required this.username,
  });

  factory User.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final type = json['type'] as String;
    remaining.remove('type');
    final username = json['username'] as String;
    remaining.remove('username');
    return User(
      type: type,
      username: username,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['type'] = type;
    map['username'] = username;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'type');
    final _value0 = type;
    context?.markProperty(pointer, 'type');
    final _actualp0 = _value0;
    if (_actualp0 != 'user') {
      throwValidationError(_ptr0, 'const', 'Expected value equal to \'user\' but found ' + _actualp0.toString() + '.');
    }
    final _ptr1 = appendJsonPointer(pointer, 'username');
    final _value1 = username;
    context?.markProperty(pointer, 'username');
  }
}
