// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/pubspec_subset/schema.json
// Generated by json_schema2dart

/// Publish destination or 'none'.
enum PublishTo { none, pubDev }

extension PublishToJson on PublishTo {
  String toJson() =>
      const {PublishTo.none: 'none', PublishTo.pubDev: 'pub.dev'}[this]!;

  static PublishTo fromJson(String value) =>
      const {'none': PublishTo.none, 'pub.dev': PublishTo.pubDev}[value]!;
}
