// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/additional_properties/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class AdditionalPropertiesExampleFlexibleObject {
  final int? id;

  const AdditionalPropertiesExampleFlexibleObject({
    this.id,
  });

  factory AdditionalPropertiesExampleFlexibleObject.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final id = json['id'] as int?;
    remaining.remove('id');
    return AdditionalPropertiesExampleFlexibleObject(
      id: id,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (id != null) map['id'] = id;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
