// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/additional_properties/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class FlexibleObject {
  final int? id;

  const FlexibleObject({this.id});

  factory FlexibleObject.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final id = json['id'] as int?;
    remaining.remove('id');
    return FlexibleObject(id: id);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (id != null) map['id'] = id;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
