// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/additional_properties/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class TypedAdditional {
  final String? baseField;
  final Map<String, double>? additionalProperties;

  const TypedAdditional({this.baseField, this.additionalProperties});

  factory TypedAdditional.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final baseField = json['baseField'] as String?;
    remaining.remove('baseField');
    var unmatched = Map<String, dynamic>.from(remaining);
    Map<String, double>? additionalPropertiesValue;
    if (unmatched.isNotEmpty) {
      final additionalPropertiesMap = <String, double>{};
      for (final entry in unmatched.entries) {
        final value = entry.value;
        additionalPropertiesMap[entry.key] = value as double;
      }
      additionalPropertiesValue = additionalPropertiesMap.isEmpty
          ? null
          : additionalPropertiesMap;
      unmatched = <String, dynamic>{};
    } else {
      additionalPropertiesValue = null;
    }
    return TypedAdditional(
      baseField: baseField,
      additionalProperties: additionalPropertiesValue,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (baseField != null) map['baseField'] = baseField;
    if (additionalProperties != null) {
      additionalProperties!.forEach((key, value) {
        map[key] = value;
      });
    }
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
