// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/enum_mixed_types/schema.json
// Generated by json_schema2dart

/// Complex mixed enum with objects
sealed class ComplexMixedEnum {
  const ComplexMixedEnum();

  factory ComplexMixedEnum.fromJson(dynamic json) {
    if (json is String) return ComplexMixedEnumString(json);
    if (json is int) return ComplexMixedEnumint(json);
    if (json is bool) return ComplexMixedEnumbool(json);
    if (json == null) return const ComplexMixedEnumNull();
    throw Exception('Unknown ComplexMixedEnum type: ${json.runtimeType}');
  }

  dynamic toJson();
}

class ComplexMixedEnumString extends ComplexMixedEnum {
  const ComplexMixedEnumString(this.value);

  final String value;

  @override
  dynamic toJson() => value;
}

class ComplexMixedEnumint extends ComplexMixedEnum {
  const ComplexMixedEnumint(this.value);

  final int value;

  @override
  dynamic toJson() => value;
}

class ComplexMixedEnumbool extends ComplexMixedEnum {
  const ComplexMixedEnumbool(this.value);

  final bool value;

  @override
  dynamic toJson() => value;
}

class ComplexMixedEnumNull extends ComplexMixedEnum {
  const ComplexMixedEnumNull();

  @override
  dynamic toJson() => null;
}

class ComplexMixedEnumdynamic extends ComplexMixedEnum {
  const ComplexMixedEnumdynamic(this.value);

  final dynamic value;

  @override
  dynamic toJson() => value;
}
