// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/enum_mixed_types/schema.json
// Generated by json_schema2dart

/// Mixed type enum with string, number, boolean, and null
sealed class MixedEnum {
  const MixedEnum();

  factory MixedEnum.fromJson(dynamic json) {
    if (json is String) return MixedEnumString(json);
    if (json is int) return MixedEnumint(json);
    if (json is bool) return MixedEnumbool(json);
    if (json == null) return const MixedEnumNull();
    throw Exception('Unknown MixedEnum type: ${json.runtimeType}');
  }

  dynamic toJson();
}

class MixedEnumString extends MixedEnum {
  const MixedEnumString(this.value);

  final String value;

  @override
  dynamic toJson() => value;
}

class MixedEnumint extends MixedEnum {
  const MixedEnumint(this.value);

  final int value;

  @override
  dynamic toJson() => value;
}

class MixedEnumbool extends MixedEnum {
  const MixedEnumbool(this.value);

  final bool value;

  @override
  dynamic toJson() => value;
}

class MixedEnumNull extends MixedEnum {
  const MixedEnumNull();

  @override
  dynamic toJson() => null;
}
