// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/enum_mixed_types/schema.json
// Generated by json_schema2dart

/// Mixed type enum with string, number, boolean, and null
sealed class MixedTypeEnumExampleMixedEnum {
  const MixedTypeEnumExampleMixedEnum();

  factory MixedTypeEnumExampleMixedEnum.fromJson(dynamic json) {
    if (json is String) return MixedTypeEnumExampleMixedEnumString(json);
    if (json is int) return MixedTypeEnumExampleMixedEnumint(json);
    if (json is bool) return MixedTypeEnumExampleMixedEnumbool(json);
    if (json == null) return const MixedTypeEnumExampleMixedEnumNull();
    throw Exception('Unknown MixedTypeEnumExampleMixedEnum type: ${json.runtimeType}');
  }

  dynamic toJson();
}

class MixedTypeEnumExampleMixedEnumString extends MixedTypeEnumExampleMixedEnum {
  const MixedTypeEnumExampleMixedEnumString(this.value);

  final String value;

  @override
  dynamic toJson() => value;
}

class MixedTypeEnumExampleMixedEnumint extends MixedTypeEnumExampleMixedEnum {
  const MixedTypeEnumExampleMixedEnumint(this.value);

  final int value;

  @override
  dynamic toJson() => value;
}

class MixedTypeEnumExampleMixedEnumbool extends MixedTypeEnumExampleMixedEnum {
  const MixedTypeEnumExampleMixedEnumbool(this.value);

  final bool value;

  @override
  dynamic toJson() => value;
}

class MixedTypeEnumExampleMixedEnumNull extends MixedTypeEnumExampleMixedEnum {
  const MixedTypeEnumExampleMixedEnumNull();

  @override
  dynamic toJson() => null;
}
