// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/enum_mixed_types/schema.json
// Generated by json_schema2dart

/// Simple number enum
sealed class MixedTypeEnumExampleNumberEnum {
  const MixedTypeEnumExampleNumberEnum();

  factory MixedTypeEnumExampleNumberEnum.fromJson(dynamic json) {
    if (json is int) return MixedTypeEnumExampleNumberEnumint(json);
    throw Exception('Unknown MixedTypeEnumExampleNumberEnum type: ${json.runtimeType}');
  }

  dynamic toJson();
}

class MixedTypeEnumExampleNumberEnumint extends MixedTypeEnumExampleNumberEnum {
  const MixedTypeEnumExampleNumberEnumint(this.value);

  final int value;

  @override
  dynamic toJson() => value;
}
