// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/enum_mixed_types/schema.json
// Generated by json_schema2dart

/// Complex mixed enum with objects
sealed class MixedTypeEnumExampleComplexMixedEnum {
  const MixedTypeEnumExampleComplexMixedEnum();

  factory MixedTypeEnumExampleComplexMixedEnum.fromJson(dynamic json) {
    if (json is String) return MixedTypeEnumExampleComplexMixedEnumString(json);
    if (json is int) return MixedTypeEnumExampleComplexMixedEnumint(json);
    if (json is bool) return MixedTypeEnumExampleComplexMixedEnumbool(json);
    if (json == null) return const MixedTypeEnumExampleComplexMixedEnumNull();
    throw Exception('Unknown MixedTypeEnumExampleComplexMixedEnum type: ${json.runtimeType}');
  }

  dynamic toJson();
}

class MixedTypeEnumExampleComplexMixedEnumString extends MixedTypeEnumExampleComplexMixedEnum {
  const MixedTypeEnumExampleComplexMixedEnumString(this.value);

  final String value;

  @override
  dynamic toJson() => value;
}

class MixedTypeEnumExampleComplexMixedEnumint extends MixedTypeEnumExampleComplexMixedEnum {
  const MixedTypeEnumExampleComplexMixedEnumint(this.value);

  final int value;

  @override
  dynamic toJson() => value;
}

class MixedTypeEnumExampleComplexMixedEnumbool extends MixedTypeEnumExampleComplexMixedEnum {
  const MixedTypeEnumExampleComplexMixedEnumbool(this.value);

  final bool value;

  @override
  dynamic toJson() => value;
}

class MixedTypeEnumExampleComplexMixedEnumNull extends MixedTypeEnumExampleComplexMixedEnum {
  const MixedTypeEnumExampleComplexMixedEnumNull();

  @override
  dynamic toJson() => null;
}

class MixedTypeEnumExampleComplexMixedEnumdynamic extends MixedTypeEnumExampleComplexMixedEnum {
  const MixedTypeEnumExampleComplexMixedEnumdynamic(this.value);

  final dynamic value;

  @override
  dynamic toJson() => value;
}
