// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/enum_mixed_types/schema.json
// Generated by json_schema2dart

/// Simple string enum
enum MixedTypeEnumExampleStringEnum { red, green, blue }

extension MixedTypeEnumExampleStringEnumJson on MixedTypeEnumExampleStringEnum {
  String toJson() => const {
        MixedTypeEnumExampleStringEnum.red: 'red',
        MixedTypeEnumExampleStringEnum.green: 'green',
        MixedTypeEnumExampleStringEnum.blue: 'blue',
      }[this]!;

  static MixedTypeEnumExampleStringEnum fromJson(String value) => const {
        'red': MixedTypeEnumExampleStringEnum.red,
        'green': MixedTypeEnumExampleStringEnum.green,
        'blue': MixedTypeEnumExampleStringEnum.blue,
      }[value]!;
}
