// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/enum_mixed_types/schema.json
// Generated by json_schema2dart

import 'string_enum.dart';
import 'validation_error.dart';

/// Demonstrates enums with mixed types
class MixedTypeEnumExample {
  /// Complex mixed enum with objects
  final ComplexMixedEnum? complexMixedEnum;

  /// Mixed type enum with string, number, boolean, and null
  final MixedEnum? mixedEnum;

  /// Simple number enum
  final NumberEnum? numberEnum;

  /// Simple string enum
  final StringEnum? stringEnum;

  const MixedTypeEnumExample({
    this.complexMixedEnum,
    this.mixedEnum,
    this.numberEnum,
    this.stringEnum,
  });

  factory MixedTypeEnumExample.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final complexMixedEnum = json['complexMixedEnum'] == null
        ? null
        : ComplexMixedEnum.fromJson(json['complexMixedEnum']);
    remaining.remove('complexMixedEnum');
    final mixedEnum = json['mixedEnum'] == null
        ? null
        : MixedEnum.fromJson(json['mixedEnum']);
    remaining.remove('mixedEnum');
    final numberEnum = json['numberEnum'] == null
        ? null
        : NumberEnum.fromJson(json['numberEnum']);
    remaining.remove('numberEnum');
    final stringEnum = json['stringEnum'] == null
        ? null
        : StringEnumJson.fromJson(json['stringEnum'] as String);
    remaining.remove('stringEnum');
    return MixedTypeEnumExample(
      complexMixedEnum: complexMixedEnum,
      mixedEnum: mixedEnum,
      numberEnum: numberEnum,
      stringEnum: stringEnum,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (complexMixedEnum != null)
      map['complexMixedEnum'] = complexMixedEnum!.toJson();
    if (mixedEnum != null) map['mixedEnum'] = mixedEnum!.toJson();
    if (numberEnum != null) map['numberEnum'] = numberEnum!.toJson();
    if (stringEnum != null) map['stringEnum'] = stringEnum!.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
