// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/enum_mixed_types/schema.json
// Generated by json_schema2dart

/// Simple number enum
sealed class NumberEnum {
  const NumberEnum();

  factory NumberEnum.fromJson(dynamic json) {
    if (json is int) return NumberEnumint(json);
    throw Exception('Unknown NumberEnum type: ${json.runtimeType}');
  }

  dynamic toJson();
}

class NumberEnumint extends NumberEnum {
  const NumberEnumint(this.value);

  final int value;

  @override
  dynamic toJson() => value;
}
