// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/enum_mixed_types/schema.json
// Generated by json_schema2dart

/// Simple string enum
enum StringEnum { red, green, blue }

extension StringEnumJson on StringEnum {
  String toJson() => const {
    StringEnum.red: 'red',
    StringEnum.green: 'green',
    StringEnum.blue: 'blue',
  }[this]!;

  static StringEnum fromJson(String value) => const {
    'red': StringEnum.red,
    'green': StringEnum.green,
    'blue': StringEnum.blue,
  }[value]!;
}
