// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/string_formats/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// Demonstrates string format validation
class StringFormatsExample {
  /// Format: date (format hints disabled).
  ///
  /// Calendar date as defined by RFC 3339 full-date.
  ///
  /// See https://json-schema.org/draft/2020-12/json-schema-validation.html#name-dates-times-and-duration.
  final String? date;

  /// Format: date-time (format hints disabled).
  ///
  /// Date and time as defined by RFC 3339 date-time.
  ///
  /// See https://json-schema.org/draft/2020-12/json-schema-validation.html#name-dates-times-and-duration.
  final String? dateTime;

  /// Format: email (format hints disabled).
  ///
  /// Email address as defined by RFC 5321 Mailbox.
  ///
  /// See https://json-schema.org/draft/2020-12/json-schema-validation.html#name-email-addresses.
  final String? email;

  /// Format: hostname (format hints disabled).
  ///
  /// Hostname as defined by RFC 1123.
  ///
  /// See https://json-schema.org/draft/2020-12/json-schema-validation.html#name-hostnames.
  final String? hostname;

  /// Format: ipv4 (format hints disabled).
  ///
  /// IPv4 address as defined by RFC 2673 section 3.2.
  ///
  /// See https://json-schema.org/draft/2020-12/json-schema-validation.html#name-ip-addresses.
  final String? ipv4;

  /// Format: ipv6 (format hints disabled).
  ///
  /// IPv6 address as defined by RFC 4291.
  ///
  /// See https://json-schema.org/draft/2020-12/json-schema-validation.html#name-ip-addresses.
  final String? ipv6;

  /// Must start with uppercase letter followed by lowercase
  /// Constraints: pattern: ^[A-Z][a-z]+$
  final String? patternString;

  /// Format: time (no type mapping available).
  ///
  /// Time of day as defined by RFC 3339 full-time.
  ///
  /// See https://json-schema.org/draft/2020-12/json-schema-validation.html#name-dates-times-and-duration.
  final String? time;

  /// Format: uri (format hints disabled).
  ///
  /// URI as defined by RFC 3986.
  ///
  /// See https://json-schema.org/draft/2020-12/json-schema-validation.html#name-resource-identifiers.
  final String? uri;

  /// Format: uuid (format hints disabled).
  ///
  /// Universally Unique Identifier as defined by RFC 4122.
  ///
  /// See https://json-schema.org/draft/2020-12/json-schema-validation.html#name-resource-identifiers.
  final String? uuid;

  const StringFormatsExample({
    this.date,
    this.dateTime,
    this.email,
    this.hostname,
    this.ipv4,
    this.ipv6,
    this.patternString,
    this.time,
    this.uri,
    this.uuid,
  });

  factory StringFormatsExample.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final date = json['date'] as String?;
    remaining.remove('date');
    final dateTime = json['dateTime'] as String?;
    remaining.remove('dateTime');
    final email = json['email'] as String?;
    remaining.remove('email');
    final hostname = json['hostname'] as String?;
    remaining.remove('hostname');
    final ipv4 = json['ipv4'] as String?;
    remaining.remove('ipv4');
    final ipv6 = json['ipv6'] as String?;
    remaining.remove('ipv6');
    final patternString = json['patternString'] as String?;
    remaining.remove('patternString');
    final time = json['time'] as String?;
    remaining.remove('time');
    final uri = json['uri'] as String?;
    remaining.remove('uri');
    final uuid = json['uuid'] as String?;
    remaining.remove('uuid');
    return StringFormatsExample(
      date: date,
      dateTime: dateTime,
      email: email,
      hostname: hostname,
      ipv4: ipv4,
      ipv6: ipv6,
      patternString: patternString,
      time: time,
      uri: uri,
      uuid: uuid,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (date != null) map['date'] = date;
    if (dateTime != null) map['dateTime'] = dateTime;
    if (email != null) map['email'] = email;
    if (hostname != null) map['hostname'] = hostname;
    if (ipv4 != null) map['ipv4'] = ipv4;
    if (ipv6 != null) map['ipv6'] = ipv6;
    if (patternString != null) map['patternString'] = patternString;
    if (time != null) map['time'] = time;
    if (uri != null) map['uri'] = uri;
    if (uuid != null) map['uuid'] = uuid;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'date');
    final _value0 = date;
    if (_value0 != null) {
      context?.markProperty(pointer, 'date');
    }
    final _ptr1 = appendJsonPointer(pointer, 'dateTime');
    final _value1 = dateTime;
    if (_value1 != null) {
      context?.markProperty(pointer, 'dateTime');
    }
    final _ptr2 = appendJsonPointer(pointer, 'email');
    final _value2 = email;
    if (_value2 != null) {
      context?.markProperty(pointer, 'email');
    }
    final _ptr3 = appendJsonPointer(pointer, 'hostname');
    final _value3 = hostname;
    if (_value3 != null) {
      context?.markProperty(pointer, 'hostname');
    }
    final _ptr4 = appendJsonPointer(pointer, 'ipv4');
    final _value4 = ipv4;
    if (_value4 != null) {
      context?.markProperty(pointer, 'ipv4');
    }
    final _ptr5 = appendJsonPointer(pointer, 'ipv6');
    final _value5 = ipv6;
    if (_value5 != null) {
      context?.markProperty(pointer, 'ipv6');
    }
    final _ptr6 = appendJsonPointer(pointer, 'patternString');
    final _value6 = patternString;
    if (_value6 != null) {
      context?.markProperty(pointer, 'patternString');
      final _patternp6 = RegExp('^[A-Z][a-z]+\$');
      if (!_patternp6.hasMatch(_value6)) {
        throwValidationError(
          _ptr6,
          'pattern',
          'Expected value to match pattern ^[A-Z][a-z]+\$ but found ' +
              _value6 +
              '.',
        );
      }
    }
    final _ptr7 = appendJsonPointer(pointer, 'time');
    final _value7 = time;
    if (_value7 != null) {
      context?.markProperty(pointer, 'time');
    }
    final _ptr8 = appendJsonPointer(pointer, 'uri');
    final _value8 = uri;
    if (_value8 != null) {
      context?.markProperty(pointer, 'uri');
    }
    final _ptr9 = appendJsonPointer(pointer, 'uuid');
    final _value9 = uuid;
    if (_value9 != null) {
      context?.markProperty(pointer, 'uuid');
    }
  }
}
