// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/array_constraints/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// Demonstrates array validation keywords
class ArrayConstraintsExample {
  /// Array must contain at least 2 numbers >= 5
  final List<double>? containsExample;
  /// Array can have at most 10 items
  /// Constraints: maxItems: 10
  final List<double>? maxItems;
  /// Array must have at least 1 item
  /// Constraints: minItems: 1
  final List<String>? minItems;
  /// Fixed tuple with exactly 3 items
  final List<dynamic>? tupleArray;
  /// All items must be unique
  /// Constraints: uniqueItems: true
  final List<String>? uniqueItems;

  const ArrayConstraintsExample({
    this.containsExample,
    this.maxItems,
    this.minItems,
    this.tupleArray,
    this.uniqueItems,
  });

  factory ArrayConstraintsExample.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final containsExample = json['containsExample'] == null ? null : (json['containsExample'] as List).map((e) => e as double).toList();
    remaining.remove('containsExample');
    final maxItems = json['maxItems'] == null ? null : (json['maxItems'] as List).map((e) => e as double).toList();
    remaining.remove('maxItems');
    final minItems = json['minItems'] == null ? null : (json['minItems'] as List).map((e) => e as String).toList();
    remaining.remove('minItems');
    final tupleArray = json['tupleArray'] == null ? null : (json['tupleArray'] as List).map((e) => e).toList();
    remaining.remove('tupleArray');
    final uniqueItems = json['uniqueItems'] == null ? null : (json['uniqueItems'] as List).map((e) => e as String).toList();
    remaining.remove('uniqueItems');
    return ArrayConstraintsExample(
      containsExample: containsExample,
      maxItems: maxItems,
      minItems: minItems,
      tupleArray: tupleArray,
      uniqueItems: uniqueItems,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (containsExample != null) map['containsExample'] = containsExample;
    if (maxItems != null) map['maxItems'] = maxItems;
    if (minItems != null) map['minItems'] = minItems;
    if (tupleArray != null) map['tupleArray'] = tupleArray;
    if (uniqueItems != null) map['uniqueItems'] = uniqueItems;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'containsExample');
    final _value0 = containsExample;
    if (_value0 != null) {
      context?.markProperty(pointer, 'containsExample');
      final _lenp0 = _value0.length;
      final _evaluatedp0 = List<bool>.filled(_lenp0, false);
      for (var i = 0; i < _lenp0; i++) {
        final itemPointer = appendJsonPointer(_ptr0, i.toString());
        final item = _value0[i];
        _evaluatedp0[i] = true;
        context?.markItem(_ptr0, i);
      }
      var _containsCountp0 = 0;
      for (var i = 0; i < _lenp0; i++) {
        final itemPointer = appendJsonPointer(_ptr0, i.toString());
        final item = _value0[i];
        final matches = true;
        if (matches) {
          _containsCountp0++;
          if (!_evaluatedp0[i]) { _evaluatedp0[i] = true; }
          context?.markItem(_ptr0, i);
        }
      }
      if (_containsCountp0 < 2) {
        throwValidationError(_ptr0, 'contains', 'Expected at least 2 item(s) matching "contains" but found ' + _containsCountp0.toString() + '.');
      }
    }
    final _ptr1 = appendJsonPointer(pointer, 'maxItems');
    final _value1 = maxItems;
    if (_value1 != null) {
      context?.markProperty(pointer, 'maxItems');
    }
    final _ptr2 = appendJsonPointer(pointer, 'minItems');
    final _value2 = minItems;
    if (_value2 != null) {
      context?.markProperty(pointer, 'minItems');
    }
    final _ptr3 = appendJsonPointer(pointer, 'tupleArray');
    final _value3 = tupleArray;
    if (_value3 != null) {
      context?.markProperty(pointer, 'tupleArray');
    }
    final _ptr4 = appendJsonPointer(pointer, 'uniqueItems');
    final _value4 = uniqueItems;
    if (_value4 != null) {
      context?.markProperty(pointer, 'uniqueItems');
    }
  }
}
