// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/union_types/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// Discriminated union using kind field
sealed class ComplexUnion {
  const ComplexUnion();

  void validate({String pointer = '', ValidationContext? context});

  factory ComplexUnion.fromJson(Map<String, dynamic> json) {
    final keys = json.keys.toSet();
    final sortedKeys = keys.toList()..sort();
    final constMatches = <ComplexUnion Function(Map<String, dynamic>)>[];
    final constMatchNames = <String>[];
    if (json['kind'] == 'circle') {
      constMatches.add(Circle.fromJson);
      constMatchNames.add('Circle');
    }
    if (json['kind'] == 'rectangle') {
      constMatches.add(Rectangle.fromJson);
      constMatchNames.add('Rectangle');
    }
    if (json['kind'] == 'triangle') {
      constMatches.add(Triangle.fromJson);
      constMatchNames.add('Triangle');
    }
    if (constMatches.length == 1) {
      return constMatches.single(json);
    }
    if (constMatches.length > 1) {
      throw ArgumentError(
        'Ambiguous ComplexUnion variant matched const heuristics: ${constMatchNames.join(', ')}',
      );
    }
    final requiredMatches = <ComplexUnion Function(Map<String, dynamic>)>[];
    final requiredMatchNames = <String>[];
    if (keys.contains('kind') && keys.contains('radius')) {
      requiredMatches.add(Circle.fromJson);
      requiredMatchNames.add('Circle');
    }
    if (keys.contains('kind') &&
        keys.contains('width') &&
        keys.contains('height')) {
      requiredMatches.add(Rectangle.fromJson);
      requiredMatchNames.add('Rectangle');
    }
    if (keys.contains('kind') &&
        keys.contains('base') &&
        keys.contains('height')) {
      requiredMatches.add(Triangle.fromJson);
      requiredMatchNames.add('Triangle');
    }
    if (requiredMatches.length == 1) {
      return requiredMatches.single(json);
    }
    if (requiredMatches.length > 1) {
      throw ArgumentError(
        'Ambiguous ComplexUnion variant matched required-property heuristics: ${requiredMatchNames.join(', ')}',
      );
    }
    throw ArgumentError(
      'No ComplexUnion variant matched heuristics (keys: ${sortedKeys.join(', ')}).',
    );
  }

  Map<String, dynamic> toJson();
}

class Circle extends ComplexUnion {
  /// Constraints: const: circle
  final String kind;
  final double radius;

  const Circle({required this.kind, required this.radius}) : super();

  factory Circle.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final kind = json['kind'] as String;
    remaining.remove('kind');
    final radius = json['radius'] as double;
    remaining.remove('radius');
    return Circle(kind: kind, radius: radius);
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['kind'] = kind;
    map['radius'] = radius;
    return map;
  }

  @override
  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'kind');
    final _value0 = kind;
    context?.markProperty(pointer, 'kind');
    final _actualp0 = _value0;
    if (_actualp0 != 'circle') {
      throwValidationError(
        _ptr0,
        'const',
        'Expected value equal to \'circle\' but found ' +
            _actualp0.toString() +
            '.',
      );
    }
    final _ptr1 = appendJsonPointer(pointer, 'radius');
    final _value1 = radius;
    context?.markProperty(pointer, 'radius');
  }
}

class Rectangle extends ComplexUnion {
  final double height;

  /// Constraints: const: rectangle
  final String kind;
  final double width;

  const Rectangle({
    required this.height,
    required this.kind,
    required this.width,
  }) : super();

  factory Rectangle.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final height = json['height'] as double;
    remaining.remove('height');
    final kind = json['kind'] as String;
    remaining.remove('kind');
    final width = json['width'] as double;
    remaining.remove('width');
    return Rectangle(height: height, kind: kind, width: width);
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['height'] = height;
    map['kind'] = kind;
    map['width'] = width;
    return map;
  }

  @override
  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'height');
    final _value0 = height;
    context?.markProperty(pointer, 'height');
    final _ptr1 = appendJsonPointer(pointer, 'kind');
    final _value1 = kind;
    context?.markProperty(pointer, 'kind');
    final _actualp1 = _value1;
    if (_actualp1 != 'rectangle') {
      throwValidationError(
        _ptr1,
        'const',
        'Expected value equal to \'rectangle\' but found ' +
            _actualp1.toString() +
            '.',
      );
    }
    final _ptr2 = appendJsonPointer(pointer, 'width');
    final _value2 = width;
    context?.markProperty(pointer, 'width');
  }
}

class Triangle extends ComplexUnion {
  final double base;
  final double height;

  /// Constraints: const: triangle
  final String kind;

  const Triangle({required this.base, required this.height, required this.kind})
    : super();

  factory Triangle.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final base = json['base'] as double;
    remaining.remove('base');
    final height = json['height'] as double;
    remaining.remove('height');
    final kind = json['kind'] as String;
    remaining.remove('kind');
    return Triangle(base: base, height: height, kind: kind);
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['base'] = base;
    map['height'] = height;
    map['kind'] = kind;
    return map;
  }

  @override
  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'base');
    final _value0 = base;
    context?.markProperty(pointer, 'base');
    final _ptr1 = appendJsonPointer(pointer, 'height');
    final _value1 = height;
    context?.markProperty(pointer, 'height');
    final _ptr2 = appendJsonPointer(pointer, 'kind');
    final _value2 = kind;
    context?.markProperty(pointer, 'kind');
    final _actualp2 = _value2;
    if (_actualp2 != 'triangle') {
      throwValidationError(
        _ptr2,
        'const',
        'Expected value equal to \'triangle\' but found ' +
            _actualp2.toString() +
            '.',
      );
    }
  }
}
