// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/union_types/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// Can be string or number
sealed class SimpleUnion {
  const SimpleUnion();

  void validate({String pointer = '', ValidationContext? context});

  factory SimpleUnion.fromJson(dynamic json) {
    if (json is String) return SimpleUnionString(json);
    if (json is num) return SimpleUnionNum(json.toDouble());
    throw ArgumentError('Invalid SimpleUnion value type: ${json.runtimeType}');
  }

  dynamic toJson();
}

class SimpleUnionString extends SimpleUnion {
  final String value;

  const SimpleUnionString(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class SimpleUnionNum extends SimpleUnion {
  final double value;

  const SimpleUnionNum(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
