// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/union_types/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class Triangle {
  final double base;
  final double height;
  /// Constraints: const: triangle
  final String kind;

  const Triangle({
    required this.base,
    required this.height,
    required this.kind,
  });

  factory Triangle.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final base = json['base'] as double;
    remaining.remove('base');
    final height = json['height'] as double;
    remaining.remove('height');
    final kind = json['kind'] as String;
    remaining.remove('kind');
    return Triangle(
      base: base,
      height: height,
      kind: kind,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['base'] = base;
    map['height'] = height;
    map['kind'] = kind;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'base');
    final _value0 = base;
    context?.markProperty(pointer, 'base');
    final _ptr1 = appendJsonPointer(pointer, 'height');
    final _value1 = height;
    context?.markProperty(pointer, 'height');
    final _ptr2 = appendJsonPointer(pointer, 'kind');
    final _value2 = kind;
    context?.markProperty(pointer, 'kind');
    final _actualp2 = _value2;
    if (_actualp2 != 'triangle') {
      throwValidationError(_ptr2, 'const', 'Expected value equal to \'triangle\' but found ' + _actualp2.toString() + '.');
    }
  }
}
