// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/union_types/schema.json
// Generated by json_schema2dart

import 'union_types_example_complex_union.dart';
import 'validation_error.dart';

/// Demonstrates various union type patterns
class UnionTypesExample {
  /// Discriminated union using kind field
  final UnionTypesExampleComplexUnion? complexUnion;
  /// Can be string or number
  final String? simpleUnion;

  const UnionTypesExample({
    this.complexUnion,
    this.simpleUnion,
  });

  factory UnionTypesExample.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final complexUnion = json['complexUnion'] == null ? null : UnionTypesExampleComplexUnion.fromJson((json['complexUnion'] as Map).cast<String, dynamic>());
    remaining.remove('complexUnion');
    final simpleUnion = json['simpleUnion'] as String?;
    remaining.remove('simpleUnion');
    return UnionTypesExample(
      complexUnion: complexUnion,
      simpleUnion: simpleUnion,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (complexUnion != null) map['complexUnion'] = complexUnion!.toJson();
    if (simpleUnion != null) map['simpleUnion'] = simpleUnion;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
