// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/numeric_test/schema.json
// Generated by json_schema2dart

import 'config_cache.dart';
import 'config_database.dart';
import 'validation_error.dart';

/// Object config with nested properties
class Config {
  final ConfigCache? cache;
  final ConfigDatabase? database;

  const Config({
    this.cache,
    this.database,
  });

  factory Config.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final cache = json['cache'] == null ? null : ConfigCache.fromJson((json['cache'] as Map).cast<String, dynamic>());
    remaining.remove('cache');
    final database = json['database'] == null ? null : ConfigDatabase.fromJson((json['database'] as Map).cast<String, dynamic>());
    remaining.remove('database');
    return Config(
      cache: cache,
      database: database,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (cache != null) map['cache'] = cache!.toJson();
    if (database != null) map['database'] = database!.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
