// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/numeric_test/schema.json
// Generated by json_schema2dart

import 'config_object_cache.dart';
import 'config_object_database.dart';
import 'validation_error.dart';

/// Configuration with multiple variants
sealed class Config {
  const Config();

  void validate({String pointer = '', ValidationContext? context});

  factory Config.fromJson(dynamic json) {
    if (json is String) return ConfigString(json);
    if (json is List)
      return ConfigArray((json as List).map((e) => e as String).toList());
    if (json is! Map<String, dynamic>) {
      throw ArgumentError('Invalid Config value: ${json.runtimeType}');
    }
    final keys = json.keys.toSet();
    final sortedKeys = keys.toList()..sort();
    return ConfigObject.fromJson(json);
  }

  dynamic toJson();
}

class ConfigString extends Config {
  final String value;

  const ConfigString(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class ConfigArray extends Config {
  final List<String> value;

  const ConfigArray(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

/// Object config with nested properties
class ConfigObject extends Config {
  final ConfigObjectCache? cache;
  final ConfigObjectDatabase? database;

  const ConfigObject({this.cache, this.database}) : super();

  factory ConfigObject.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final cache = json['cache'] == null
        ? null
        : ConfigObjectCache.fromJson(
            (json['cache'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('cache');
    final database = json['database'] == null
        ? null
        : ConfigObjectDatabase.fromJson(
            (json['database'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('database');
    return ConfigObject(cache: cache, database: database);
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (cache != null) map['cache'] = cache!.toJson();
    if (database != null) map['database'] = database!.toJson();
    return map;
  }

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
