// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/numeric_test/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class ConfigCache {
  final bool? enabled;
  final int? ttl;

  const ConfigCache({
    this.enabled,
    this.ttl,
  });

  factory ConfigCache.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final enabled = json['enabled'] as bool?;
    remaining.remove('enabled');
    final ttl = json['ttl'] as int?;
    remaining.remove('ttl');
    return ConfigCache(
      enabled: enabled,
      ttl: ttl,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (enabled != null) map['enabled'] = enabled;
    if (ttl != null) map['ttl'] = ttl;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
