// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/numeric_test/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class ConfigObjectDatabase {
  final String? host;
  final int? port;

  const ConfigObjectDatabase({this.host, this.port});

  factory ConfigObjectDatabase.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final host = json['host'] as String?;
    remaining.remove('host');
    final port = json['port'] as int?;
    remaining.remove('port');
    return ConfigObjectDatabase(host: host, port: port);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (host != null) map['host'] = host;
    if (port != null) map['port'] = port;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
