// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/numeric_test/schema.json
// Generated by json_schema2dart

import 'config.dart';
import 'validation_error.dart';

class TestSchema {
  /// Configuration with multiple variants
  final Config config;

  const TestSchema({required this.config});

  factory TestSchema.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final config = Config.fromJson(
      (json['config'] as Map).cast<String, dynamic>(),
    );
    remaining.remove('config');
    return TestSchema(config: config);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['config'] = config.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'config');
    final _value0 = config;
    context?.markProperty(pointer, 'config');
    final _jsonp0 = _value0.toJson();
    final _constraintp0c0_0 = context == null ? null : ValidationContext();
    var _constraintp0m0_0 = false;
    try {
      final context = _constraintp0c0_0;
      final _constraintp0v0_0 = _jsonp0 as String;
      _constraintp0m0_0 = true;
    } on ValidationError {
    } catch (_) {}
    final _constraintp0c0_1 = context == null ? null : ValidationContext();
    var _constraintp0m0_1 = false;
    try {
      final context = _constraintp0c0_1;
      final _constraintp0v0_1 = (_jsonp0 as List)
          .map((e) => e as String)
          .toList();
      _constraintp0m0_1 = true;
    } on ValidationError {
    } catch (_) {}
    final _constraintp0c0_2 = context == null ? null : ValidationContext();
    var _constraintp0m0_2 = false;
    try {
      final context = _constraintp0c0_2;
      final _constraintp0v0_2 = ConfigObject.fromJson(
        (_jsonp0 as Map).cast<String, dynamic>(),
      );
      _constraintp0m0_2 = true;
    } on ValidationError {
    } catch (_) {}
    final _constraintp0matches0 = <bool>[
      _constraintp0m0_0,
      _constraintp0m0_1,
      _constraintp0m0_2,
    ];
    final _constraintp0count0 = _constraintp0matches0
        .where((value) => value)
        .length;
    if (_constraintp0count0 != 1) {
      throwValidationError(
        _ptr0,
        'oneOf',
        'Expected exactly one subschema in #/properties/config/oneOf to validate.',
      );
    }
    if (context != null && _constraintp0m0_0 && _constraintp0c0_0 != null) {
      context.mergeFrom(_constraintp0c0_0!);
    }
    if (context != null && _constraintp0m0_1 && _constraintp0c0_1 != null) {
      context.mergeFrom(_constraintp0c0_1!);
    }
    if (context != null && _constraintp0m0_2 && _constraintp0c0_2 != null) {
      context.mergeFrom(_constraintp0c0_2!);
    }
  }
}
