// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/numeric_test/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class TestSchema {
  /// Configuration with multiple variants
  final dynamic config;

  const TestSchema({
    required this.config,
  });

  factory TestSchema.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final config = json['config'];
    remaining.remove('config');
    return TestSchema(
      config: config,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['config'] = config;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
