// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/build_runner_example/lib/schemas/todo_list.json
// Generated by json_schema2dart

export 'todo_list_generated/todo_list.dart';
export 'todo_list_generated/item.dart';
export 'todo_list_generated/metadata_reminder.dart';
export 'todo_list_generated/metadata_reminder_dependency.dart';
export 'todo_list_generated/metadata.dart';
export 'todo_list_generated/metadata_reminder_dependency_channel.dart';
export 'todo_list_generated/validation_error.dart';
