// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

export 'schema_generated/root_schema.dart';
export 'schema_generated/runs_composite_step_env_object_additional_property.dart';
export 'schema_generated/runs_composite_step_env.dart';
export 'schema_generated/runs_composite_step_shell.dart';
export 'schema_generated/runs_javascript.dart';
export 'schema_generated/runs_composite_step_with.dart';
export 'schema_generated/runs_composite_step.dart';
export 'schema_generated/runs_composite.dart';
export 'schema_generated/runs_docker_env_object_additional_property.dart';
export 'schema_generated/runs_docker_env.dart';
export 'schema_generated/runs_composite_step_continue_on_error.dart';
export 'schema_generated/outputs_pattern_property1.dart';
export 'schema_generated/outputs.dart';
export 'schema_generated/outputs_composite_pattern_property1.dart';
export 'schema_generated/outputs_composite.dart';
export 'schema_generated/root_schema_branding.dart';
export 'schema_generated/root_schema_inputs_pattern_property1.dart';
export 'schema_generated/root_schema_inputs.dart';
export 'schema_generated/root_schema_runs.dart';
export 'schema_generated/runs_docker.dart';
export 'schema_generated/runs_javascript_using.dart';
export 'schema_generated/runs_composite_step_shell_variant2.dart';
export 'schema_generated/root_schema_branding_color.dart';
export 'schema_generated/root_schema_branding_icon.dart';
export 'schema_generated/validation_error.dart';
