// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/format_assertions/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class FormatAssertionsExample {
  /// Format: email (format hints disabled).
  ///
  /// Email address as defined by RFC 5321 Mailbox.
  ///
  /// See https://json-schema.org/draft/2020-12/json-schema-validation.html#name-email-addresses.
  final String email;

  /// Format: uri (format hints disabled).
  ///
  /// URI as defined by RFC 3986.
  ///
  /// See https://json-schema.org/draft/2020-12/json-schema-validation.html#name-resource-identifiers.
  final String? website;

  const FormatAssertionsExample({required this.email, this.website});

  factory FormatAssertionsExample.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final email = json['email'] as String;
    remaining.remove('email');
    final website = json['website'] as String?;
    remaining.remove('website');
    return FormatAssertionsExample(email: email, website: website);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['email'] = email;
    if (website != null) map['website'] = website;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
