// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/readonly_writeonly/schema.json
// Generated by json_schema2dart

export 'schema_generated/read_only_write_only_example.dart';
export 'schema_generated/validation_error.dart';
