// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/number_constraints/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// Demonstrates numeric validation keywords
class NumberConstraintsExample {
  /// Must be < 100
  /// Constraints: exclusiveMaximum: 100
  final double? exclusiveMaximum;
  /// Must be > 0
  /// Constraints: exclusiveMinimum: 0
  final double? exclusiveMinimum;
  /// Integer between 1 and 999
  /// Constraints: minimum: 1, maximum: 999
  final int? integerType;
  /// Must be <= 100
  /// Constraints: maximum: 100
  final double? maximum;
  /// Must be >= 0
  /// Constraints: minimum: 0
  final double? minimum;
  /// Must be multiple of 5
  /// Constraints: multipleOf: 5
  final double? multipleOf;

  const NumberConstraintsExample({
    this.exclusiveMaximum,
    this.exclusiveMinimum,
    this.integerType,
    this.maximum,
    this.minimum,
    this.multipleOf,
  });

  factory NumberConstraintsExample.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final exclusiveMaximum = json['exclusiveMaximum'] as double?;
    remaining.remove('exclusiveMaximum');
    final exclusiveMinimum = json['exclusiveMinimum'] as double?;
    remaining.remove('exclusiveMinimum');
    final integerType = json['integerType'] as int?;
    remaining.remove('integerType');
    final maximum = json['maximum'] as double?;
    remaining.remove('maximum');
    final minimum = json['minimum'] as double?;
    remaining.remove('minimum');
    final multipleOf = json['multipleOf'] as double?;
    remaining.remove('multipleOf');
    return NumberConstraintsExample(
      exclusiveMaximum: exclusiveMaximum,
      exclusiveMinimum: exclusiveMinimum,
      integerType: integerType,
      maximum: maximum,
      minimum: minimum,
      multipleOf: multipleOf,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (exclusiveMaximum != null) map['exclusiveMaximum'] = exclusiveMaximum;
    if (exclusiveMinimum != null) map['exclusiveMinimum'] = exclusiveMinimum;
    if (integerType != null) map['integerType'] = integerType;
    if (maximum != null) map['maximum'] = maximum;
    if (minimum != null) map['minimum'] = minimum;
    if (multipleOf != null) map['multipleOf'] = multipleOf;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'exclusiveMaximum');
    final _value0 = exclusiveMaximum;
    if (_value0 != null) {
      context?.markProperty(pointer, 'exclusiveMaximum');
      if (_value0 >= 100) {
        throwValidationError(_ptr0, 'maximum', 'Expected value < 100 but found ' + _value0.toString() + '.');
      }
    }
    final _ptr1 = appendJsonPointer(pointer, 'exclusiveMinimum');
    final _value1 = exclusiveMinimum;
    if (_value1 != null) {
      context?.markProperty(pointer, 'exclusiveMinimum');
      if (_value1 <= 0) {
        throwValidationError(_ptr1, 'minimum', 'Expected value > 0 but found ' + _value1.toString() + '.');
      }
    }
    final _ptr2 = appendJsonPointer(pointer, 'integerType');
    final _value2 = integerType;
    if (_value2 != null) {
      context?.markProperty(pointer, 'integerType');
      if (_value2 < 1) {
        throwValidationError(_ptr2, 'minimum', 'Expected value >= 1 but found ' + _value2.toString() + '.');
      }
      if (_value2 > 999) {
        throwValidationError(_ptr2, 'maximum', 'Expected value <= 999 but found ' + _value2.toString() + '.');
      }
    }
    final _ptr3 = appendJsonPointer(pointer, 'maximum');
    final _value3 = maximum;
    if (_value3 != null) {
      context?.markProperty(pointer, 'maximum');
      if (_value3 > 100) {
        throwValidationError(_ptr3, 'maximum', 'Expected value <= 100 but found ' + _value3.toString() + '.');
      }
    }
    final _ptr4 = appendJsonPointer(pointer, 'minimum');
    final _value4 = minimum;
    if (_value4 != null) {
      context?.markProperty(pointer, 'minimum');
      if (_value4 < 0) {
        throwValidationError(_ptr4, 'minimum', 'Expected value >= 0 but found ' + _value4.toString() + '.');
      }
    }
    final _ptr5 = appendJsonPointer(pointer, 'multipleOf');
    final _value5 = multipleOf;
    if (_value5 != null) {
      context?.markProperty(pointer, 'multipleOf');
    }
  }
}
