// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/allof_example/schema.json
// Generated by json_schema2dart

import 'all_of_example_person.dart';
import 'validation_error.dart';

/// Demonstrates allOf composition
class AllOfExample {
  final AllOfExamplePerson? person;

  const AllOfExample({
    this.person,
  });

  factory AllOfExample.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final person = json['person'] == null ? null : AllOfExamplePerson.fromJson((json['person'] as Map).cast<String, dynamic>());
    remaining.remove('person');
    return AllOfExample(
      person: person,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (person != null) map['person'] = person!.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
