// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/allof_example/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class RootSchemaPerson2 {
  /// Format: email (format hints disabled).
  ///
  /// Email address as defined by RFC 5321 Mailbox.
  ///
  /// See https://json-schema.org/draft/2020-12/json-schema-validation.html#name-email-addresses.
  final String email;
  final String? phone;

  const RootSchemaPerson2({required this.email, this.phone});

  factory RootSchemaPerson2.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final email = json['email'] as String;
    remaining.remove('email');
    final phone = json['phone'] as String?;
    remaining.remove('phone');
    return RootSchemaPerson2(email: email, phone: phone);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['email'] = email;
    if (phone != null) map['phone'] = phone;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
