// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/pattern_properties/schema.json
// Generated by json_schema2dart

export 'schema_generated/pattern_properties_example.dart';
export 'schema_generated/validation_error.dart';
