import 'dart:convert';
import 'dart:io';
import 'package:test/test.dart';
import 'package:schema2dart/src/generator.dart';

void main() {
  group('readOnly and writeOnly support', () {
    late Map<String, dynamic> schema;
    late SchemaGenerator generator;

    setUp(() {
      final schemaJson = File(
        'test/readonly_writeonly/user_schema.json',
      ).readAsStringSync();
      schema = jsonDecode(schemaJson) as Map<String, dynamic>;
      generator = SchemaGenerator(options: const SchemaGeneratorOptions());
    });

    test('should parse readOnly and writeOnly keywords', () {
      final result = generator.generate(schema);

      expect(result, isNotNull);
      expect(result, contains('READ-ONLY'));
      expect(result, contains('WRITE-ONLY'));
    });

    test('should add comments for readOnly properties', () {
      final result = generator.generate(schema);

      // Check for readOnly comment on id field
      expect(
        result,
        contains('/// Unique user identifier generated by the server'),
      );
      expect(
        result,
        contains('/// READ-ONLY: This property is managed by the server'),
      );

      // Check for readOnly on createdAt
      expect(result, contains('/// Timestamp when the user was created'));
      expect(result, contains('READ-ONLY'));
    });

    test('should add comments for writeOnly properties', () {
      final result = generator.generate(schema);

      // Check for writeOnly comment on password field
      expect(
        result,
        contains('/// User password - never returned in responses'),
      );
      expect(
        result,
        contains(
          '/// WRITE-ONLY: This property should not be included in responses',
        ),
      );
    });

    test('should still include readOnly/writeOnly fields in serialization', () {
      final result = generator.generate(schema);

      // Both readOnly and writeOnly fields should be in fromJson
      expect(result, contains("final id = json['id'] as String?;"));
      expect(result, contains("final password = json['password'] as String?;"));

      // Both should be in constructor call
      expect(result, contains("id: id,"));
      expect(result, contains("password: password,"));

      // Both should be in toJson
      expect(result, contains("if (id != null) map['id'] = id;"));
      expect(
        result,
        contains("if (password != null) map['password'] = password;"),
      );
    });

    test('generated code should compile', () {
      final result = generator.generate(schema);
      final outputPath = 'test/readonly_writeonly/generated_user.dart';

      File(outputPath).writeAsStringSync(result);

      // Run dart analyze on the generated file
      final analyzeResult = Process.runSync('dart', ['analyze', outputPath]);

      // Clean up
      File(outputPath).deleteSync();

      expect(
        analyzeResult.exitCode,
        0,
        reason:
            'Generated code should pass dart analyze:\n${analyzeResult.stdout}\n${analyzeResult.stderr}',
      );
    });
  });
}
