// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: lib/schemas/todo_list.json
// Generated by json_schema2dart

import 'metadata_reminder_dependency_channel.dart';
import 'validation_error.dart';

class MetadataReminderDependency {
  final MetadataReminderDependencyChannel? channel;

  const MetadataReminderDependency({
    this.channel,
  });

  factory MetadataReminderDependency.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final channel = json['channel'] == null ? null : MetadataReminderDependencyChannelJson.fromJson(json['channel'] as String);
    remaining.remove('channel');
    return MetadataReminderDependency(
      channel: channel,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (channel != null) map['channel'] = channel!.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
