// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: lib/schemas/todo_list.json
// Generated by json_schema2dart

enum MetadataReminderDependencyChannel { email, sms, push }

extension MetadataReminderDependencyChannelJson on MetadataReminderDependencyChannel {
  String toJson() => const {
        MetadataReminderDependencyChannel.email: 'email',
        MetadataReminderDependencyChannel.sms: 'sms',
        MetadataReminderDependencyChannel.push: 'push',
      }[this]!;

  static MetadataReminderDependencyChannel fromJson(String value) => const {
        'email': MetadataReminderDependencyChannel.email,
        'sms': MetadataReminderDependencyChannel.sms,
        'push': MetadataReminderDependencyChannel.push,
      }[value]!;
}
