// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/nested_refs/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class Address {
  final String city;
  final String? country;
  final String street;

  const Address({
    required this.city,
    this.country,
    required this.street,
  });

  factory Address.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final city = json['city'] as String;
    remaining.remove('city');
    final country = json['country'] as String?;
    remaining.remove('country');
    final street = json['street'] as String;
    remaining.remove('street');
    return Address(
      city: city,
      country: country,
      street: street,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['city'] = city;
    if (country != null) map['country'] = country;
    map['street'] = street;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
