// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/nested_refs/schema.json
// Generated by json_schema2dart

import 'address.dart';
import 'validation_error.dart';

class NestedReferencesExampleManager {
  final Address? address;
  final int? age;
  final String department;
  final String name;

  const NestedReferencesExampleManager({
    this.address,
    this.age,
    required this.department,
    required this.name,
  });

  factory NestedReferencesExampleManager.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final address = json['address'] == null ? null : Address.fromJson((json['address'] as Map).cast<String, dynamic>());
    remaining.remove('address');
    final age = json['age'] as int?;
    remaining.remove('age');
    final department = json['department'] as String;
    remaining.remove('department');
    final name = json['name'] as String;
    remaining.remove('name');
    return NestedReferencesExampleManager(
      address: address,
      age: age,
      department: department,
      name: name,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (address != null) map['address'] = address!.toJson();
    if (age != null) map['age'] = age;
    map['department'] = department;
    map['name'] = name;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
