// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/nested_refs/schema.json
// Generated by json_schema2dart

import 'address.dart';
import 'nested_references_example_manager.dart';
import 'person.dart';
import 'validation_error.dart';

/// Demonstrates $ref usage and nested definitions
class NestedReferencesExample {
  final Person? employee;
  final NestedReferencesExampleManager? manager;
  final List<Address>? offices;

  const NestedReferencesExample({
    this.employee,
    this.manager,
    this.offices,
  });

  factory NestedReferencesExample.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final employee = json['employee'] == null ? null : Person.fromJson((json['employee'] as Map).cast<String, dynamic>());
    remaining.remove('employee');
    final manager = json['manager'] == null ? null : NestedReferencesExampleManager.fromJson((json['manager'] as Map).cast<String, dynamic>());
    remaining.remove('manager');
    final offices = json['offices'] == null ? null : (json['offices'] as List).map((e) => Address.fromJson((e as Map).cast<String, dynamic>())).toList();
    remaining.remove('offices');
    return NestedReferencesExample(
      employee: employee,
      manager: manager,
      offices: offices,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (employee != null) map['employee'] = employee!.toJson();
    if (manager != null) map['manager'] = manager!.toJson();
    if (offices != null) map['offices'] = offices!.map((e) => e.toJson()).toList();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
