// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/nested_refs/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class RootSchemaManager {
  final String department;

  const RootSchemaManager({required this.department});

  factory RootSchemaManager.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final department = json['department'] as String;
    remaining.remove('department');
    return RootSchemaManager(department: department);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['department'] = department;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
