// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

sealed class Configuration {
  const Configuration();

  factory Configuration.fromJson(dynamic json) {
    if (json is String) return ConfigurationString(json);
    if (json is num) return ConfigurationNum(json.toDouble());
    if (json is bool) return ConfigurationBool(json);
    if (json is List) return ConfigurationArray((json as List).map((e) => e).toList());
    if (json is! Map<String, dynamic>) {
      throw ArgumentError('Invalid Configuration value: ${json.runtimeType}');
    }
    final keys = json.keys.toSet();
    final sortedKeys = keys.toList()..sort();
    return ConfigurationObject.fromJson(json);
  }

  dynamic toJson();
}
class ConfigurationString extends Configuration {
  final String value;

  const ConfigurationString(this.value) : super();

  @override
  dynamic toJson() => value;
}
class ConfigurationNum extends Configuration {
  final double value;

  const ConfigurationNum(this.value) : super();

  @override
  dynamic toJson() => value;
}
class ConfigurationBool extends Configuration {
  final bool value;

  const ConfigurationBool(this.value) : super();

  @override
  dynamic toJson() => value;
}
class ConfigurationObject extends Configuration {
  final Map<String, dynamic>? additionalProperties;

  const ConfigurationObject({
    this.additionalProperties,
  }) : super();

  factory ConfigurationObject.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    var unmatched = Map<String, dynamic>.from(remaining);
    Map<String, dynamic>? additionalPropertiesValue;
    if (unmatched.isNotEmpty) {
      final additionalPropertiesMap = <String, dynamic>{};
      for (final entry in unmatched.entries) {
        final value = entry.value;
        additionalPropertiesMap[entry.key] = value;
      }
      additionalPropertiesValue = additionalPropertiesMap.isEmpty ? null : additionalPropertiesMap;
      unmatched = <String, dynamic>{};
    } else {
      additionalPropertiesValue = null;
    }
    return ConfigurationObject(
      additionalProperties: additionalPropertiesValue,
    );
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (additionalProperties != null) {
      additionalProperties!.forEach((key, value) {
        map[key] = value;
      });
    }
    return map;
  }
}
class ConfigurationArray extends Configuration {
  final List<dynamic> value;

  const ConfigurationArray(this.value) : super();

  @override
  dynamic toJson() => value;
}
