// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'container_credentials.dart';
import 'container_env.dart';
import 'container_port.dart';
import 'validation_error.dart';

class Container {
  /// If the image's container registry requires authentication to pull the image, you can use credentials to set a map of the username and password. The credentials are the same values that you would provide to the `docker login` command.
  final ContainerCredentials? credentials;
  /// Sets an array of environment variables in the container.
  final ContainerEnv? env;
  /// The Docker image to use as the container to run the action. The value can be the Docker Hub image name or a registry name.
  final String image;
  /// Additional Docker container resource options. For a list of options, see https://docs.docker.com/engine/reference/commandline/create/#options.
  final String? options;
  /// Sets an array of ports to expose on the container.
  /// Constraints: minItems: 1
  final List<ContainerPort>? ports;
  /// Sets an array of volumes for the container to use. You can use volumes to share data between services or other steps in a job. You can specify named Docker volumes, anonymous Docker volumes, or bind mounts on the host.
  /// To specify a volume, you specify the source and destination path: <source>:<destinationPath>
  /// The <source> is a volume name or an absolute path on the host machine, and <destinationPath> is an absolute path in the container.
  /// Constraints: minItems: 1
  final List<String>? volumes;

  const Container({
    this.credentials,
    this.env,
    required this.image,
    this.options,
    this.ports,
    this.volumes,
  });

  factory Container.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final credentials = json['credentials'] == null ? null : ContainerCredentials.fromJson((json['credentials'] as Map).cast<String, dynamic>());
    remaining.remove('credentials');
    final env = json['env'] == null ? null : ContainerEnv.fromJson((json['env'] as Map).cast<String, dynamic>());
    remaining.remove('env');
    final image = json['image'] as String;
    remaining.remove('image');
    final options = json['options'] as String?;
    remaining.remove('options');
    final ports = json['ports'] == null ? null : (json['ports'] as List).map((e) => ContainerPort.fromJson((e as Map).cast<String, dynamic>())).toList();
    remaining.remove('ports');
    final volumes = json['volumes'] == null ? null : (json['volumes'] as List).map((e) => e as String).toList();
    remaining.remove('volumes');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return Container(
      credentials: credentials,
      env: env,
      image: image,
      options: options,
      ports: ports,
      volumes: volumes,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (credentials != null) map['credentials'] = credentials!.toJson();
    if (env != null) map['env'] = env!.toJson();
    map['image'] = image;
    if (options != null) map['options'] = options;
    if (ports != null) map['ports'] = ports!.map((e) => e.toJson()).toList();
    if (volumes != null) map['volumes'] = volumes;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'credentials');
    final _value0 = credentials;
    if (_value0 != null) {
      context?.markProperty(pointer, 'credentials');
    }
    final _ptr1 = appendJsonPointer(pointer, 'env');
    final _value1 = env;
    if (_value1 != null) {
      context?.markProperty(pointer, 'env');
    }
    final _ptr2 = appendJsonPointer(pointer, 'image');
    final _value2 = image;
    context?.markProperty(pointer, 'image');
    final _ptr3 = appendJsonPointer(pointer, 'options');
    final _value3 = options;
    if (_value3 != null) {
      context?.markProperty(pointer, 'options');
    }
    final _ptr4 = appendJsonPointer(pointer, 'ports');
    final _value4 = ports;
    if (_value4 != null) {
      context?.markProperty(pointer, 'ports');
    }
    final _ptr5 = appendJsonPointer(pointer, 'volumes');
    final _value5 = volumes;
    if (_value5 != null) {
      context?.markProperty(pointer, 'volumes');
    }
  }
}
