// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

sealed class ContainerPort {
  const ContainerPort();

  factory ContainerPort.fromJson(dynamic json) {
    if (json is num) return ContainerPortNum(json);
    if (json is String) return ContainerPortString(json);
    throw ArgumentError('Invalid ContainerPort value type: ${json.runtimeType}');
  }

  dynamic toJson();
}
class ContainerPortNum extends ContainerPort {
  final double value;

  const ContainerPortNum(this.value) : super();

  @override
  dynamic toJson() => value;
}
class ContainerPortString extends ContainerPort {
  final String value;

  const ContainerPortString(this.value) : super();

  @override
  dynamic toJson() => value;
}
