// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

sealed class ContainerEnvObjectAdditionalProperty {
  const ContainerEnvObjectAdditionalProperty();

  factory ContainerEnvObjectAdditionalProperty.fromJson(dynamic json) {
    if (json is String) return ContainerEnvObjectAdditionalPropertyString(json);
    if (json is num) return ContainerEnvObjectAdditionalPropertyNum(json);
    if (json is bool) return ContainerEnvObjectAdditionalPropertyBool(json);
    throw ArgumentError('Invalid ContainerEnvObjectAdditionalProperty value type: ${json.runtimeType}');
  }

  dynamic toJson();
}
class ContainerEnvObjectAdditionalPropertyString extends ContainerEnvObjectAdditionalProperty {
  final String value;

  const ContainerEnvObjectAdditionalPropertyString(this.value) : super();

  @override
  dynamic toJson() => value;
}
class ContainerEnvObjectAdditionalPropertyNum extends ContainerEnvObjectAdditionalProperty {
  final double value;

  const ContainerEnvObjectAdditionalPropertyNum(this.value) : super();

  @override
  dynamic toJson() => value;
}
class ContainerEnvObjectAdditionalPropertyBool extends ContainerEnvObjectAdditionalProperty {
  final bool value;

  const ContainerEnvObjectAdditionalPropertyBool(this.value) : super();

  @override
  dynamic toJson() => value;
}
