// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'defaults_run_shell_string.dart';

/// You can override the default shell settings in the runner's operating system using the shell keyword. You can use built-in shell keywords, or you can define a custom set of shell options.
sealed class DefaultsRunShell {
  const DefaultsRunShell();

  factory DefaultsRunShell.fromJson(dynamic json) {
    if (json is String) return DefaultsRunShellString(json);
    throw ArgumentError('Invalid DefaultsRunShell value type: ${json.runtimeType}');
  }

  dynamic toJson();
}
class DefaultsRunShellValue extends DefaultsRunShell {
  final DefaultsRunShellString value;

  const DefaultsRunShellValue(this.value) : super();

  @override
  dynamic toJson() => value;
}
