// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'shell.dart';
import 'validation_error.dart';

class DefaultsRun {
  final Shell? shell;
  final String? workingDirectory;

  const DefaultsRun({this.shell, this.workingDirectory});

  factory DefaultsRun.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final shell = json['shell'] == null
        ? null
        : Shell.fromJson((json['shell'] as Map).cast<String, dynamic>());
    remaining.remove('shell');
    final workingDirectory = json['working-directory'] as String?;
    remaining.remove('working-directory');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return DefaultsRun(shell: shell, workingDirectory: workingDirectory);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (shell != null) map['shell'] = shell!.toJson();
    if (workingDirectory != null) map['working-directory'] = workingDirectory;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
