// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

enum DefaultsRunShellString { bash, pwsh, python, sh, cmd, powershell }

extension DefaultsRunShellStringJson on DefaultsRunShellString {
  String toJson() => const {
        DefaultsRunShellString.bash: 'bash',
        DefaultsRunShellString.pwsh: 'pwsh',
        DefaultsRunShellString.python: 'python',
        DefaultsRunShellString.sh: 'sh',
        DefaultsRunShellString.cmd: 'cmd',
        DefaultsRunShellString.powershell: 'powershell',
      }[this]!;

  static DefaultsRunShellString fromJson(String value) => const {
        'bash': DefaultsRunShellString.bash,
        'pwsh': DefaultsRunShellString.pwsh,
        'python': DefaultsRunShellString.python,
        'sh': DefaultsRunShellString.sh,
        'cmd': DefaultsRunShellString.cmd,
        'powershell': DefaultsRunShellString.powershell,
      }[value]!;
}
