// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'env_object_additional_property.dart';
import 'validation_error.dart';

/// To set custom environment variables, you need to specify the variables in the workflow file. You can define environment variables for a step, job, or entire workflow using the jobs.<job_id>.steps[*].env, jobs.<job_id>.env, and env keywords. For more information, see https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsenv
sealed class Env {
  const Env();

  void validate({String pointer = '', ValidationContext? context});

  factory Env.fromJson(dynamic json) {
    if (json is String) return EnvString(json);
    if (json is! Map<String, dynamic>) {
      throw ArgumentError('Invalid Env value: ${json.runtimeType}');
    }
    final keys = json.keys.toSet();
    final sortedKeys = keys.toList()..sort();
    return EnvObject.fromJson(json);
  }

  dynamic toJson();
}

class EnvObject extends Env {
  final Map<String, EnvObjectAdditionalProperty>? additionalProperties;

  const EnvObject({this.additionalProperties}) : super();

  factory EnvObject.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    var unmatched = Map<String, dynamic>.from(remaining);
    Map<String, EnvObjectAdditionalProperty>? additionalPropertiesValue;
    if (unmatched.isNotEmpty) {
      final additionalPropertiesMap = <String, EnvObjectAdditionalProperty>{};
      for (final entry in unmatched.entries) {
        final value = entry.value;
        additionalPropertiesMap[entry.key] =
            EnvObjectAdditionalProperty.fromJson(
              (value as Map).cast<String, dynamic>(),
            );
      }
      additionalPropertiesValue = additionalPropertiesMap.isEmpty
          ? null
          : additionalPropertiesMap;
      unmatched = <String, dynamic>{};
    } else {
      additionalPropertiesValue = null;
    }
    return EnvObject(additionalProperties: additionalPropertiesValue);
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (additionalProperties != null) {
      additionalProperties!.forEach((key, value) {
        map[key] = value.toJson();
      });
    }
    return map;
  }

  @override
  void validate({String pointer = '', ValidationContext? context}) {
    final _additionalPropertiesMap = additionalProperties;
    if (_additionalPropertiesMap != null) {
      _additionalPropertiesMap.forEach((key, value) {
        final itemPointer = appendJsonPointer(pointer, key);
        context?.markProperty(pointer, key);
        final _jsonadditionalProperties = value.toJson();
        final _constraintadditionalPropertiesc0_0 = context == null
            ? null
            : ValidationContext();
        var _constraintadditionalPropertiesm0_0 = false;
        try {
          final context = _constraintadditionalPropertiesc0_0;
          final _constraintadditionalPropertiesv0_0 =
              _jsonadditionalProperties as String;
          _constraintadditionalPropertiesm0_0 = true;
        } on ValidationError {
        } catch (_) {}
        final _constraintadditionalPropertiesc0_1 = context == null
            ? null
            : ValidationContext();
        var _constraintadditionalPropertiesm0_1 = false;
        try {
          final context = _constraintadditionalPropertiesc0_1;
          final _constraintadditionalPropertiesv0_1 =
              _jsonadditionalProperties as double;
          _constraintadditionalPropertiesm0_1 = true;
        } on ValidationError {
        } catch (_) {}
        final _constraintadditionalPropertiesc0_2 = context == null
            ? null
            : ValidationContext();
        var _constraintadditionalPropertiesm0_2 = false;
        try {
          final context = _constraintadditionalPropertiesc0_2;
          final _constraintadditionalPropertiesv0_2 =
              _jsonadditionalProperties as bool;
          _constraintadditionalPropertiesm0_2 = true;
        } on ValidationError {
        } catch (_) {}
        final _constraintadditionalPropertiesmatches0 = <bool>[
          _constraintadditionalPropertiesm0_0,
          _constraintadditionalPropertiesm0_1,
          _constraintadditionalPropertiesm0_2,
        ];
        final _constraintadditionalPropertiescount0 =
            _constraintadditionalPropertiesmatches0
                .where((value) => value)
                .length;
        if (_constraintadditionalPropertiescount0 != 1) {
          throwValidationError(
            itemPointer,
            'oneOf',
            'Expected exactly one subschema in #/definitions/env/oneOf/0/additionalProperties/oneOf to validate.',
          );
        }
        if (context != null &&
            _constraintadditionalPropertiesm0_0 &&
            _constraintadditionalPropertiesc0_0 != null) {
          context.mergeFrom(_constraintadditionalPropertiesc0_0!);
        }
        if (context != null &&
            _constraintadditionalPropertiesm0_1 &&
            _constraintadditionalPropertiesc0_1 != null) {
          context.mergeFrom(_constraintadditionalPropertiesc0_1!);
        }
        if (context != null &&
            _constraintadditionalPropertiesm0_2 &&
            _constraintadditionalPropertiesc0_2 != null) {
          context.mergeFrom(_constraintadditionalPropertiesc0_2!);
        }
      });
    }
  }
}

class EnvString extends Env {
  final String value;

  const EnvString(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
