// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'env_object_additional_property.dart';

/// To set custom environment variables, you need to specify the variables in the workflow file. You can define environment variables for a step, job, or entire workflow using the jobs.<job_id>.steps[*].env, jobs.<job_id>.env, and env keywords. For more information, see https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsenv
sealed class Env {
  const Env();

  factory Env.fromJson(dynamic json) {
    if (json is String) return EnvString(json);
    if (json is! Map<String, dynamic>) {
      throw ArgumentError('Invalid Env value: ${json.runtimeType}');
    }
    final keys = json.keys.toSet();
    final sortedKeys = keys.toList()..sort();
    return EnvObject.fromJson(json);
  }

  dynamic toJson();
}
class EnvObject extends Env {
  final Map<String, EnvObjectAdditionalProperty>? additionalProperties;

  const EnvObject({
    this.additionalProperties,
  }) : super();

  factory EnvObject.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    var unmatched = Map<String, dynamic>.from(remaining);
    Map<String, EnvObjectAdditionalProperty>? additionalPropertiesValue;
    if (unmatched.isNotEmpty) {
      final additionalPropertiesMap = <String, EnvObjectAdditionalProperty>{};
      for (final entry in unmatched.entries) {
        final value = entry.value;
        additionalPropertiesMap[entry.key] = EnvObjectAdditionalProperty.fromJson((value as Map).cast<String, dynamic>());
      }
      additionalPropertiesValue = additionalPropertiesMap.isEmpty ? null : additionalPropertiesMap;
      unmatched = <String, dynamic>{};
    } else {
      additionalPropertiesValue = null;
    }
    return EnvObject(
      additionalProperties: additionalPropertiesValue,
    );
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (additionalProperties != null) {
      additionalProperties!.forEach((key, value) {
        map[key] = value.toJson();
      });
    }
    return map;
  }
}
class EnvString extends Env {
  final String value;

  const EnvString(this.value) : super();

  @override
  dynamic toJson() => value;
}
