// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

sealed class EnvObjectAdditionalProperty {
  const EnvObjectAdditionalProperty();

  factory EnvObjectAdditionalProperty.fromJson(dynamic json) {
    if (json is String) return EnvObjectAdditionalPropertyString(json);
    if (json is num) return EnvObjectAdditionalPropertyNum(json.toDouble());
    if (json is bool) return EnvObjectAdditionalPropertyBool(json);
    throw ArgumentError('Invalid EnvObjectAdditionalProperty value type: ${json.runtimeType}');
  }

  dynamic toJson();
}
class EnvObjectAdditionalPropertyString extends EnvObjectAdditionalProperty {
  final String value;

  const EnvObjectAdditionalPropertyString(this.value) : super();

  @override
  dynamic toJson() => value;
}
class EnvObjectAdditionalPropertyNum extends EnvObjectAdditionalProperty {
  final double value;

  const EnvObjectAdditionalPropertyNum(this.value) : super();

  @override
  dynamic toJson() => value;
}
class EnvObjectAdditionalPropertyBool extends EnvObjectAdditionalProperty {
  final bool value;

  const EnvObjectAdditionalPropertyBool(this.value) : super();

  @override
  dynamic toJson() => value;
}
