// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class EventObjectObject {

  const EventObjectObject();

  factory EventObjectObject.fromJson(Map<String, dynamic> json) {
    return EventObjectObject(
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
