// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class GithubWorkflowOnObjectScheduleItem {
  final String? cron;

  const GithubWorkflowOnObjectScheduleItem({
    this.cron,
  });

  factory GithubWorkflowOnObjectScheduleItem.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final cron = json['cron'] as String?;
    remaining.remove('cron');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return GithubWorkflowOnObjectScheduleItem(
      cron: cron,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (cron != null) map['cron'] = cron;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
