// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

/// Required if input is defined for the on.workflow_call keyword. The value of this parameter is a string specifying the data type of the input. This must be one of: boolean, number, or string.
enum GithubWorkflowOnObjectWorkflowCallInputsPatternProperty1Type { boolean, number, string }

extension GithubWorkflowOnObjectWorkflowCallInputsPatternProperty1TypeJson on GithubWorkflowOnObjectWorkflowCallInputsPatternProperty1Type {
  String toJson() => const {
        GithubWorkflowOnObjectWorkflowCallInputsPatternProperty1Type.boolean: 'boolean',
        GithubWorkflowOnObjectWorkflowCallInputsPatternProperty1Type.number: 'number',
        GithubWorkflowOnObjectWorkflowCallInputsPatternProperty1Type.string: 'string',
      }[this]!;

  static GithubWorkflowOnObjectWorkflowCallInputsPatternProperty1Type fromJson(String value) => const {
        'boolean': GithubWorkflowOnObjectWorkflowCallInputsPatternProperty1Type.boolean,
        'number': GithubWorkflowOnObjectWorkflowCallInputsPatternProperty1Type.number,
        'string': GithubWorkflowOnObjectWorkflowCallInputsPatternProperty1Type.string,
      }[value]!;
}
