// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'github_workflow_on_object_workflow_dispatch_inputs.dart';

/// You can now create workflows that are manually triggered with the new workflow_dispatch event. You will then see a 'Run workflow' button on the Actions tab, enabling you to easily trigger a run.
class GithubWorkflowOnObjectWorkflowDispatch {
  /// Input parameters allow you to specify data that the action expects to use during runtime. GitHub stores input parameters as environment variables. Input ids with uppercase letters are converted to lowercase during runtime. We recommended using lowercase input ids.
  final GithubWorkflowOnObjectWorkflowDispatchInputs? inputs;

  const GithubWorkflowOnObjectWorkflowDispatch({
    this.inputs,
  });

  factory GithubWorkflowOnObjectWorkflowDispatch.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final inputs = json['inputs'] == null ? null : GithubWorkflowOnObjectWorkflowDispatchInputs.fromJson((json['inputs'] as Map).cast<String, dynamic>());
    remaining.remove('inputs');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return GithubWorkflowOnObjectWorkflowDispatch(
      inputs: inputs,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (inputs != null) map['inputs'] = inputs!.toJson();
    return map;
  }
}
