// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'github_workflow_on_object_workflow_call_secrets_pattern_property1.dart';

/// A map of the secrets that can be used in the called workflow. Within the called workflow, you can use the secrets context to refer to a secret.
class GithubWorkflowOnObjectWorkflowCallSecrets {
  final Map<String, GithubWorkflowOnObjectWorkflowCallSecretsPatternProperty1>? patternProperties;

  const GithubWorkflowOnObjectWorkflowCallSecrets({
    this.patternProperties,
  });

  factory GithubWorkflowOnObjectWorkflowCallSecrets.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    var unmatched = Map<String, dynamic>.from(remaining);
    Map<String, GithubWorkflowOnObjectWorkflowCallSecretsPatternProperty1>? patternPropertiesValue;
    {
      final patternPropertiesMap = <String, GithubWorkflowOnObjectWorkflowCallSecretsPatternProperty1>{};
      final unmatchedAfterPattern = <String, dynamic>{};
      for (final entry in unmatched.entries) {
        final key = entry.key;
        final value = entry.value;
        var matched = false;
        if (!matched && RegExp('^[_a-zA-Z][a-zA-Z0-9_-]*\$').hasMatch(key)) {
          patternPropertiesMap[key] = GithubWorkflowOnObjectWorkflowCallSecretsPatternProperty1.fromJson((value as Map).cast<String, dynamic>());
          matched = true;
        }
        if (!matched) {
          unmatchedAfterPattern[key] = value;
        }
      }
      patternPropertiesValue = patternPropertiesMap.isEmpty ? null : patternPropertiesMap;
      unmatched = unmatchedAfterPattern;
    }
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return GithubWorkflowOnObjectWorkflowCallSecrets(
      patternProperties: patternPropertiesValue,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (patternProperties != null) {
      for (final entry in patternProperties!.entries) {
        final key = entry.key;
        final value = entry.value;
        var matched = false;
        if (!matched && RegExp('^[_a-zA-Z][a-zA-Z0-9_-]*\$').hasMatch(key)) {
          map[key] = value.toJson();
          matched = true;
        }
        if (!matched) {
          map[key] = value;
        }
      }
    }
    return map;
  }
}
