// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'github_workflow_on_object_workflow_call_inputs.dart';
import 'github_workflow_on_object_workflow_call_outputs.dart';
import 'github_workflow_on_object_workflow_call_secrets.dart';
import 'validation_error.dart';

/// Allows workflows to be reused by other workflows.
class GithubWorkflowOnObjectWorkflowCall {
  /// When using the workflow_call keyword, you can optionally specify inputs that are passed to the called workflow from the caller workflow.
  final GithubWorkflowOnObjectWorkflowCallInputs? inputs;
  /// When using the workflow_call keyword, you can optionally specify inputs that are passed to the called workflow from the caller workflow.
  final GithubWorkflowOnObjectWorkflowCallOutputs? outputs;
  /// A map of the secrets that can be used in the called workflow. Within the called workflow, you can use the secrets context to refer to a secret.
  final GithubWorkflowOnObjectWorkflowCallSecrets? secrets;

  const GithubWorkflowOnObjectWorkflowCall({
    this.inputs,
    this.outputs,
    this.secrets,
  });

  factory GithubWorkflowOnObjectWorkflowCall.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final inputs = json['inputs'] == null ? null : GithubWorkflowOnObjectWorkflowCallInputs.fromJson((json['inputs'] as Map).cast<String, dynamic>());
    remaining.remove('inputs');
    final outputs = json['outputs'] == null ? null : GithubWorkflowOnObjectWorkflowCallOutputs.fromJson((json['outputs'] as Map).cast<String, dynamic>());
    remaining.remove('outputs');
    final secrets = json['secrets'] == null ? null : GithubWorkflowOnObjectWorkflowCallSecrets.fromJson((json['secrets'] as Map).cast<String, dynamic>());
    remaining.remove('secrets');
    return GithubWorkflowOnObjectWorkflowCall(
      inputs: inputs,
      outputs: outputs,
      secrets: secrets,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (inputs != null) map['inputs'] = inputs!.toJson();
    if (outputs != null) map['outputs'] = outputs!.toJson();
    if (secrets != null) map['secrets'] = secrets!.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
