// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'matrix_object_pattern_property1_array_item.dart';

sealed class MatrixObjectPatternProperty1 {
  const MatrixObjectPatternProperty1();

  factory MatrixObjectPatternProperty1.fromJson(dynamic json) {
    if (json is String) return MatrixObjectPatternProperty1String(json);
    if (json is List) return MatrixObjectPatternProperty1Array((json as List).map((e) => MatrixObjectPatternProperty1ArrayItem.fromJson((e as Map).cast<String, dynamic>())).toList());
    throw ArgumentError('Invalid MatrixObjectPatternProperty1 value type: ${json.runtimeType}');
  }

  dynamic toJson();
}
class MatrixObjectPatternProperty1String extends MatrixObjectPatternProperty1 {
  final String value;

  const MatrixObjectPatternProperty1String(this.value) : super();

  @override
  dynamic toJson() => value;
}
class MatrixObjectPatternProperty1Array extends MatrixObjectPatternProperty1 {
  final List<MatrixObjectPatternProperty1ArrayItem> value;

  const MatrixObjectPatternProperty1Array(this.value) : super();

  @override
  dynamic toJson() => value.map((e) => e.toJson()).toList();
}
