// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'configuration.dart';

sealed class MatrixObjectAdditionalProperty {
  const MatrixObjectAdditionalProperty();

  factory MatrixObjectAdditionalProperty.fromJson(dynamic json) {
    if (json is String) return MatrixObjectAdditionalPropertyString(json);
    throw ArgumentError('Invalid MatrixObjectAdditionalProperty value type: ${json.runtimeType}');
  }

  dynamic toJson();
}
class MatrixObjectAdditionalPropertyArray extends MatrixObjectAdditionalProperty {
  final List<Configuration> value;

  const MatrixObjectAdditionalPropertyArray(this.value) : super();

  @override
  dynamic toJson() => value;
}
class MatrixObjectAdditionalPropertyString extends MatrixObjectAdditionalProperty {
  final String value;

  const MatrixObjectAdditionalPropertyString(this.value) : super();

  @override
  dynamic toJson() => value;
}
