// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'configuration.dart';
import 'validation_error.dart';

class MatrixObjectPatternProperty1ArrayItem {
  final Map<String, Configuration>? additionalProperties;

  const MatrixObjectPatternProperty1ArrayItem({
    this.additionalProperties,
  });

  factory MatrixObjectPatternProperty1ArrayItem.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    var unmatched = Map<String, dynamic>.from(remaining);
    Map<String, Configuration>? additionalPropertiesValue;
    if (unmatched.isNotEmpty) {
      final additionalPropertiesMap = <String, Configuration>{};
      for (final entry in unmatched.entries) {
        final value = entry.value;
        additionalPropertiesMap[entry.key] = Configuration.fromJson((value as Map).cast<String, dynamic>());
      }
      additionalPropertiesValue = additionalPropertiesMap.isEmpty ? null : additionalPropertiesMap;
      unmatched = <String, dynamic>{};
    } else {
      additionalPropertiesValue = null;
    }
    return MatrixObjectPatternProperty1ArrayItem(
      additionalProperties: additionalPropertiesValue,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (additionalProperties != null) {
      additionalProperties!.forEach((key, value) {
        map[key] = value.toJson();
      });
    }
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
