// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'configuration.dart';
import 'validation_error.dart';

sealed class MatrixObjectAdditionalProperty {
  const MatrixObjectAdditionalProperty();

  void validate({String pointer = '', ValidationContext? context});

  factory MatrixObjectAdditionalProperty.fromJson(dynamic json) {
    if (json is List)
      return MatrixObjectAdditionalPropertyArray(
        (json as List)
            .map(
              (e) => Configuration.fromJson((e as Map).cast<String, dynamic>()),
            )
            .toList(),
      );
    if (json is String) return MatrixObjectAdditionalPropertyString(json);
    throw ArgumentError(
      'Invalid MatrixObjectAdditionalProperty value type: ${json.runtimeType}',
    );
  }

  dynamic toJson();
}

class MatrixObjectAdditionalPropertyArray
    extends MatrixObjectAdditionalProperty {
  final List<Configuration> value;

  const MatrixObjectAdditionalPropertyArray(this.value) : super();

  @override
  dynamic toJson() => value.map((e) => e.toJson()).toList();

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class MatrixObjectAdditionalPropertyString
    extends MatrixObjectAdditionalProperty {
  final String value;

  const MatrixObjectAdditionalPropertyString(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
