// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'normal_job_runs_on_object_labels.dart';
import 'validation_error.dart';

/// The type of machine to run the job on. The machine can be either a GitHub-hosted runner, or a self-hosted runner.
sealed class NormalJobRunsOn {
  const NormalJobRunsOn();

  void validate({String pointer = '', ValidationContext? context});

  factory NormalJobRunsOn.fromJson(dynamic json) {
    if (json is String) return NormalJobRunsOnString(json);
    if (json is String) return NormalJobRunsOnString2(json);
    if (json is String) return NormalJobRunsOnString3(json);
    if (json is! Map<String, dynamic>) {
      throw ArgumentError('Invalid NormalJobRunsOn value: ${json.runtimeType}');
    }
    final keys = json.keys.toSet();
    final sortedKeys = keys.toList()..sort();
    return NormalJobRunsOnObject.fromJson(json);
  }

  dynamic toJson();
}

class NormalJobRunsOnString extends NormalJobRunsOn {
  final String value;

  const NormalJobRunsOnString(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class NormalJobRunsOnValue extends NormalJobRunsOn {
  final dynamic value;

  const NormalJobRunsOnValue(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class NormalJobRunsOnObject extends NormalJobRunsOn {
  final String? group;
  final NormalJobRunsOnObjectLabels? labels;

  const NormalJobRunsOnObject({this.group, this.labels}) : super();

  factory NormalJobRunsOnObject.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final group = json['group'] as String?;
    remaining.remove('group');
    final labels = json['labels'] == null
        ? null
        : NormalJobRunsOnObjectLabels.fromJson(
            (json['labels'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('labels');
    return NormalJobRunsOnObject(group: group, labels: labels);
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (group != null) map['group'] = group;
    if (labels != null) map['labels'] = labels!.toJson();
    return map;
  }

  @override
  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'group');
    final _value0 = group;
    if (_value0 != null) {
      context?.markProperty(pointer, 'group');
    }
    final _ptr1 = appendJsonPointer(pointer, 'labels');
    final _value1 = labels;
    if (_value1 != null) {
      context?.markProperty(pointer, 'labels');
      final _jsonp1 = _value1.toJson();
      final _constraintp1c0_0 = context == null ? null : ValidationContext();
      var _constraintp1m0_0 = false;
      try {
        final context = _constraintp1c0_0;
        final _constraintp1v0_0 = _jsonp1 as String;
        _constraintp1m0_0 = true;
      } on ValidationError {
      } catch (_) {}
      final _constraintp1c0_1 = context == null ? null : ValidationContext();
      var _constraintp1m0_1 = false;
      try {
        final context = _constraintp1c0_1;
        final _constraintp1v0_1 = (_jsonp1 as List)
            .map((e) => e as String)
            .toList();
        _constraintp1m0_1 = true;
      } on ValidationError {
      } catch (_) {}
      final _constraintp1matches0 = <bool>[
        _constraintp1m0_0,
        _constraintp1m0_1,
      ];
      final _constraintp1count0 = _constraintp1matches0
          .where((value) => value)
          .length;
      if (_constraintp1count0 != 1) {
        throwValidationError(
          _ptr1,
          'oneOf',
          'Expected exactly one subschema in #/definitions/normalJob/properties/runs-on/anyOf/2/properties/labels/oneOf to validate.',
        );
      }
      if (context != null && _constraintp1m0_0 && _constraintp1c0_0 != null) {
        context.mergeFrom(_constraintp1c0_0!);
      }
      if (context != null && _constraintp1m0_1 && _constraintp1c0_1 != null) {
        context.mergeFrom(_constraintp1c0_1!);
      }
    }
  }
}

class NormalJobRunsOnString2 extends NormalJobRunsOn {
  final String value;

  const NormalJobRunsOnString2(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class NormalJobRunsOnString3 extends NormalJobRunsOn {
  final String value;

  const NormalJobRunsOnString3(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
