// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// The maximum number of jobs that can run simultaneously when using a matrix job strategy. By default, GitHub will maximize the number of jobs run in parallel depending on the available runners on GitHub-hosted virtual machines.
sealed class NormalJobStrategyMaxParallel {
  const NormalJobStrategyMaxParallel();

  void validate({String pointer = '', ValidationContext? context});

  factory NormalJobStrategyMaxParallel.fromJson(dynamic json) {
    if (json is num) return NormalJobStrategyMaxParallelNum(json.toDouble());
    if (json is String) return NormalJobStrategyMaxParallelString(json);
    throw ArgumentError(
      'Invalid NormalJobStrategyMaxParallel value type: ${json.runtimeType}',
    );
  }

  dynamic toJson();
}

class NormalJobStrategyMaxParallelNum extends NormalJobStrategyMaxParallel {
  final double value;

  const NormalJobStrategyMaxParallelNum(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class NormalJobStrategyMaxParallelString extends NormalJobStrategyMaxParallel {
  final String value;

  const NormalJobStrategyMaxParallelString(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
