// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

sealed class NormalJobRunsOnObjectLabels {
  const NormalJobRunsOnObjectLabels();

  void validate({String pointer = '', ValidationContext? context});

  factory NormalJobRunsOnObjectLabels.fromJson(dynamic json) {
    if (json is String) return NormalJobRunsOnObjectLabelsString(json);
    if (json is List)
      return NormalJobRunsOnObjectLabelsArray(
        (json as List).map((e) => e as String).toList(),
      );
    throw ArgumentError(
      'Invalid NormalJobRunsOnObjectLabels value type: ${json.runtimeType}',
    );
  }

  dynamic toJson();
}

class NormalJobRunsOnObjectLabelsString extends NormalJobRunsOnObjectLabels {
  final String value;

  const NormalJobRunsOnObjectLabelsString(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class NormalJobRunsOnObjectLabelsArray extends NormalJobRunsOnObjectLabels {
  final List<String> value;

  const NormalJobRunsOnObjectLabelsArray(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
