// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'normal_job_runs_on_object_labels.dart';
import 'validation_error.dart';

/// The type of machine to run the job on. The machine can be either a GitHub-hosted runner, or a self-hosted runner.
sealed class NormalJobRunsOn {
  const NormalJobRunsOn();

  void validate({String pointer = '', ValidationContext? context});

  factory NormalJobRunsOn.fromJson(dynamic json) {
    if (json is String) return NormalJobRunsOnString(json);
    if (json is String) return NormalJobRunsOnString2(json);
    if (json is String) return NormalJobRunsOnString3(json);
    if (json is! Map<String, dynamic>) {
      throw ArgumentError('Invalid NormalJobRunsOn value: ${json.runtimeType}');
    }
    final keys = json.keys.toSet();
    final sortedKeys = keys.toList()..sort();
    return NormalJobRunsOnObject.fromJson(json);
  }

  dynamic toJson();
}
class NormalJobRunsOnString extends NormalJobRunsOn {
  final String value;

  const NormalJobRunsOnString(this.value) : super();

  @override
  dynamic toJson() => value;
}
class NormalJobRunsOnValue extends NormalJobRunsOn {
  final dynamic value;

  const NormalJobRunsOnValue(this.value) : super();

  @override
  dynamic toJson() => value;
}
class NormalJobRunsOnObject extends NormalJobRunsOn {
  final String? group;
  final NormalJobRunsOnObjectLabels? labels;

  const NormalJobRunsOnObject({
    this.group,
    this.labels,
  }) : super();

  factory NormalJobRunsOnObject.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final group = json['group'] as String?;
    remaining.remove('group');
    final labels = json['labels'] == null ? null : NormalJobRunsOnObjectLabels.fromJson((json['labels'] as Map).cast<String, dynamic>());
    remaining.remove('labels');
    return NormalJobRunsOnObject(
      group: group,
      labels: labels,
    );
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (group != null) map['group'] = group;
    if (labels != null) map['labels'] = labels!.toJson();
    return map;
  }

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
class NormalJobRunsOnString2 extends NormalJobRunsOn {
  final String value;

  const NormalJobRunsOnString2(this.value) : super();

  @override
  dynamic toJson() => value;
}
class NormalJobRunsOnString3 extends NormalJobRunsOn {
  final String value;

  const NormalJobRunsOnString3(this.value) : super();

  @override
  dynamic toJson() => value;
}
