// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// You can use the if conditional to prevent a job from running unless a condition is met. You can use any supported context and expression to create a conditional.
/// Expressions in an if conditional do not require the ${{ }} syntax. For more information, see https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions.
sealed class NormalJobIf {
  const NormalJobIf();

  void validate({String pointer = '', ValidationContext? context});

  factory NormalJobIf.fromJson(dynamic json) {
    if (json is bool) return NormalJobIfBool(json);
    if (json is num) return NormalJobIfNum(json.toDouble());
    if (json is String) return NormalJobIfString(json);
    throw ArgumentError('Invalid NormalJobIf value type: ${json.runtimeType}');
  }

  dynamic toJson();
}

class NormalJobIfBool extends NormalJobIf {
  final bool value;

  const NormalJobIfBool(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class NormalJobIfNum extends NormalJobIf {
  final double value;

  const NormalJobIfNum(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class NormalJobIfString extends NormalJobIf {
  final String value;

  const NormalJobIfString(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
