// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// Prevents a workflow run from failing when a job fails. Set to true to allow a workflow run to pass when this job fails.
sealed class NormalJobContinueOnError {
  const NormalJobContinueOnError();

  void validate({String pointer = '', ValidationContext? context});

  factory NormalJobContinueOnError.fromJson(dynamic json) {
    if (json is bool) return NormalJobContinueOnErrorBool(json);
    if (json is String) return NormalJobContinueOnErrorString(json);
    throw ArgumentError(
      'Invalid NormalJobContinueOnError value type: ${json.runtimeType}',
    );
  }

  dynamic toJson();
}

class NormalJobContinueOnErrorBool extends NormalJobContinueOnError {
  final bool value;

  const NormalJobContinueOnErrorBool(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class NormalJobContinueOnErrorString extends NormalJobContinueOnError {
  final String value;

  const NormalJobContinueOnErrorString(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
