// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// When set to true, GitHub cancels all in-progress jobs if any matrix job fails. Default: true
sealed class NormalJobStrategyFailFast {
  const NormalJobStrategyFailFast();

  void validate({String pointer = '', ValidationContext? context});

  factory NormalJobStrategyFailFast.fromJson(dynamic json) {
    if (json is bool) return NormalJobStrategyFailFastBool(json);
    if (json is String) return NormalJobStrategyFailFastString(json);
    throw ArgumentError(
      'Invalid NormalJobStrategyFailFast value type: ${json.runtimeType}',
    );
  }

  dynamic toJson();
}

class NormalJobStrategyFailFastBool extends NormalJobStrategyFailFast {
  final bool value;

  const NormalJobStrategyFailFastBool(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class NormalJobStrategyFailFastString extends NormalJobStrategyFailFast {
  final String value;

  const NormalJobStrategyFailFastString(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
