// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

sealed class NormalJobRunsOnObjectLabels {
  const NormalJobRunsOnObjectLabels();

  factory NormalJobRunsOnObjectLabels.fromJson(dynamic json) {
    if (json is String) return NormalJobRunsOnObjectLabelsString(json);
    throw ArgumentError('Invalid NormalJobRunsOnObjectLabels value type: ${json.runtimeType}');
  }

  dynamic toJson();
}
class NormalJobRunsOnObjectLabelsString extends NormalJobRunsOnObjectLabels {
  final String value;

  const NormalJobRunsOnObjectLabelsString(this.value) : super();

  @override
  dynamic toJson() => value;
}
class NormalJobRunsOnObjectLabelsArray extends NormalJobRunsOnObjectLabels {
  final List<String> value;

  const NormalJobRunsOnObjectLabelsArray(this.value) : super();

  @override
  dynamic toJson() => value;
}
