// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

/// The maximum number of minutes to let a workflow run before GitHub automatically cancels it. Default: 360
sealed class NormalJobTimeoutMinutes {
  const NormalJobTimeoutMinutes();

  factory NormalJobTimeoutMinutes.fromJson(dynamic json) {
    if (json is num) return NormalJobTimeoutMinutesNum(json.toDouble());
    if (json is String) return NormalJobTimeoutMinutesString(json);
    throw ArgumentError('Invalid NormalJobTimeoutMinutes value type: ${json.runtimeType}');
  }

  dynamic toJson();
}
class NormalJobTimeoutMinutesNum extends NormalJobTimeoutMinutes {
  final double value;

  const NormalJobTimeoutMinutesNum(this.value) : super();

  @override
  dynamic toJson() => value;
}
class NormalJobTimeoutMinutesString extends NormalJobTimeoutMinutes {
  final String value;

  const NormalJobTimeoutMinutesString(this.value) : super();

  @override
  dynamic toJson() => value;
}
