// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

/// The environment that the job references.
sealed class NormalJobEnvironment {
  const NormalJobEnvironment();

  factory NormalJobEnvironment.fromJson(dynamic json) {
    if (json is String) return NormalJobEnvironmentString(json);
    if (json is! Map<String, dynamic>) {
      throw ArgumentError('Invalid NormalJobEnvironment value: ${json.runtimeType}');
    }
    final keys = json.keys.toSet();
    final sortedKeys = keys.toList()..sort();
    final requiredMatches = <NormalJobEnvironment Function(Map<String, dynamic>)>[];
    final requiredMatchNames = <String>[];
    if (keys.contains('name')) {
      requiredMatches.add(Environment.fromJson);
      requiredMatchNames.add('Environment');
    }
    if (requiredMatches.length == 1) {
      return requiredMatches.single(json);
    }
    if (requiredMatches.length > 1) {
      throw ArgumentError('Ambiguous NormalJobEnvironment variant matched required-property heuristics: ${requiredMatchNames.join(', ')}');
    }
    return Environment.fromJson(json);
  }

  dynamic toJson();
}
class NormalJobEnvironmentString extends NormalJobEnvironment {
  final String value;

  const NormalJobEnvironmentString(this.value) : super();

  @override
  dynamic toJson() => value;
}
/// The environment that the job references
class Environment extends NormalJobEnvironment {
  /// The name of the environment configured in the repo.
  final String name;
  /// A deployment URL
  final String? url;

  const Environment({
    required this.name,
    this.url,
  }) : super();

  factory Environment.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final name = json['name'] as String;
    remaining.remove('name');
    final url = json['url'] as String?;
    remaining.remove('url');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return Environment(
      name: name,
      url: url,
    );
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = name;
    if (url != null) map['url'] = url;
    return map;
  }
}
