// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'event.dart';
import 'event_object_object.dart';
import 'on_object_schedule_item.dart';
import 'on_object_workflow_call.dart';
import 'on_object_workflow_dispatch.dart';
import 'root_schema_on_pull_request.dart';
import 'root_schema_on_pull_request2.dart';
import 'root_schema_on_pull_request_not.dart';
import 'root_schema_on_pull_request_not2.dart';
import 'root_schema_on_pull_request_not3.dart';
import 'root_schema_on_pull_request_target.dart';
import 'root_schema_on_pull_request_target2.dart';
import 'root_schema_on_pull_request_target_not.dart';
import 'root_schema_on_pull_request_target_not2.dart';
import 'root_schema_on_pull_request_target_not3.dart';
import 'root_schema_on_push.dart';
import 'root_schema_on_push2.dart';
import 'root_schema_on_push_not.dart';
import 'root_schema_on_push_not2.dart';
import 'root_schema_on_push_not3.dart';
import 'validation_error.dart';

/// The name of the GitHub event that triggers the workflow. You can provide a single event string, array of events, array of event types, or an event configuration map that schedules a workflow or restricts the execution of a workflow to specific files, tags, or branch changes. For a list of available events, see https://help.github.com/en/github/automating-your-workflow-with-github-actions/events-that-trigger-workflows.
sealed class On {
  const On();

  void validate({String pointer = '', ValidationContext? context});

  factory On.fromJson(dynamic json) {
    if (json is String) return OnValue(EventJson.fromJson(json));
    if (json is List)
      return OnArray(
        (json as List).map((e) => EventJson.fromJson(e as String)).toList(),
      );
    if (json is! Map<String, dynamic>) {
      throw ArgumentError('Invalid On value: ${json.runtimeType}');
    }
    final keys = json.keys.toSet();
    final sortedKeys = keys.toList()..sort();
    return OnObject.fromJson(json);
  }

  dynamic toJson();
}

class OnValue extends On {
  final Event value;

  const OnValue(this.value) : super();

  @override
  dynamic toJson() => value.toJson();

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class OnArray extends On {
  final List<Event> value;

  const OnArray(this.value) : super();

  @override
  dynamic toJson() => value.map((e) => e.toJson()).toList();

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class OnObject extends On {
  /// Runs your workflow anytime the branch_protection_rule event occurs. More than one activity type triggers this event.
  final EventObjectObject? branchProtectionRule;

  /// Runs your workflow anytime the check_run event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/checks/runs.
  final EventObjectObject? checkRun;

  /// Runs your workflow anytime the check_suite event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/checks/suites/.
  final EventObjectObject? checkSuite;

  /// Runs your workflow anytime someone creates a branch or tag, which triggers the create event. For information about the REST API, see https://developer.github.com/v3/git/refs/#create-a-reference.
  final EventObjectObject? create;

  /// Runs your workflow anytime someone deletes a branch or tag, which triggers the delete event. For information about the REST API, see https://developer.github.com/v3/git/refs/#delete-a-reference.
  final EventObjectObject? delete;

  /// Runs your workflow anytime someone creates a deployment, which triggers the deployment event. Deployments created with a commit SHA may not have a Git ref. For information about the REST API, see https://developer.github.com/v3/repos/deployments/.
  final EventObjectObject? deployment;

  /// Runs your workflow anytime a third party provides a deployment status, which triggers the deployment_status event. Deployments created with a commit SHA may not have a Git ref. For information about the REST API, see https://developer.github.com/v3/repos/deployments/#create-a-deployment-status.
  final EventObjectObject? deploymentStatus;

  /// Runs your workflow anytime the discussion event occurs. More than one activity type triggers this event. For information about the GraphQL API, see https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions
  final EventObjectObject? discussion;

  /// Runs your workflow anytime the discussion_comment event occurs. More than one activity type triggers this event. For information about the GraphQL API, see https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions
  final EventObjectObject? discussionComment;

  /// Runs your workflow anytime when someone forks a repository, which triggers the fork event. For information about the REST API, see https://developer.github.com/v3/repos/forks/#create-a-fork.
  final EventObjectObject? fork;

  /// Runs your workflow when someone creates or updates a Wiki page, which triggers the gollum event.
  final EventObjectObject? gollum;

  /// Runs your workflow anytime the issue_comment event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/issues/comments/.
  final EventObjectObject? issueComment;

  /// Runs your workflow anytime the issues event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/issues.
  final EventObjectObject? issues;

  /// Runs your workflow anytime the label event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/issues/labels/.
  final EventObjectObject? label;

  /// Runs your workflow when a pull request is added to a merge queue, which adds the pull request to a merge group. For information about the merge queue, see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue .
  final EventObjectObject? mergeGroup;

  /// Runs your workflow anytime the milestone event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/issues/milestones/.
  final EventObjectObject? milestone;

  /// Runs your workflow anytime someone pushes to a GitHub Pages-enabled branch, which triggers the page_build event. For information about the REST API, see https://developer.github.com/v3/repos/pages/.
  final EventObjectObject? pageBuild;

  /// Runs your workflow anytime the project event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/projects/.
  final EventObjectObject? project;

  /// Runs your workflow anytime the project_card event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/projects/cards.
  final EventObjectObject? projectCard;

  /// Runs your workflow anytime the project_column event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/projects/columns.
  final EventObjectObject? projectColumn;

  /// Runs your workflow anytime someone makes a private repository public, which triggers the public event. For information about the REST API, see https://developer.github.com/v3/repos/#edit.
  final EventObjectObject? public;

  /// Runs your workflow anytime the pull_request event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/pulls.
  /// Note: Workflows do not run on private base repositories when you open a pull request from a forked repository.
  /// When you create a pull request from a forked repository to the base repository, GitHub sends the pull_request event to the base repository and no pull request events occur on the forked repository.
  /// Workflows don't run on forked repositories by default. You must enable GitHub Actions in the Actions tab of the forked repository.
  /// The permissions for the GITHUB_TOKEN in forked repositories is read-only. For more information about the GITHUB_TOKEN, see https://help.github.com/en/articles/virtual-environments-for-github-actions.
  final RootSchemaOnPullRequest? pullRequest;

  /// Runs your workflow anytime the pull_request_review event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/pulls/reviews.
  /// Note: Workflows do not run on private base repositories when you open a pull request from a forked repository.
  /// When you create a pull request from a forked repository to the base repository, GitHub sends the pull_request event to the base repository and no pull request events occur on the forked repository.
  /// Workflows don't run on forked repositories by default. You must enable GitHub Actions in the Actions tab of the forked repository.
  /// The permissions for the GITHUB_TOKEN in forked repositories is read-only. For more information about the GITHUB_TOKEN, see https://help.github.com/en/articles/virtual-environments-for-github-actions.
  final EventObjectObject? pullRequestReview;

  /// Runs your workflow anytime a comment on a pull request's unified diff is modified, which triggers the pull_request_review_comment event. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/pulls/comments.
  /// Note: Workflows do not run on private base repositories when you open a pull request from a forked repository.
  /// When you create a pull request from a forked repository to the base repository, GitHub sends the pull_request event to the base repository and no pull request events occur on the forked repository.
  /// Workflows don't run on forked repositories by default. You must enable GitHub Actions in the Actions tab of the forked repository.
  /// The permissions for the GITHUB_TOKEN in forked repositories is read-only. For more information about the GITHUB_TOKEN, see https://help.github.com/en/articles/virtual-environments-for-github-actions.
  final EventObjectObject? pullRequestReviewComment;

  /// This event is similar to pull_request, except that it runs in the context of the base repository of the pull request, rather than in the merge commit. This means that you can more safely make your secrets available to the workflows triggered by the pull request, because only workflows defined in the commit on the base repository are run. For example, this event allows you to create workflows that label and comment on pull requests, based on the contents of the event payload.
  final RootSchemaOnPullRequestTarget? pullRequestTarget;

  /// Runs your workflow when someone pushes to a repository branch, which triggers the push event.
  /// Note: The webhook payload available to GitHub Actions does not include the added, removed, and modified attributes in the commit object. You can retrieve the full commit object using the REST API. For more information, see https://developer.github.com/v3/repos/commits/#get-a-single-commit.
  final RootSchemaOnPush? push;

  /// Runs your workflow anytime a package is published or updated. For more information, see https://help.github.com/en/github/managing-packages-with-github-packages.
  final EventObjectObject? registryPackage;

  /// Runs your workflow anytime the release event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/repos/releases/ in the GitHub Developer documentation.
  final EventObjectObject? release;

  /// You can use the GitHub API to trigger a webhook event called repository_dispatch when you want to trigger a workflow for activity that happens outside of GitHub. For more information, see https://developer.github.com/v3/repos/#create-a-repository-dispatch-event.
  /// To trigger the custom repository_dispatch webhook event, you must send a POST request to a GitHub API endpoint and provide an event_type name to describe the activity type. To trigger a workflow run, you must also configure your workflow to use the repository_dispatch event.
  final EventObjectObject? repositoryDispatch;

  /// You can schedule a workflow to run at specific UTC times using POSIX cron syntax (https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07). Scheduled workflows run on the latest commit on the default or base branch. The shortest interval you can run scheduled workflows is once every 5 minutes.
  /// Note: GitHub Actions does not support the non-standard syntax @yearly, @monthly, @weekly, @daily, @hourly, and @reboot.
  /// You can use crontab guru (https://crontab.guru/). to help generate your cron syntax and confirm what time it will run. To help you get started, there is also a list of crontab guru examples (https://crontab.guru/examples.html).
  /// Constraints: minItems: 1
  final List<OnObjectScheduleItem>? schedule;

  /// Runs your workflow anytime the status of a Git commit changes, which triggers the status event. For information about the REST API, see https://developer.github.com/v3/repos/statuses/.
  final EventObjectObject? status;

  /// Runs your workflow anytime the watch event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/activity/starring/.
  final EventObjectObject? watch;

  /// Allows workflows to be reused by other workflows.
  final OnObjectWorkflowCall? workflowCall;

  /// You can now create workflows that are manually triggered with the new workflow_dispatch event. You will then see a 'Run workflow' button on the Actions tab, enabling you to easily trigger a run.
  final OnObjectWorkflowDispatch? workflowDispatch;

  /// This event occurs when a workflow run is requested or completed, and allows you to execute a workflow based on the finished result of another workflow. For example, if your pull_request workflow generates build artifacts, you can create a new workflow that uses workflow_run to analyze the results and add a comment to the original pull request.
  final EventObjectObject? workflowRun;

  const OnObject({
    this.branchProtectionRule,
    this.checkRun,
    this.checkSuite,
    this.create,
    this.delete,
    this.deployment,
    this.deploymentStatus,
    this.discussion,
    this.discussionComment,
    this.fork,
    this.gollum,
    this.issueComment,
    this.issues,
    this.label,
    this.mergeGroup,
    this.milestone,
    this.pageBuild,
    this.project,
    this.projectCard,
    this.projectColumn,
    this.public,
    this.pullRequest,
    this.pullRequestReview,
    this.pullRequestReviewComment,
    this.pullRequestTarget,
    this.push,
    this.registryPackage,
    this.release,
    this.repositoryDispatch,
    this.schedule,
    this.status,
    this.watch,
    this.workflowCall,
    this.workflowDispatch,
    this.workflowRun,
  }) : super();

  factory OnObject.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final branchProtectionRule = json['branch_protection_rule'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['branch_protection_rule'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('branch_protection_rule');
    final checkRun = json['check_run'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['check_run'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('check_run');
    final checkSuite = json['check_suite'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['check_suite'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('check_suite');
    final create = json['create'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['create'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('create');
    final delete = json['delete'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['delete'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('delete');
    final deployment = json['deployment'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['deployment'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('deployment');
    final deploymentStatus = json['deployment_status'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['deployment_status'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('deployment_status');
    final discussion = json['discussion'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['discussion'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('discussion');
    final discussionComment = json['discussion_comment'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['discussion_comment'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('discussion_comment');
    final fork = json['fork'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['fork'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('fork');
    final gollum = json['gollum'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['gollum'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('gollum');
    final issueComment = json['issue_comment'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['issue_comment'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('issue_comment');
    final issues = json['issues'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['issues'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('issues');
    final label = json['label'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['label'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('label');
    final mergeGroup = json['merge_group'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['merge_group'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('merge_group');
    final milestone = json['milestone'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['milestone'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('milestone');
    final pageBuild = json['page_build'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['page_build'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('page_build');
    final project = json['project'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['project'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('project');
    final projectCard = json['project_card'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['project_card'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('project_card');
    final projectColumn = json['project_column'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['project_column'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('project_column');
    final public = json['public'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['public'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('public');
    final pullRequest = json['pull_request'] == null
        ? null
        : RootSchemaOnPullRequest.fromJson(
            (json['pull_request'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('pull_request');
    final pullRequestReview = json['pull_request_review'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['pull_request_review'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('pull_request_review');
    final pullRequestReviewComment = json['pull_request_review_comment'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['pull_request_review_comment'] as Map)
                .cast<String, dynamic>(),
          );
    remaining.remove('pull_request_review_comment');
    final pullRequestTarget = json['pull_request_target'] == null
        ? null
        : RootSchemaOnPullRequestTarget.fromJson(
            (json['pull_request_target'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('pull_request_target');
    final push = json['push'] == null
        ? null
        : RootSchemaOnPush.fromJson(
            (json['push'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('push');
    final registryPackage = json['registry_package'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['registry_package'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('registry_package');
    final release = json['release'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['release'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('release');
    final repositoryDispatch = json['repository_dispatch'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['repository_dispatch'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('repository_dispatch');
    final schedule = json['schedule'] == null
        ? null
        : (json['schedule'] as List)
              .map(
                (e) => OnObjectScheduleItem.fromJson(
                  (e as Map).cast<String, dynamic>(),
                ),
              )
              .toList();
    remaining.remove('schedule');
    final status = json['status'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['status'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('status');
    final watch = json['watch'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['watch'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('watch');
    final workflowCall = json['workflow_call'] == null
        ? null
        : OnObjectWorkflowCall.fromJson(
            (json['workflow_call'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('workflow_call');
    final workflowDispatch = json['workflow_dispatch'] == null
        ? null
        : OnObjectWorkflowDispatch.fromJson(
            (json['workflow_dispatch'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('workflow_dispatch');
    final workflowRun = json['workflow_run'] == null
        ? null
        : EventObjectObject.fromJson(
            (json['workflow_run'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('workflow_run');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return OnObject(
      branchProtectionRule: branchProtectionRule,
      checkRun: checkRun,
      checkSuite: checkSuite,
      create: create,
      delete: delete,
      deployment: deployment,
      deploymentStatus: deploymentStatus,
      discussion: discussion,
      discussionComment: discussionComment,
      fork: fork,
      gollum: gollum,
      issueComment: issueComment,
      issues: issues,
      label: label,
      mergeGroup: mergeGroup,
      milestone: milestone,
      pageBuild: pageBuild,
      project: project,
      projectCard: projectCard,
      projectColumn: projectColumn,
      public: public,
      pullRequest: pullRequest,
      pullRequestReview: pullRequestReview,
      pullRequestReviewComment: pullRequestReviewComment,
      pullRequestTarget: pullRequestTarget,
      push: push,
      registryPackage: registryPackage,
      release: release,
      repositoryDispatch: repositoryDispatch,
      schedule: schedule,
      status: status,
      watch: watch,
      workflowCall: workflowCall,
      workflowDispatch: workflowDispatch,
      workflowRun: workflowRun,
    );
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (branchProtectionRule != null)
      map['branch_protection_rule'] = branchProtectionRule!.toJson();
    if (checkRun != null) map['check_run'] = checkRun!.toJson();
    if (checkSuite != null) map['check_suite'] = checkSuite!.toJson();
    if (create != null) map['create'] = create!.toJson();
    if (delete != null) map['delete'] = delete!.toJson();
    if (deployment != null) map['deployment'] = deployment!.toJson();
    if (deploymentStatus != null)
      map['deployment_status'] = deploymentStatus!.toJson();
    if (discussion != null) map['discussion'] = discussion!.toJson();
    if (discussionComment != null)
      map['discussion_comment'] = discussionComment!.toJson();
    if (fork != null) map['fork'] = fork!.toJson();
    if (gollum != null) map['gollum'] = gollum!.toJson();
    if (issueComment != null) map['issue_comment'] = issueComment!.toJson();
    if (issues != null) map['issues'] = issues!.toJson();
    if (label != null) map['label'] = label!.toJson();
    if (mergeGroup != null) map['merge_group'] = mergeGroup!.toJson();
    if (milestone != null) map['milestone'] = milestone!.toJson();
    if (pageBuild != null) map['page_build'] = pageBuild!.toJson();
    if (project != null) map['project'] = project!.toJson();
    if (projectCard != null) map['project_card'] = projectCard!.toJson();
    if (projectColumn != null) map['project_column'] = projectColumn!.toJson();
    if (public != null) map['public'] = public!.toJson();
    if (pullRequest != null) map['pull_request'] = pullRequest!.toJson();
    if (pullRequestReview != null)
      map['pull_request_review'] = pullRequestReview!.toJson();
    if (pullRequestReviewComment != null)
      map['pull_request_review_comment'] = pullRequestReviewComment!.toJson();
    if (pullRequestTarget != null)
      map['pull_request_target'] = pullRequestTarget!.toJson();
    if (push != null) map['push'] = push!.toJson();
    if (registryPackage != null)
      map['registry_package'] = registryPackage!.toJson();
    if (release != null) map['release'] = release!.toJson();
    if (repositoryDispatch != null)
      map['repository_dispatch'] = repositoryDispatch!.toJson();
    if (schedule != null)
      map['schedule'] = schedule!.map((e) => e.toJson()).toList();
    if (status != null) map['status'] = status!.toJson();
    if (watch != null) map['watch'] = watch!.toJson();
    if (workflowCall != null) map['workflow_call'] = workflowCall!.toJson();
    if (workflowDispatch != null)
      map['workflow_dispatch'] = workflowDispatch!.toJson();
    if (workflowRun != null) map['workflow_run'] = workflowRun!.toJson();
    return map;
  }

  @override
  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'branch_protection_rule');
    final _value0 = branchProtectionRule;
    if (_value0 != null) {
      context?.markProperty(pointer, 'branch_protection_rule');
    }
    final _ptr1 = appendJsonPointer(pointer, 'check_run');
    final _value1 = checkRun;
    if (_value1 != null) {
      context?.markProperty(pointer, 'check_run');
    }
    final _ptr2 = appendJsonPointer(pointer, 'check_suite');
    final _value2 = checkSuite;
    if (_value2 != null) {
      context?.markProperty(pointer, 'check_suite');
    }
    final _ptr3 = appendJsonPointer(pointer, 'create');
    final _value3 = create;
    if (_value3 != null) {
      context?.markProperty(pointer, 'create');
    }
    final _ptr4 = appendJsonPointer(pointer, 'delete');
    final _value4 = delete;
    if (_value4 != null) {
      context?.markProperty(pointer, 'delete');
    }
    final _ptr5 = appendJsonPointer(pointer, 'deployment');
    final _value5 = deployment;
    if (_value5 != null) {
      context?.markProperty(pointer, 'deployment');
    }
    final _ptr6 = appendJsonPointer(pointer, 'deployment_status');
    final _value6 = deploymentStatus;
    if (_value6 != null) {
      context?.markProperty(pointer, 'deployment_status');
    }
    final _ptr7 = appendJsonPointer(pointer, 'discussion');
    final _value7 = discussion;
    if (_value7 != null) {
      context?.markProperty(pointer, 'discussion');
    }
    final _ptr8 = appendJsonPointer(pointer, 'discussion_comment');
    final _value8 = discussionComment;
    if (_value8 != null) {
      context?.markProperty(pointer, 'discussion_comment');
    }
    final _ptr9 = appendJsonPointer(pointer, 'fork');
    final _value9 = fork;
    if (_value9 != null) {
      context?.markProperty(pointer, 'fork');
    }
    final _ptr10 = appendJsonPointer(pointer, 'gollum');
    final _value10 = gollum;
    if (_value10 != null) {
      context?.markProperty(pointer, 'gollum');
    }
    final _ptr11 = appendJsonPointer(pointer, 'issue_comment');
    final _value11 = issueComment;
    if (_value11 != null) {
      context?.markProperty(pointer, 'issue_comment');
    }
    final _ptr12 = appendJsonPointer(pointer, 'issues');
    final _value12 = issues;
    if (_value12 != null) {
      context?.markProperty(pointer, 'issues');
    }
    final _ptr13 = appendJsonPointer(pointer, 'label');
    final _value13 = label;
    if (_value13 != null) {
      context?.markProperty(pointer, 'label');
    }
    final _ptr14 = appendJsonPointer(pointer, 'merge_group');
    final _value14 = mergeGroup;
    if (_value14 != null) {
      context?.markProperty(pointer, 'merge_group');
    }
    final _ptr15 = appendJsonPointer(pointer, 'milestone');
    final _value15 = milestone;
    if (_value15 != null) {
      context?.markProperty(pointer, 'milestone');
    }
    final _ptr16 = appendJsonPointer(pointer, 'page_build');
    final _value16 = pageBuild;
    if (_value16 != null) {
      context?.markProperty(pointer, 'page_build');
    }
    final _ptr17 = appendJsonPointer(pointer, 'project');
    final _value17 = project;
    if (_value17 != null) {
      context?.markProperty(pointer, 'project');
    }
    final _ptr18 = appendJsonPointer(pointer, 'project_card');
    final _value18 = projectCard;
    if (_value18 != null) {
      context?.markProperty(pointer, 'project_card');
    }
    final _ptr19 = appendJsonPointer(pointer, 'project_column');
    final _value19 = projectColumn;
    if (_value19 != null) {
      context?.markProperty(pointer, 'project_column');
    }
    final _ptr20 = appendJsonPointer(pointer, 'public');
    final _value20 = public;
    if (_value20 != null) {
      context?.markProperty(pointer, 'public');
    }
    final _ptr21 = appendJsonPointer(pointer, 'pull_request');
    final _value21 = pullRequest;
    if (_value21 != null) {
      context?.markProperty(pointer, 'pull_request');
      _value21.validate(pointer: _ptr21, context: context);
      final _jsonp21 = _value21.toJson();
      final _constraintp21c0_0 = context == null ? null : ValidationContext();
      var _constraintp21m0_0 = false;
      try {
        final context = _constraintp21c0_0;
        final _constraintp21v0_0 = _jsonp21;
        _constraintp21m0_0 = true;
      } on ValidationError {
      } catch (_) {}
      final _constraintp21c0_1 = context == null ? null : ValidationContext();
      var _constraintp21m0_1 = false;
      try {
        final context = _constraintp21c0_1;
        final _constraintp21v0_1 = RootSchemaOnPullRequest.fromJson(
          (_jsonp21 as Map).cast<String, dynamic>(),
        );
        _constraintp21v0_1.validate(pointer: _ptr21, context: context);
        final _jsonp21c0b1 = _constraintp21v0_1.toJson();
        final _constraintp21c0b1c0_0 = context == null
            ? null
            : ValidationContext();
        var _constraintp21c0b1m0_0 = false;
        try {
          final context = _constraintp21c0b1c0_0;
          final _constraintp21c0b1v0_0 = RootSchemaOnPullRequest2.fromJson(
            (_jsonp21c0b1 as Map).cast<String, dynamic>(),
          );
          _constraintp21c0b1v0_0.validate(pointer: _ptr21, context: context);
          _constraintp21c0b1m0_0 = true;
        } on ValidationError {
        } catch (_) {}
        final _constraintp21c0b1c0_1 = context == null
            ? null
            : ValidationContext();
        var _constraintp21c0b1m0_1 = false;
        try {
          final context = _constraintp21c0b1c0_1;
          final _constraintp21c0b1v0_1 = _jsonp21c0b1;
          final _jsonp21c0b1c0b1 = _constraintp21c0b1v0_1;
          final _constraintp21c0b1c0b1c0_0 = context == null
              ? null
              : ValidationContext();
          var _constraintp21c0b1c0b1m0_0 = false;
          try {
            final context = _constraintp21c0b1c0b1c0_0;
            final _constraintp21c0b1c0b1v0_0 =
                RootSchemaOnPullRequestNot.fromJson(
                  (_jsonp21c0b1c0b1 as Map).cast<String, dynamic>(),
                );
            _constraintp21c0b1c0b1m0_0 = true;
          } on ValidationError {
          } catch (_) {}
          final _constraintp21c0b1c0b1matches0 = <bool>[
            _constraintp21c0b1c0b1m0_0,
          ];
          if (_constraintp21c0b1c0b1matches0.any((value) => value)) {
            throwValidationError(
              _ptr21,
              'not',
              'Expected subschema at #/properties/on/oneOf/2/properties/pull_request/oneOf/1/allOf/1/not to fail validation.',
            );
          }
          _constraintp21c0b1m0_1 = true;
        } on ValidationError {
        } catch (_) {}
        final _constraintp21c0b1c0_2 = context == null
            ? null
            : ValidationContext();
        var _constraintp21c0b1m0_2 = false;
        try {
          final context = _constraintp21c0b1c0_2;
          final _constraintp21c0b1v0_2 = _jsonp21c0b1;
          final _jsonp21c0b1c0b2 = _constraintp21c0b1v0_2;
          final _constraintp21c0b1c0b2c0_0 = context == null
              ? null
              : ValidationContext();
          var _constraintp21c0b1c0b2m0_0 = false;
          try {
            final context = _constraintp21c0b1c0b2c0_0;
            final _constraintp21c0b1c0b2v0_0 =
                RootSchemaOnPullRequestNot2.fromJson(
                  (_jsonp21c0b1c0b2 as Map).cast<String, dynamic>(),
                );
            _constraintp21c0b1c0b2m0_0 = true;
          } on ValidationError {
          } catch (_) {}
          final _constraintp21c0b1c0b2matches0 = <bool>[
            _constraintp21c0b1c0b2m0_0,
          ];
          if (_constraintp21c0b1c0b2matches0.any((value) => value)) {
            throwValidationError(
              _ptr21,
              'not',
              'Expected subschema at #/properties/on/oneOf/2/properties/pull_request/oneOf/1/allOf/2/not to fail validation.',
            );
          }
          _constraintp21c0b1m0_2 = true;
        } on ValidationError {
        } catch (_) {}
        final _constraintp21c0b1c0_3 = context == null
            ? null
            : ValidationContext();
        var _constraintp21c0b1m0_3 = false;
        try {
          final context = _constraintp21c0b1c0_3;
          final _constraintp21c0b1v0_3 = _jsonp21c0b1;
          final _jsonp21c0b1c0b3 = _constraintp21c0b1v0_3;
          final _constraintp21c0b1c0b3c0_0 = context == null
              ? null
              : ValidationContext();
          var _constraintp21c0b1c0b3m0_0 = false;
          try {
            final context = _constraintp21c0b1c0b3c0_0;
            final _constraintp21c0b1c0b3v0_0 =
                RootSchemaOnPullRequestNot3.fromJson(
                  (_jsonp21c0b1c0b3 as Map).cast<String, dynamic>(),
                );
            _constraintp21c0b1c0b3m0_0 = true;
          } on ValidationError {
          } catch (_) {}
          final _constraintp21c0b1c0b3matches0 = <bool>[
            _constraintp21c0b1c0b3m0_0,
          ];
          if (_constraintp21c0b1c0b3matches0.any((value) => value)) {
            throwValidationError(
              _ptr21,
              'not',
              'Expected subschema at #/properties/on/oneOf/2/properties/pull_request/oneOf/1/allOf/3/not to fail validation.',
            );
          }
          _constraintp21c0b1m0_3 = true;
        } on ValidationError {
        } catch (_) {}
        final _constraintp21c0b1matches0 = <bool>[
          _constraintp21c0b1m0_0,
          _constraintp21c0b1m0_1,
          _constraintp21c0b1m0_2,
          _constraintp21c0b1m0_3,
        ];
        if (_constraintp21c0b1matches0.any((value) => !value)) {
          throwValidationError(
            _ptr21,
            'allOf',
            'Expected all subschemas in #/properties/on/oneOf/2/properties/pull_request/oneOf/1/allOf to validate.',
          );
        }
        if (context != null &&
            _constraintp21c0b1m0_0 &&
            _constraintp21c0b1c0_0 != null) {
          context.mergeFrom(_constraintp21c0b1c0_0!);
        }
        if (context != null &&
            _constraintp21c0b1m0_1 &&
            _constraintp21c0b1c0_1 != null) {
          context.mergeFrom(_constraintp21c0b1c0_1!);
        }
        if (context != null &&
            _constraintp21c0b1m0_2 &&
            _constraintp21c0b1c0_2 != null) {
          context.mergeFrom(_constraintp21c0b1c0_2!);
        }
        if (context != null &&
            _constraintp21c0b1m0_3 &&
            _constraintp21c0b1c0_3 != null) {
          context.mergeFrom(_constraintp21c0b1c0_3!);
        }
        _constraintp21m0_1 = true;
      } on ValidationError {
      } catch (_) {}
      final _constraintp21matches0 = <bool>[
        _constraintp21m0_0,
        _constraintp21m0_1,
      ];
      final _constraintp21count0 = _constraintp21matches0
          .where((value) => value)
          .length;
      if (_constraintp21count0 != 1) {
        throwValidationError(
          _ptr21,
          'oneOf',
          'Expected exactly one subschema in #/properties/on/oneOf/2/properties/pull_request/oneOf to validate.',
        );
      }
      if (context != null && _constraintp21m0_0 && _constraintp21c0_0 != null) {
        context.mergeFrom(_constraintp21c0_0!);
      }
      if (context != null && _constraintp21m0_1 && _constraintp21c0_1 != null) {
        context.mergeFrom(_constraintp21c0_1!);
      }
    }
    final _ptr22 = appendJsonPointer(pointer, 'pull_request_review');
    final _value22 = pullRequestReview;
    if (_value22 != null) {
      context?.markProperty(pointer, 'pull_request_review');
    }
    final _ptr23 = appendJsonPointer(pointer, 'pull_request_review_comment');
    final _value23 = pullRequestReviewComment;
    if (_value23 != null) {
      context?.markProperty(pointer, 'pull_request_review_comment');
    }
    final _ptr24 = appendJsonPointer(pointer, 'pull_request_target');
    final _value24 = pullRequestTarget;
    if (_value24 != null) {
      context?.markProperty(pointer, 'pull_request_target');
      _value24.validate(pointer: _ptr24, context: context);
      final _jsonp24 = _value24.toJson();
      final _constraintp24c0_0 = context == null ? null : ValidationContext();
      var _constraintp24m0_0 = false;
      try {
        final context = _constraintp24c0_0;
        final _constraintp24v0_0 = _jsonp24;
        _constraintp24m0_0 = true;
      } on ValidationError {
      } catch (_) {}
      final _constraintp24c0_1 = context == null ? null : ValidationContext();
      var _constraintp24m0_1 = false;
      try {
        final context = _constraintp24c0_1;
        final _constraintp24v0_1 = RootSchemaOnPullRequestTarget.fromJson(
          (_jsonp24 as Map).cast<String, dynamic>(),
        );
        _constraintp24v0_1.validate(pointer: _ptr24, context: context);
        final _jsonp24c0b1 = _constraintp24v0_1.toJson();
        final _constraintp24c0b1c0_0 = context == null
            ? null
            : ValidationContext();
        var _constraintp24c0b1m0_0 = false;
        try {
          final context = _constraintp24c0b1c0_0;
          final _constraintp24c0b1v0_0 =
              RootSchemaOnPullRequestTarget2.fromJson(
                (_jsonp24c0b1 as Map).cast<String, dynamic>(),
              );
          _constraintp24c0b1v0_0.validate(pointer: _ptr24, context: context);
          _constraintp24c0b1m0_0 = true;
        } on ValidationError {
        } catch (_) {}
        final _constraintp24c0b1c0_1 = context == null
            ? null
            : ValidationContext();
        var _constraintp24c0b1m0_1 = false;
        try {
          final context = _constraintp24c0b1c0_1;
          final _constraintp24c0b1v0_1 = _jsonp24c0b1;
          final _jsonp24c0b1c0b1 = _constraintp24c0b1v0_1;
          final _constraintp24c0b1c0b1c0_0 = context == null
              ? null
              : ValidationContext();
          var _constraintp24c0b1c0b1m0_0 = false;
          try {
            final context = _constraintp24c0b1c0b1c0_0;
            final _constraintp24c0b1c0b1v0_0 =
                RootSchemaOnPullRequestTargetNot.fromJson(
                  (_jsonp24c0b1c0b1 as Map).cast<String, dynamic>(),
                );
            _constraintp24c0b1c0b1m0_0 = true;
          } on ValidationError {
          } catch (_) {}
          final _constraintp24c0b1c0b1matches0 = <bool>[
            _constraintp24c0b1c0b1m0_0,
          ];
          if (_constraintp24c0b1c0b1matches0.any((value) => value)) {
            throwValidationError(
              _ptr24,
              'not',
              'Expected subschema at #/properties/on/oneOf/2/properties/pull_request_target/oneOf/1/allOf/1/not to fail validation.',
            );
          }
          _constraintp24c0b1m0_1 = true;
        } on ValidationError {
        } catch (_) {}
        final _constraintp24c0b1c0_2 = context == null
            ? null
            : ValidationContext();
        var _constraintp24c0b1m0_2 = false;
        try {
          final context = _constraintp24c0b1c0_2;
          final _constraintp24c0b1v0_2 = _jsonp24c0b1;
          final _jsonp24c0b1c0b2 = _constraintp24c0b1v0_2;
          final _constraintp24c0b1c0b2c0_0 = context == null
              ? null
              : ValidationContext();
          var _constraintp24c0b1c0b2m0_0 = false;
          try {
            final context = _constraintp24c0b1c0b2c0_0;
            final _constraintp24c0b1c0b2v0_0 =
                RootSchemaOnPullRequestTargetNot2.fromJson(
                  (_jsonp24c0b1c0b2 as Map).cast<String, dynamic>(),
                );
            _constraintp24c0b1c0b2m0_0 = true;
          } on ValidationError {
          } catch (_) {}
          final _constraintp24c0b1c0b2matches0 = <bool>[
            _constraintp24c0b1c0b2m0_0,
          ];
          if (_constraintp24c0b1c0b2matches0.any((value) => value)) {
            throwValidationError(
              _ptr24,
              'not',
              'Expected subschema at #/properties/on/oneOf/2/properties/pull_request_target/oneOf/1/allOf/2/not to fail validation.',
            );
          }
          _constraintp24c0b1m0_2 = true;
        } on ValidationError {
        } catch (_) {}
        final _constraintp24c0b1c0_3 = context == null
            ? null
            : ValidationContext();
        var _constraintp24c0b1m0_3 = false;
        try {
          final context = _constraintp24c0b1c0_3;
          final _constraintp24c0b1v0_3 = _jsonp24c0b1;
          final _jsonp24c0b1c0b3 = _constraintp24c0b1v0_3;
          final _constraintp24c0b1c0b3c0_0 = context == null
              ? null
              : ValidationContext();
          var _constraintp24c0b1c0b3m0_0 = false;
          try {
            final context = _constraintp24c0b1c0b3c0_0;
            final _constraintp24c0b1c0b3v0_0 =
                RootSchemaOnPullRequestTargetNot3.fromJson(
                  (_jsonp24c0b1c0b3 as Map).cast<String, dynamic>(),
                );
            _constraintp24c0b1c0b3m0_0 = true;
          } on ValidationError {
          } catch (_) {}
          final _constraintp24c0b1c0b3matches0 = <bool>[
            _constraintp24c0b1c0b3m0_0,
          ];
          if (_constraintp24c0b1c0b3matches0.any((value) => value)) {
            throwValidationError(
              _ptr24,
              'not',
              'Expected subschema at #/properties/on/oneOf/2/properties/pull_request_target/oneOf/1/allOf/3/not to fail validation.',
            );
          }
          _constraintp24c0b1m0_3 = true;
        } on ValidationError {
        } catch (_) {}
        final _constraintp24c0b1matches0 = <bool>[
          _constraintp24c0b1m0_0,
          _constraintp24c0b1m0_1,
          _constraintp24c0b1m0_2,
          _constraintp24c0b1m0_3,
        ];
        if (_constraintp24c0b1matches0.any((value) => !value)) {
          throwValidationError(
            _ptr24,
            'allOf',
            'Expected all subschemas in #/properties/on/oneOf/2/properties/pull_request_target/oneOf/1/allOf to validate.',
          );
        }
        if (context != null &&
            _constraintp24c0b1m0_0 &&
            _constraintp24c0b1c0_0 != null) {
          context.mergeFrom(_constraintp24c0b1c0_0!);
        }
        if (context != null &&
            _constraintp24c0b1m0_1 &&
            _constraintp24c0b1c0_1 != null) {
          context.mergeFrom(_constraintp24c0b1c0_1!);
        }
        if (context != null &&
            _constraintp24c0b1m0_2 &&
            _constraintp24c0b1c0_2 != null) {
          context.mergeFrom(_constraintp24c0b1c0_2!);
        }
        if (context != null &&
            _constraintp24c0b1m0_3 &&
            _constraintp24c0b1c0_3 != null) {
          context.mergeFrom(_constraintp24c0b1c0_3!);
        }
        _constraintp24m0_1 = true;
      } on ValidationError {
      } catch (_) {}
      final _constraintp24matches0 = <bool>[
        _constraintp24m0_0,
        _constraintp24m0_1,
      ];
      final _constraintp24count0 = _constraintp24matches0
          .where((value) => value)
          .length;
      if (_constraintp24count0 != 1) {
        throwValidationError(
          _ptr24,
          'oneOf',
          'Expected exactly one subschema in #/properties/on/oneOf/2/properties/pull_request_target/oneOf to validate.',
        );
      }
      if (context != null && _constraintp24m0_0 && _constraintp24c0_0 != null) {
        context.mergeFrom(_constraintp24c0_0!);
      }
      if (context != null && _constraintp24m0_1 && _constraintp24c0_1 != null) {
        context.mergeFrom(_constraintp24c0_1!);
      }
    }
    final _ptr25 = appendJsonPointer(pointer, 'push');
    final _value25 = push;
    if (_value25 != null) {
      context?.markProperty(pointer, 'push');
      _value25.validate(pointer: _ptr25, context: context);
      final _jsonp25 = _value25.toJson();
      final _constraintp25c0_0 = context == null ? null : ValidationContext();
      var _constraintp25m0_0 = false;
      try {
        final context = _constraintp25c0_0;
        final _constraintp25v0_0 = _jsonp25;
        _constraintp25m0_0 = true;
      } on ValidationError {
      } catch (_) {}
      final _constraintp25c0_1 = context == null ? null : ValidationContext();
      var _constraintp25m0_1 = false;
      try {
        final context = _constraintp25c0_1;
        final _constraintp25v0_1 = RootSchemaOnPush.fromJson(
          (_jsonp25 as Map).cast<String, dynamic>(),
        );
        _constraintp25v0_1.validate(pointer: _ptr25, context: context);
        final _jsonp25c0b1 = _constraintp25v0_1.toJson();
        final _constraintp25c0b1c0_0 = context == null
            ? null
            : ValidationContext();
        var _constraintp25c0b1m0_0 = false;
        try {
          final context = _constraintp25c0b1c0_0;
          final _constraintp25c0b1v0_0 = RootSchemaOnPush2.fromJson(
            (_jsonp25c0b1 as Map).cast<String, dynamic>(),
          );
          _constraintp25c0b1v0_0.validate(pointer: _ptr25, context: context);
          _constraintp25c0b1m0_0 = true;
        } on ValidationError {
        } catch (_) {}
        final _constraintp25c0b1c0_1 = context == null
            ? null
            : ValidationContext();
        var _constraintp25c0b1m0_1 = false;
        try {
          final context = _constraintp25c0b1c0_1;
          final _constraintp25c0b1v0_1 = _jsonp25c0b1;
          final _jsonp25c0b1c0b1 = _constraintp25c0b1v0_1;
          final _constraintp25c0b1c0b1c0_0 = context == null
              ? null
              : ValidationContext();
          var _constraintp25c0b1c0b1m0_0 = false;
          try {
            final context = _constraintp25c0b1c0b1c0_0;
            final _constraintp25c0b1c0b1v0_0 = RootSchemaOnPushNot.fromJson(
              (_jsonp25c0b1c0b1 as Map).cast<String, dynamic>(),
            );
            _constraintp25c0b1c0b1m0_0 = true;
          } on ValidationError {
          } catch (_) {}
          final _constraintp25c0b1c0b1matches0 = <bool>[
            _constraintp25c0b1c0b1m0_0,
          ];
          if (_constraintp25c0b1c0b1matches0.any((value) => value)) {
            throwValidationError(
              _ptr25,
              'not',
              'Expected subschema at #/properties/on/oneOf/2/properties/push/oneOf/1/allOf/1/not to fail validation.',
            );
          }
          _constraintp25c0b1m0_1 = true;
        } on ValidationError {
        } catch (_) {}
        final _constraintp25c0b1c0_2 = context == null
            ? null
            : ValidationContext();
        var _constraintp25c0b1m0_2 = false;
        try {
          final context = _constraintp25c0b1c0_2;
          final _constraintp25c0b1v0_2 = _jsonp25c0b1;
          final _jsonp25c0b1c0b2 = _constraintp25c0b1v0_2;
          final _constraintp25c0b1c0b2c0_0 = context == null
              ? null
              : ValidationContext();
          var _constraintp25c0b1c0b2m0_0 = false;
          try {
            final context = _constraintp25c0b1c0b2c0_0;
            final _constraintp25c0b1c0b2v0_0 = RootSchemaOnPushNot2.fromJson(
              (_jsonp25c0b1c0b2 as Map).cast<String, dynamic>(),
            );
            _constraintp25c0b1c0b2m0_0 = true;
          } on ValidationError {
          } catch (_) {}
          final _constraintp25c0b1c0b2matches0 = <bool>[
            _constraintp25c0b1c0b2m0_0,
          ];
          if (_constraintp25c0b1c0b2matches0.any((value) => value)) {
            throwValidationError(
              _ptr25,
              'not',
              'Expected subschema at #/properties/on/oneOf/2/properties/push/oneOf/1/allOf/2/not to fail validation.',
            );
          }
          _constraintp25c0b1m0_2 = true;
        } on ValidationError {
        } catch (_) {}
        final _constraintp25c0b1c0_3 = context == null
            ? null
            : ValidationContext();
        var _constraintp25c0b1m0_3 = false;
        try {
          final context = _constraintp25c0b1c0_3;
          final _constraintp25c0b1v0_3 = _jsonp25c0b1;
          final _jsonp25c0b1c0b3 = _constraintp25c0b1v0_3;
          final _constraintp25c0b1c0b3c0_0 = context == null
              ? null
              : ValidationContext();
          var _constraintp25c0b1c0b3m0_0 = false;
          try {
            final context = _constraintp25c0b1c0b3c0_0;
            final _constraintp25c0b1c0b3v0_0 = RootSchemaOnPushNot3.fromJson(
              (_jsonp25c0b1c0b3 as Map).cast<String, dynamic>(),
            );
            _constraintp25c0b1c0b3m0_0 = true;
          } on ValidationError {
          } catch (_) {}
          final _constraintp25c0b1c0b3matches0 = <bool>[
            _constraintp25c0b1c0b3m0_0,
          ];
          if (_constraintp25c0b1c0b3matches0.any((value) => value)) {
            throwValidationError(
              _ptr25,
              'not',
              'Expected subschema at #/properties/on/oneOf/2/properties/push/oneOf/1/allOf/3/not to fail validation.',
            );
          }
          _constraintp25c0b1m0_3 = true;
        } on ValidationError {
        } catch (_) {}
        final _constraintp25c0b1matches0 = <bool>[
          _constraintp25c0b1m0_0,
          _constraintp25c0b1m0_1,
          _constraintp25c0b1m0_2,
          _constraintp25c0b1m0_3,
        ];
        if (_constraintp25c0b1matches0.any((value) => !value)) {
          throwValidationError(
            _ptr25,
            'allOf',
            'Expected all subschemas in #/properties/on/oneOf/2/properties/push/oneOf/1/allOf to validate.',
          );
        }
        if (context != null &&
            _constraintp25c0b1m0_0 &&
            _constraintp25c0b1c0_0 != null) {
          context.mergeFrom(_constraintp25c0b1c0_0!);
        }
        if (context != null &&
            _constraintp25c0b1m0_1 &&
            _constraintp25c0b1c0_1 != null) {
          context.mergeFrom(_constraintp25c0b1c0_1!);
        }
        if (context != null &&
            _constraintp25c0b1m0_2 &&
            _constraintp25c0b1c0_2 != null) {
          context.mergeFrom(_constraintp25c0b1c0_2!);
        }
        if (context != null &&
            _constraintp25c0b1m0_3 &&
            _constraintp25c0b1c0_3 != null) {
          context.mergeFrom(_constraintp25c0b1c0_3!);
        }
        _constraintp25m0_1 = true;
      } on ValidationError {
      } catch (_) {}
      final _constraintp25matches0 = <bool>[
        _constraintp25m0_0,
        _constraintp25m0_1,
      ];
      final _constraintp25count0 = _constraintp25matches0
          .where((value) => value)
          .length;
      if (_constraintp25count0 != 1) {
        throwValidationError(
          _ptr25,
          'oneOf',
          'Expected exactly one subschema in #/properties/on/oneOf/2/properties/push/oneOf to validate.',
        );
      }
      if (context != null && _constraintp25m0_0 && _constraintp25c0_0 != null) {
        context.mergeFrom(_constraintp25c0_0!);
      }
      if (context != null && _constraintp25m0_1 && _constraintp25c0_1 != null) {
        context.mergeFrom(_constraintp25c0_1!);
      }
    }
    final _ptr26 = appendJsonPointer(pointer, 'registry_package');
    final _value26 = registryPackage;
    if (_value26 != null) {
      context?.markProperty(pointer, 'registry_package');
    }
    final _ptr27 = appendJsonPointer(pointer, 'release');
    final _value27 = release;
    if (_value27 != null) {
      context?.markProperty(pointer, 'release');
    }
    final _ptr28 = appendJsonPointer(pointer, 'repository_dispatch');
    final _value28 = repositoryDispatch;
    if (_value28 != null) {
      context?.markProperty(pointer, 'repository_dispatch');
    }
    final _ptr29 = appendJsonPointer(pointer, 'schedule');
    final _value29 = schedule;
    if (_value29 != null) {
      context?.markProperty(pointer, 'schedule');
      if (_value29.length < 1) {
        throwValidationError(
          _ptr29,
          'minItems',
          'Expected at least 1 items but found ' +
              _value29.length.toString() +
              '.',
        );
      }
    }
    final _ptr30 = appendJsonPointer(pointer, 'status');
    final _value30 = status;
    if (_value30 != null) {
      context?.markProperty(pointer, 'status');
    }
    final _ptr31 = appendJsonPointer(pointer, 'watch');
    final _value31 = watch;
    if (_value31 != null) {
      context?.markProperty(pointer, 'watch');
    }
    final _ptr32 = appendJsonPointer(pointer, 'workflow_call');
    final _value32 = workflowCall;
    if (_value32 != null) {
      context?.markProperty(pointer, 'workflow_call');
      _value32.validate(pointer: _ptr32, context: context);
    }
    final _ptr33 = appendJsonPointer(pointer, 'workflow_dispatch');
    final _value33 = workflowDispatch;
    if (_value33 != null) {
      context?.markProperty(pointer, 'workflow_dispatch');
      _value33.validate(pointer: _ptr33, context: context);
    }
    final _ptr34 = appendJsonPointer(pointer, 'workflow_run');
    final _value34 = workflowRun;
    if (_value34 != null) {
      context?.markProperty(pointer, 'workflow_run');
    }
  }
}
