// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'on_object_workflow_call_inputs.dart';
import 'on_object_workflow_call_outputs.dart';
import 'on_object_workflow_call_secrets.dart';
import 'validation_error.dart';

/// Allows workflows to be reused by other workflows.
class OnObjectWorkflowCall {
  /// When using the workflow_call keyword, you can optionally specify inputs that are passed to the called workflow from the caller workflow.
  final OnObjectWorkflowCallInputs? inputs;

  /// When using the workflow_call keyword, you can optionally specify inputs that are passed to the called workflow from the caller workflow.
  final OnObjectWorkflowCallOutputs? outputs;

  /// A map of the secrets that can be used in the called workflow. Within the called workflow, you can use the secrets context to refer to a secret.
  final OnObjectWorkflowCallSecrets? secrets;

  const OnObjectWorkflowCall({this.inputs, this.outputs, this.secrets});

  factory OnObjectWorkflowCall.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final inputs = json['inputs'] == null
        ? null
        : OnObjectWorkflowCallInputs.fromJson(
            (json['inputs'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('inputs');
    final outputs = json['outputs'] == null
        ? null
        : OnObjectWorkflowCallOutputs.fromJson(
            (json['outputs'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('outputs');
    final secrets = json['secrets'] == null
        ? null
        : OnObjectWorkflowCallSecrets.fromJson(
            (json['secrets'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('secrets');
    return OnObjectWorkflowCall(
      inputs: inputs,
      outputs: outputs,
      secrets: secrets,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (inputs != null) map['inputs'] = inputs!.toJson();
    if (outputs != null) map['outputs'] = outputs!.toJson();
    if (secrets != null) map['secrets'] = secrets!.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'inputs');
    final _value0 = inputs;
    if (_value0 != null) {
      context?.markProperty(pointer, 'inputs');
      _value0.validate(pointer: _ptr0, context: context);
    }
    final _ptr1 = appendJsonPointer(pointer, 'outputs');
    final _value1 = outputs;
    if (_value1 != null) {
      context?.markProperty(pointer, 'outputs');
    }
    final _ptr2 = appendJsonPointer(pointer, 'secrets');
    final _value2 = secrets;
    if (_value2 != null) {
      context?.markProperty(pointer, 'secrets');
    }
  }
}
