// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// The default value is used when an input parameter isn't specified in a workflow file.
sealed class OnObjectWorkflowCallInputsPatternProperty1Default {
  const OnObjectWorkflowCallInputsPatternProperty1Default();

  void validate({String pointer = '', ValidationContext? context});

  factory OnObjectWorkflowCallInputsPatternProperty1Default.fromJson(
    dynamic json,
  ) {
    if (json is bool)
      return OnObjectWorkflowCallInputsPatternProperty1DefaultBool(json);
    if (json is num)
      return OnObjectWorkflowCallInputsPatternProperty1DefaultNum(
        json.toDouble(),
      );
    if (json is String)
      return OnObjectWorkflowCallInputsPatternProperty1DefaultString(json);
    throw ArgumentError(
      'Invalid OnObjectWorkflowCallInputsPatternProperty1Default value type: ${json.runtimeType}',
    );
  }

  dynamic toJson();
}

class OnObjectWorkflowCallInputsPatternProperty1DefaultBool
    extends OnObjectWorkflowCallInputsPatternProperty1Default {
  final bool value;

  const OnObjectWorkflowCallInputsPatternProperty1DefaultBool(this.value)
    : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class OnObjectWorkflowCallInputsPatternProperty1DefaultNum
    extends OnObjectWorkflowCallInputsPatternProperty1Default {
  final double value;

  const OnObjectWorkflowCallInputsPatternProperty1DefaultNum(this.value)
    : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class OnObjectWorkflowCallInputsPatternProperty1DefaultString
    extends OnObjectWorkflowCallInputsPatternProperty1Default {
  final String value;

  const OnObjectWorkflowCallInputsPatternProperty1DefaultString(this.value)
    : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
