// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'on_object_workflow_dispatch_inputs.dart';
import 'validation_error.dart';

/// You can now create workflows that are manually triggered with the new workflow_dispatch event. You will then see a 'Run workflow' button on the Actions tab, enabling you to easily trigger a run.
class OnObjectWorkflowDispatch {
  /// Input parameters allow you to specify data that the action expects to use during runtime. GitHub stores input parameters as environment variables. Input ids with uppercase letters are converted to lowercase during runtime. We recommended using lowercase input ids.
  final OnObjectWorkflowDispatchInputs? inputs;

  const OnObjectWorkflowDispatch({this.inputs});

  factory OnObjectWorkflowDispatch.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final inputs = json['inputs'] == null
        ? null
        : OnObjectWorkflowDispatchInputs.fromJson(
            (json['inputs'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('inputs');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return OnObjectWorkflowDispatch(inputs: inputs);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (inputs != null) map['inputs'] = inputs!.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'inputs');
    final _value0 = inputs;
    if (_value0 != null) {
      context?.markProperty(pointer, 'inputs');
      _value0.validate(pointer: _ptr0, context: context);
    }
  }
}
