// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

/// Required if input is defined for the on.workflow_call keyword. The value of this parameter is a string specifying the data type of the input. This must be one of: boolean, number, or string.
enum OnObjectWorkflowCallInputsPatternProperty1Type { boolean, number, string }

extension OnObjectWorkflowCallInputsPatternProperty1TypeJson
    on OnObjectWorkflowCallInputsPatternProperty1Type {
  String toJson() => const {
    OnObjectWorkflowCallInputsPatternProperty1Type.boolean: 'boolean',
    OnObjectWorkflowCallInputsPatternProperty1Type.number: 'number',
    OnObjectWorkflowCallInputsPatternProperty1Type.string: 'string',
  }[this]!;

  static OnObjectWorkflowCallInputsPatternProperty1Type fromJson(
    String value,
  ) => const {
    'boolean': OnObjectWorkflowCallInputsPatternProperty1Type.boolean,
    'number': OnObjectWorkflowCallInputsPatternProperty1Type.number,
    'string': OnObjectWorkflowCallInputsPatternProperty1Type.string,
  }[value]!;
}
