// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'on_object_workflow_call_inputs_pattern_property1_default.dart';
import 'on_object_workflow_call_inputs_pattern_property1_type.dart';
import 'validation_error.dart';

/// A string identifier to associate with the input. The value of <input_id> is a map of the input's metadata. The <input_id> must be a unique identifier within the inputs object. The <input_id> must start with a letter or _ and contain only alphanumeric characters, -, or _.
class OnObjectWorkflowCallInputsPatternProperty1 {
  /// The default value is used when an input parameter isn't specified in a workflow file.
  /// Constraints: types: [boolean, number, string]
  final OnObjectWorkflowCallInputsPatternProperty1Default? default_;

  /// A string description of the input parameter.
  final String? description;

  /// A boolean to indicate whether the action requires the input parameter. Set to true when the parameter is required.
  final bool? required_;

  /// Required if input is defined for the on.workflow_call keyword. The value of this parameter is a string specifying the data type of the input. This must be one of: boolean, number, or string.
  final OnObjectWorkflowCallInputsPatternProperty1Type type;

  const OnObjectWorkflowCallInputsPatternProperty1({
    this.default_,
    this.description,
    this.required_,
    required this.type,
  });

  factory OnObjectWorkflowCallInputsPatternProperty1.fromJson(
    Map<String, dynamic> json,
  ) {
    final remaining = Map<String, dynamic>.from(json);
    final default_ = json['default'] == null
        ? null
        : OnObjectWorkflowCallInputsPatternProperty1Default.fromJson(
            (json['default'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('default');
    final description = json['description'] as String?;
    remaining.remove('description');
    final required_ = json['required'] as bool?;
    remaining.remove('required');
    final type = OnObjectWorkflowCallInputsPatternProperty1TypeJson.fromJson(
      json['type'] as String,
    );
    remaining.remove('type');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return OnObjectWorkflowCallInputsPatternProperty1(
      default_: default_,
      description: description,
      required_: required_,
      type: type,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (default_ != null) map['default'] = default_!.toJson();
    if (description != null) map['description'] = description;
    if (required_ != null) map['required'] = required_;
    map['type'] = type.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'default');
    final _value0 = default_;
    if (_value0 != null) {
      context?.markProperty(pointer, 'default');
      if (!(_value0 is bool || _value0 is num || _value0 is String)) {
        throwValidationError(
          _ptr0,
          'type',
          'Expected value to match one of the allowed types [boolean, number, string].',
        );
      }
    }
    final _ptr1 = appendJsonPointer(pointer, 'description');
    final _value1 = description;
    if (_value1 != null) {
      context?.markProperty(pointer, 'description');
    }
    final _ptr2 = appendJsonPointer(pointer, 'required');
    final _value2 = required_;
    if (_value2 != null) {
      context?.markProperty(pointer, 'required');
    }
    final _ptr3 = appendJsonPointer(pointer, 'type');
    final _value3 = type;
    context?.markProperty(pointer, 'type');
  }
}
