// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// A string identifier to associate with the secret.
class OnObjectWorkflowCallSecretsPatternProperty1 {
  /// A string description of the secret parameter.
  final String? description;

  /// A boolean specifying whether the secret must be supplied.
  final bool? required_;

  const OnObjectWorkflowCallSecretsPatternProperty1({
    this.description,
    this.required_,
  });

  factory OnObjectWorkflowCallSecretsPatternProperty1.fromJson(
    Map<String, dynamic> json,
  ) {
    final remaining = Map<String, dynamic>.from(json);
    final description = json['description'] as String?;
    remaining.remove('description');
    final required_ = json['required'] as bool?;
    remaining.remove('required');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return OnObjectWorkflowCallSecretsPatternProperty1(
      description: description,
      required_: required_,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (description != null) map['description'] = description;
    if (required_ != null) map['required'] = required_;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
