// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

/// Required if input is defined for the on.workflow_call keyword. The value of this parameter is a string specifying the data type of the input. This must be one of: boolean, number, or string.
enum OnWorkflowCallInputsPatternProperty1Type { boolean, number, string }

extension OnWorkflowCallInputsPatternProperty1TypeJson on OnWorkflowCallInputsPatternProperty1Type {
  String toJson() => const {
        OnWorkflowCallInputsPatternProperty1Type.boolean: 'boolean',
        OnWorkflowCallInputsPatternProperty1Type.number: 'number',
        OnWorkflowCallInputsPatternProperty1Type.string: 'string',
      }[this]!;

  static OnWorkflowCallInputsPatternProperty1Type fromJson(String value) => const {
        'boolean': OnWorkflowCallInputsPatternProperty1Type.boolean,
        'number': OnWorkflowCallInputsPatternProperty1Type.number,
        'string': OnWorkflowCallInputsPatternProperty1Type.string,
      }[value]!;
}
