// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'on_workflow_call_outputs_pattern_property1.dart';
import 'validation_error.dart';

/// When using the workflow_call keyword, you can optionally specify inputs that are passed to the called workflow from the caller workflow.
class OnWorkflowCallOutputs {
  final Map<String, OnWorkflowCallOutputsPatternProperty1>? patternProperties;

  const OnWorkflowCallOutputs({
    this.patternProperties,
  });

  factory OnWorkflowCallOutputs.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    var unmatched = Map<String, dynamic>.from(remaining);
    Map<String, OnWorkflowCallOutputsPatternProperty1>? patternPropertiesValue;
    {
      final patternPropertiesMap = <String, OnWorkflowCallOutputsPatternProperty1>{};
      final unmatchedAfterPattern = <String, dynamic>{};
      for (final entry in unmatched.entries) {
        final key = entry.key;
        final value = entry.value;
        var matched = false;
        if (!matched && RegExp('^[_a-zA-Z][a-zA-Z0-9_-]*\$').hasMatch(key)) {
          patternPropertiesMap[key] = OnWorkflowCallOutputsPatternProperty1.fromJson((value as Map).cast<String, dynamic>());
          matched = true;
        }
        if (!matched) {
          unmatchedAfterPattern[key] = value;
        }
      }
      patternPropertiesValue = patternPropertiesMap.isEmpty ? null : patternPropertiesMap;
      unmatched = unmatchedAfterPattern;
    }
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return OnWorkflowCallOutputs(
      patternProperties: patternPropertiesValue,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (patternProperties != null) {
      for (final entry in patternProperties!.entries) {
        final key = entry.key;
        final value = entry.value;
        var matched = false;
        if (!matched && RegExp('^[_a-zA-Z][a-zA-Z0-9_-]*\$').hasMatch(key)) {
          map[key] = value.toJson();
          matched = true;
        }
        if (!matched) {
          map[key] = value;
        }
      }
    }
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
