// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

enum PermissionsObjectModels { read, none }

extension PermissionsObjectModelsJson on PermissionsObjectModels {
  String toJson() => const {
    PermissionsObjectModels.read: 'read',
    PermissionsObjectModels.none: 'none',
  }[this]!;

  static PermissionsObjectModels fromJson(String value) => const {
    'read': PermissionsObjectModels.read,
    'none': PermissionsObjectModels.none,
  }[value]!;
}
