// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

enum PermissionsString { readAll, writeAll }

extension PermissionsStringJson on PermissionsString {
  String toJson() => const {
        PermissionsString.readAll: 'read-all',
        PermissionsString.writeAll: 'write-all',
      }[this]!;

  static PermissionsString fromJson(String value) => const {
        'read-all': PermissionsString.readAll,
        'write-all': PermissionsString.writeAll,
      }[value]!;
}
