// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

enum Permissions { readAll, writeAll }

extension PermissionsJson on Permissions {
  String toJson() => const {
        Permissions.readAll: 'read-all',
        Permissions.writeAll: 'write-all',
      }[this]!;

  static Permissions fromJson(String value) => const {
        'read-all': Permissions.readAll,
        'write-all': Permissions.writeAll,
      }[value]!;
}
