// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class PullRequest {
  final List<String>? branches;
  final List<String>? branchesIgnore;
  final List<String>? paths;
  final List<String>? pathsIgnore;
  final List<String>? tags;
  final List<String>? tagsIgnore;
  /// Default: [opened, synchronize, reopened].
  final dynamic types;

  const PullRequest({
    this.branches,
    this.branchesIgnore,
    this.paths,
    this.pathsIgnore,
    this.tags,
    this.tagsIgnore,
    this.types,
  });

  factory PullRequest.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final branches = json['branches'] == null ? null : (json['branches'] as List).map((e) => e as String).toList();
    remaining.remove('branches');
    final branchesIgnore = json['branches-ignore'] == null ? null : (json['branches-ignore'] as List).map((e) => e as String).toList();
    remaining.remove('branches-ignore');
    final paths = json['paths'] == null ? null : (json['paths'] as List).map((e) => e as String).toList();
    remaining.remove('paths');
    final pathsIgnore = json['paths-ignore'] == null ? null : (json['paths-ignore'] as List).map((e) => e as String).toList();
    remaining.remove('paths-ignore');
    final tags = json['tags'] == null ? null : (json['tags'] as List).map((e) => e as String).toList();
    remaining.remove('tags');
    final tagsIgnore = json['tags-ignore'] == null ? null : (json['tags-ignore'] as List).map((e) => e as String).toList();
    remaining.remove('tags-ignore');
    final types = json['types'];
    remaining.remove('types');
    return PullRequest(
      branches: branches,
      branchesIgnore: branchesIgnore,
      paths: paths,
      pathsIgnore: pathsIgnore,
      tags: tags,
      tagsIgnore: tagsIgnore,
      types: types,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (branches != null) map['branches'] = branches;
    if (branchesIgnore != null) map['branches-ignore'] = branchesIgnore;
    if (paths != null) map['paths'] = paths;
    if (pathsIgnore != null) map['paths-ignore'] = pathsIgnore;
    if (tags != null) map['tags'] = tags;
    if (tagsIgnore != null) map['tags-ignore'] = tagsIgnore;
    if (types != null) map['types'] = types;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
