// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

enum ReusableWorkflowCallJobSecretsString { inherit }

extension ReusableWorkflowCallJobSecretsStringJson on ReusableWorkflowCallJobSecretsString {
  String toJson() => const {
        ReusableWorkflowCallJobSecretsString.inherit: 'inherit',
      }[this]!;

  static ReusableWorkflowCallJobSecretsString fromJson(String value) => const {
        'inherit': ReusableWorkflowCallJobSecretsString.inherit,
      }[value]!;
}
