// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// When set to true, GitHub cancels all in-progress jobs if any matrix job fails. Default: true
sealed class ReusableWorkflowCallJobStrategyFailFast {
  const ReusableWorkflowCallJobStrategyFailFast();

  void validate({String pointer = '', ValidationContext? context});

  factory ReusableWorkflowCallJobStrategyFailFast.fromJson(dynamic json) {
    if (json is bool) return ReusableWorkflowCallJobStrategyFailFastBool(json);
    if (json is String)
      return ReusableWorkflowCallJobStrategyFailFastString(json);
    throw ArgumentError(
      'Invalid ReusableWorkflowCallJobStrategyFailFast value type: ${json.runtimeType}',
    );
  }

  dynamic toJson();
}

class ReusableWorkflowCallJobStrategyFailFastBool
    extends ReusableWorkflowCallJobStrategyFailFast {
  final bool value;

  const ReusableWorkflowCallJobStrategyFailFastBool(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class ReusableWorkflowCallJobStrategyFailFastString
    extends ReusableWorkflowCallJobStrategyFailFast {
  final String value;

  const ReusableWorkflowCallJobStrategyFailFastString(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
