// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// The maximum number of jobs that can run simultaneously when using a matrix job strategy. By default, GitHub will maximize the number of jobs run in parallel depending on the available runners on GitHub-hosted virtual machines.
sealed class ReusableWorkflowCallJobStrategyMaxParallel {
  const ReusableWorkflowCallJobStrategyMaxParallel();

  void validate({String pointer = '', ValidationContext? context});

  factory ReusableWorkflowCallJobStrategyMaxParallel.fromJson(dynamic json) {
    if (json is num)
      return ReusableWorkflowCallJobStrategyMaxParallelNum(json.toDouble());
    if (json is String)
      return ReusableWorkflowCallJobStrategyMaxParallelString(json);
    throw ArgumentError(
      'Invalid ReusableWorkflowCallJobStrategyMaxParallel value type: ${json.runtimeType}',
    );
  }

  dynamic toJson();
}

class ReusableWorkflowCallJobStrategyMaxParallelNum
    extends ReusableWorkflowCallJobStrategyMaxParallel {
  final double value;

  const ReusableWorkflowCallJobStrategyMaxParallelNum(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class ReusableWorkflowCallJobStrategyMaxParallelString
    extends ReusableWorkflowCallJobStrategyMaxParallel {
  final String value;

  const ReusableWorkflowCallJobStrategyMaxParallelString(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
