// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'matrix.dart';
import 'reusable_workflow_call_job_strategy_fail_fast.dart';
import 'reusable_workflow_call_job_strategy_max_parallel.dart';
import 'validation_error.dart';

/// A strategy creates a build matrix for your jobs. You can define different variations of an environment to run each job in.
class ReusableWorkflowCallJobStrategy {
  /// When set to true, GitHub cancels all in-progress jobs if any matrix job fails. Default: true
  ///
  /// Default: true.
  /// Constraints: types: [boolean, string]
  final ReusableWorkflowCallJobStrategyFailFast? failFast;
  final Matrix matrix;

  /// The maximum number of jobs that can run simultaneously when using a matrix job strategy. By default, GitHub will maximize the number of jobs run in parallel depending on the available runners on GitHub-hosted virtual machines.
  /// Constraints: types: [number, string]
  final ReusableWorkflowCallJobStrategyMaxParallel? maxParallel;

  const ReusableWorkflowCallJobStrategy({
    this.failFast = const ReusableWorkflowCallJobStrategyFailFastBool(true),
    required this.matrix,
    this.maxParallel,
  });

  factory ReusableWorkflowCallJobStrategy.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final failFast =
        (json['fail-fast'] == null
            ? null
            : ReusableWorkflowCallJobStrategyFailFast.fromJson(
                (json['fail-fast'] as Map).cast<String, dynamic>(),
              )) ??
        const ReusableWorkflowCallJobStrategyFailFastBool(true);
    remaining.remove('fail-fast');
    final matrix = Matrix.fromJson(
      (json['matrix'] as Map).cast<String, dynamic>(),
    );
    remaining.remove('matrix');
    final maxParallel = json['max-parallel'] == null
        ? null
        : ReusableWorkflowCallJobStrategyMaxParallel.fromJson(
            (json['max-parallel'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('max-parallel');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return ReusableWorkflowCallJobStrategy(
      failFast: failFast,
      matrix: matrix,
      maxParallel: maxParallel,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (failFast != null) map['fail-fast'] = failFast!.toJson();
    map['matrix'] = matrix.toJson();
    if (maxParallel != null) map['max-parallel'] = maxParallel!.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'fail-fast');
    final _value0 = failFast;
    context?.annotate(
      _ptr0,
      'default',
      true,
      schemaPointer:
          '#/definitions/reusableWorkflowCallJob/properties/strategy/properties/fail-fast',
    );
    if (_value0 != null) {
      context?.markProperty(pointer, 'fail-fast');
      if (!(_value0 is bool || _value0 is String)) {
        throwValidationError(
          _ptr0,
          'type',
          'Expected value to match one of the allowed types [boolean, string].',
        );
      }
    }
    final _ptr1 = appendJsonPointer(pointer, 'matrix');
    final _value1 = matrix;
    context?.markProperty(pointer, 'matrix');
    final _ptr2 = appendJsonPointer(pointer, 'max-parallel');
    final _value2 = maxParallel;
    if (_value2 != null) {
      context?.markProperty(pointer, 'max-parallel');
      if (!(_value2 is num || _value2 is String)) {
        throwValidationError(
          _ptr2,
          'type',
          'Expected value to match one of the allowed types [number, string].',
        );
      }
    }
  }
}
