// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// You can use the if conditional to prevent a job from running unless a condition is met. You can use any supported context and expression to create a conditional.
/// Expressions in an if conditional do not require the ${{ }} syntax. For more information, see https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions.
sealed class ReusableWorkflowCallJobIf {
  const ReusableWorkflowCallJobIf();

  void validate({String pointer = '', ValidationContext? context});

  factory ReusableWorkflowCallJobIf.fromJson(dynamic json) {
    if (json is bool) return ReusableWorkflowCallJobIfBool(json);
    if (json is num) return ReusableWorkflowCallJobIfNum(json.toDouble());
    if (json is String) return ReusableWorkflowCallJobIfString(json);
    throw ArgumentError(
      'Invalid ReusableWorkflowCallJobIf value type: ${json.runtimeType}',
    );
  }

  dynamic toJson();
}

class ReusableWorkflowCallJobIfBool extends ReusableWorkflowCallJobIf {
  final bool value;

  const ReusableWorkflowCallJobIfBool(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class ReusableWorkflowCallJobIfNum extends ReusableWorkflowCallJobIf {
  final double value;

  const ReusableWorkflowCallJobIfNum(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class ReusableWorkflowCallJobIfString extends ReusableWorkflowCallJobIf {
  final String value;

  const ReusableWorkflowCallJobIfString(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
