// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'reusable_workflow_call_job_secrets_string.dart';
import 'validation_error.dart';

/// When a job is used to call a reusable workflow, you can use 'secrets' to provide a map of secrets that are passed to the called workflow. Any secrets that you pass must match the names defined in the called workflow.
sealed class ReusableWorkflowCallJobSecrets {
  const ReusableWorkflowCallJobSecrets();

  void validate({String pointer = '', ValidationContext? context});

  factory ReusableWorkflowCallJobSecrets.fromJson(dynamic json) {
    if (json is! Map<String, dynamic>) {
      throw ArgumentError('Invalid ReusableWorkflowCallJobSecrets value: ${json.runtimeType}');
    }
    final keys = json.keys.toSet();
    final sortedKeys = keys.toList()..sort();
    return ReusableWorkflowCallJobSecretsObject.fromJson(json);
  }

  dynamic toJson();
}
/// To set custom environment variables, you need to specify the variables in the workflow file. You can define environment variables for a step, job, or entire workflow using the jobs.<job_id>.steps[*].env, jobs.<job_id>.env, and env keywords. For more information, see https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsenv
class ReusableWorkflowCallJobSecretsObject extends ReusableWorkflowCallJobSecrets {

  const ReusableWorkflowCallJobSecretsObject(): super();

  factory ReusableWorkflowCallJobSecretsObject.fromJson(Map<String, dynamic> json) {
    return ReusableWorkflowCallJobSecretsObject(
    );
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    return map;
  }

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
class ReusableWorkflowCallJobSecretsValue extends ReusableWorkflowCallJobSecrets {
  final ReusableWorkflowCallJobSecretsString value;

  const ReusableWorkflowCallJobSecretsValue(this.value) : super();

  @override
  dynamic toJson() => value;
}
