// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class RootSchemaOnPullRequestNot2 {
  const RootSchemaOnPullRequestNot2();

  factory RootSchemaOnPullRequestNot2.fromJson(Map<String, dynamic> json) {
    return RootSchemaOnPullRequestNot2();
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
