// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class RootSchemaOnPushNot {
  const RootSchemaOnPushNot();

  factory RootSchemaOnPushNot.fromJson(Map<String, dynamic> json) {
    return RootSchemaOnPushNot();
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
