// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class RootSchemaOnPushNot3 {
  const RootSchemaOnPushNot3();

  factory RootSchemaOnPushNot3.fromJson(Map<String, dynamic> json) {
    return RootSchemaOnPushNot3();
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
