// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class RunsOn {
  final String? group;
  final dynamic labels;

  const RunsOn({
    this.group,
    this.labels,
  });

  factory RunsOn.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final group = json['group'] as String?;
    remaining.remove('group');
    final labels = json['labels'];
    remaining.remove('labels');
    return RunsOn(
      group: group,
      labels: labels,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (group != null) map['group'] = group;
    if (labels != null) map['labels'] = labels;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
