// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

enum Secrets { inherit }

extension SecretsJson on Secrets {
  String toJson() => const {
        Secrets.inherit: 'inherit',
      }[this]!;

  static Secrets fromJson(String value) => const {
        'inherit': Secrets.inherit,
      }[value]!;
}
