// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'shell_string.dart';

/// You can override the default shell settings in the runner's operating system using the shell keyword. You can use built-in shell keywords, or you can define a custom set of shell options.
sealed class Shell {
  const Shell();

  factory Shell.fromJson(dynamic json) {
    if (json is String) return ShellString2(json);
    if (json is String) return ShellValue(ShellStringJson.fromJson(json));
    throw ArgumentError('Invalid Shell value type: ${json.runtimeType}');
  }

  dynamic toJson();
}
class ShellString2 extends Shell {
  final String value;

  const ShellString2(this.value) : super();

  @override
  dynamic toJson() => value;
}
class ShellValue extends Shell {
  final ShellString value;

  const ShellValue(this.value) : super();

  @override
  dynamic toJson() => value.toJson();
}
