// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

enum Shell { bash, pwsh, python, sh, cmd, powershell }

extension ShellJson on Shell {
  String toJson() => const {
        Shell.bash: 'bash',
        Shell.pwsh: 'pwsh',
        Shell.python: 'python',
        Shell.sh: 'sh',
        Shell.cmd: 'cmd',
        Shell.powershell: 'powershell',
      }[this]!;

  static Shell fromJson(String value) => const {
        'bash': Shell.bash,
        'pwsh': Shell.pwsh,
        'python': Shell.python,
        'sh': Shell.sh,
        'cmd': Shell.cmd,
        'powershell': Shell.powershell,
      }[value]!;
}
