// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// You can use the if conditional to prevent a step from running unless a condition is met. You can use any supported context and expression to create a conditional.
/// Expressions in an if conditional do not require the ${{ }} syntax. For more information, see https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions.
sealed class StepIf {
  const StepIf();

  void validate({String pointer = '', ValidationContext? context});

  factory StepIf.fromJson(dynamic json) {
    if (json is bool) return StepIfBool(json);
    if (json is num) return StepIfNum(json.toDouble());
    if (json is String) return StepIfString(json);
    throw ArgumentError('Invalid StepIf value type: ${json.runtimeType}');
  }

  dynamic toJson();
}

class StepIfBool extends StepIf {
  final bool value;

  const StepIfBool(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class StepIfNum extends StepIf {
  final double value;

  const StepIfNum(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class StepIfString extends StepIf {
  final String value;

  const StepIfString(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
