// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// Prevents a job from failing when a step fails. Set to true to allow a job to pass when this step fails.
sealed class StepContinueOnError {
  const StepContinueOnError();

  void validate({String pointer = '', ValidationContext? context});

  factory StepContinueOnError.fromJson(dynamic json) {
    if (json is bool) return StepContinueOnErrorBool(json);
    if (json is String) return StepContinueOnErrorString(json);
    throw ArgumentError('Invalid StepContinueOnError value type: ${json.runtimeType}');
  }

  dynamic toJson();
}
class StepContinueOnErrorBool extends StepContinueOnError {
  final bool value;

  const StepContinueOnErrorBool(this.value) : super();

  @override
  dynamic toJson() => value;
}
class StepContinueOnErrorString extends StepContinueOnError {
  final String value;

  const StepContinueOnErrorString(this.value) : super();

  @override
  dynamic toJson() => value;
}
