// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// Selects the types of activity that will trigger a workflow run. Most GitHub events are triggered by more than one type of activity. For example, the event for the release resource is triggered when a release is published, unpublished, created, edited, deleted, or prereleased. The types keyword enables you to narrow down activity that causes the workflow to run. When only one activity type triggers a webhook event, the types keyword is unnecessary.
/// You can use an array of event types. For more information about each event and their activity types, see https://help.github.com/en/articles/events-that-trigger-workflows#webhook-events.
sealed class Types {
  const Types();

  void validate({String pointer = '', ValidationContext? context});

  factory Types.fromJson(dynamic json) {
    if (json is String) return TypesString(json);
    throw ArgumentError('Invalid Types value type: ${json.runtimeType}');
  }

  dynamic toJson();
}
class TypesArray extends Types {
  final List<dynamic> value;

  const TypesArray(this.value) : super();

  @override
  dynamic toJson() => value;
}
class TypesString extends Types {
  final String value;

  const TypesString(this.value) : super();

  @override
  dynamic toJson() => value;
}
