// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';
import 'workflow_dispatch_input_type.dart';

/// A string identifier to associate with the input. The value of <input_id> is a map of the input's metadata. The <input_id> must be a unique identifier within the inputs object. The <input_id> must start with a letter or _ and contain only alphanumeric characters, -, or _.
class WorkflowDispatchInput {
  /// A string representing the default value. The default value is used when an input parameter isn't specified in a workflow file.
  final dynamic default_;
  /// A string shown to users using the deprecated input.
  final String? deprecationMessage;
  /// A string description of the input parameter.
  final String description;
  /// The options of the dropdown list, if the type is a choice.
  /// Constraints: minItems: 1
  final List<String>? options;
  /// A boolean to indicate whether the action requires the input parameter. Set to true when the parameter is required.
  final bool? required_;
  /// A string representing the type of the input.
  final WorkflowDispatchInputType? type;

  const WorkflowDispatchInput({
    this.default_,
    this.deprecationMessage,
    required this.description,
    this.options,
    this.required_,
    this.type,
  });

  factory WorkflowDispatchInput.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final default_ = json['default'];
    remaining.remove('default');
    final deprecationMessage = json['deprecationMessage'] as String?;
    remaining.remove('deprecationMessage');
    final description = json['description'] as String;
    remaining.remove('description');
    final options = json['options'] == null ? null : (json['options'] as List).map((e) => e as String).toList();
    remaining.remove('options');
    final required_ = json['required'] as bool?;
    remaining.remove('required');
    final type = json['type'] == null ? null : WorkflowDispatchInputTypeJson.fromJson(json['type'] as String);
    remaining.remove('type');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return WorkflowDispatchInput(
      default_: default_,
      deprecationMessage: deprecationMessage,
      description: description,
      options: options,
      required_: required_,
      type: type,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (default_ != null) map['default'] = default_;
    if (deprecationMessage != null) map['deprecationMessage'] = deprecationMessage;
    map['description'] = description;
    if (options != null) map['options'] = options;
    if (required_ != null) map['required'] = required_;
    if (type != null) map['type'] = type!.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'default');
    final _value0 = default_;
    if (_value0 != null) {
      context?.markProperty(pointer, 'default');
    }
    final _ptr1 = appendJsonPointer(pointer, 'deprecationMessage');
    final _value1 = deprecationMessage;
    if (_value1 != null) {
      context?.markProperty(pointer, 'deprecationMessage');
    }
    final _ptr2 = appendJsonPointer(pointer, 'description');
    final _value2 = description;
    context?.markProperty(pointer, 'description');
    final _ptr3 = appendJsonPointer(pointer, 'options');
    final _value3 = options;
    if (_value3 != null) {
      context?.markProperty(pointer, 'options');
    }
    final _ptr4 = appendJsonPointer(pointer, 'required');
    final _value4 = required_;
    if (_value4 != null) {
      context?.markProperty(pointer, 'required');
    }
    final _ptr5 = appendJsonPointer(pointer, 'type');
    final _value5 = type;
    if (_value5 != null) {
      context?.markProperty(pointer, 'type');
    }
  }
}
