// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/nullable_types/schema.json
// Generated by json_schema2dart

import 'nullable_object.dart';
import 'validation_error.dart';

/// Demonstrates nullable field handling
class NullableTypesExample {
  /// Constraints: types: [array, null]
  final List<String>? nullableArray;

  /// A number that can be null
  /// Constraints: types: [number, null]
  final double? nullableNumber;

  /// Constraints: types: [object, null]
  final NullableObject? nullableObject;

  /// A string that can be null
  /// Constraints: types: [string, null]
  final String? nullableString;

  const NullableTypesExample({
    this.nullableArray,
    this.nullableNumber,
    this.nullableObject,
    this.nullableString,
  });

  factory NullableTypesExample.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final nullableArray = json['nullableArray'] == null
        ? null
        : (json['nullableArray'] as List).map((e) => e as String).toList();
    remaining.remove('nullableArray');
    final nullableNumber = json['nullableNumber'] as double?;
    remaining.remove('nullableNumber');
    final nullableObject = json['nullableObject'] == null
        ? null
        : NullableObject.fromJson(
            (json['nullableObject'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('nullableObject');
    final nullableString = json['nullableString'] as String?;
    remaining.remove('nullableString');
    return NullableTypesExample(
      nullableArray: nullableArray,
      nullableNumber: nullableNumber,
      nullableObject: nullableObject,
      nullableString: nullableString,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (nullableArray != null) map['nullableArray'] = nullableArray;
    if (nullableNumber != null) map['nullableNumber'] = nullableNumber;
    if (nullableObject != null)
      map['nullableObject'] = nullableObject!.toJson();
    if (nullableString != null) map['nullableString'] = nullableString;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'nullableArray');
    final _value0 = nullableArray;
    if (_value0 != null) {
      context?.markProperty(pointer, 'nullableArray');
      if (!(_value0 is List || _value0 == null)) {
        throwValidationError(
          _ptr0,
          'type',
          'Expected value to match one of the allowed types [array, null].',
        );
      }
    }
    final _ptr1 = appendJsonPointer(pointer, 'nullableNumber');
    final _value1 = nullableNumber;
    if (_value1 != null) {
      context?.markProperty(pointer, 'nullableNumber');
      if (!(_value1 is num || _value1 == null)) {
        throwValidationError(
          _ptr1,
          'type',
          'Expected value to match one of the allowed types [number, null].',
        );
      }
    }
    final _ptr2 = appendJsonPointer(pointer, 'nullableObject');
    final _value2 = nullableObject;
    if (_value2 != null) {
      context?.markProperty(pointer, 'nullableObject');
      if (!(_value2 is NullableObject || _value2 == null)) {
        throwValidationError(
          _ptr2,
          'type',
          'Expected value to match one of the allowed types [object, null].',
        );
      }
    }
    final _ptr3 = appendJsonPointer(pointer, 'nullableString');
    final _value3 = nullableString;
    if (_value3 != null) {
      context?.markProperty(pointer, 'nullableString');
      if (!(_value3 is String || _value3 == null)) {
        throwValidationError(
          _ptr3,
          'type',
          'Expected value to match one of the allowed types [string, null].',
        );
      }
    }
  }
}
