// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/nullable_types/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class NullableTypesExampleNullableObject {
  final String? name;

  const NullableTypesExampleNullableObject({
    this.name,
  });

  factory NullableTypesExampleNullableObject.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final name = json['name'] as String?;
    remaining.remove('name');
    return NullableTypesExampleNullableObject(
      name: name,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (name != null) map['name'] = name;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
