// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/nullable_types/schema.json
// Generated by json_schema2dart

import 'nullable_types_example_nullable_object.dart';
import 'validation_error.dart';

/// Demonstrates nullable field handling
class NullableTypesExample {
  final List<String>? nullableArray;
  /// A number that can be null
  final double? nullableNumber;
  final NullableTypesExampleNullableObject? nullableObject;
  /// A string that can be null
  final String nullableString;

  const NullableTypesExample({
    this.nullableArray,
    this.nullableNumber,
    this.nullableObject,
    required this.nullableString,
  });

  factory NullableTypesExample.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final nullableArray = json['nullableArray'] == null ? null : (json['nullableArray'] as List).map((e) => e as String).toList();
    remaining.remove('nullableArray');
    final nullableNumber = json['nullableNumber'] as double?;
    remaining.remove('nullableNumber');
    final nullableObject = json['nullableObject'] == null ? null : NullableTypesExampleNullableObject.fromJson((json['nullableObject'] as Map).cast<String, dynamic>());
    remaining.remove('nullableObject');
    final nullableString = json['nullableString'] as String;
    remaining.remove('nullableString');
    return NullableTypesExample(
      nullableArray: nullableArray,
      nullableNumber: nullableNumber,
      nullableObject: nullableObject,
      nullableString: nullableString,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (nullableArray != null) map['nullableArray'] = nullableArray;
    if (nullableNumber != null) map['nullableNumber'] = nullableNumber;
    if (nullableObject != null) map['nullableObject'] = nullableObject!.toJson();
    map['nullableString'] = nullableString;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
