// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/content_validation/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class ContentValidationExample {
  final String payload;

  const ContentValidationExample({required this.payload});

  factory ContentValidationExample.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final payload = json['payload'] as String;
    remaining.remove('payload');
    return ContentValidationExample(payload: payload);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['payload'] = payload;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
