// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/allof_example/schema.json
// Generated by json_schema2dart

export 'schema_generated/all_of_example.dart';
export 'schema_generated/person.dart';
export 'schema_generated/root_schema_person.dart';
export 'schema_generated/root_schema_person2.dart';
export 'schema_generated/validation_error.dart';
