// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

import 'branding_color.dart';
import 'branding_icon.dart';
import 'validation_error.dart';

/// You can use a color and Feather icon to create a badge to personalize and distinguish your action. Badges are shown next to your action name in GitHub Marketplace.
class Branding {
  /// The background color of the badge.
  final BrandingColor? color;

  /// The name of the Feather icon to use.
  final BrandingIcon? icon;

  const Branding({this.color, this.icon});

  factory Branding.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final color = json['color'] == null
        ? null
        : BrandingColorJson.fromJson(json['color'] as String);
    remaining.remove('color');
    final icon = json['icon'] == null
        ? null
        : BrandingIconJson.fromJson(json['icon'] as String);
    remaining.remove('icon');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return Branding(color: color, icon: icon);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (color != null) map['color'] = color!.toJson();
    if (icon != null) map['icon'] = icon!.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
