// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

/// The background color of the badge.
enum BrandingColor {
  white,
  black,
  yellow,
  blue,
  green,
  orange,
  red,
  purple,
  grayDark,
}

extension BrandingColorJson on BrandingColor {
  String toJson() => const {
    BrandingColor.white: 'white',
    BrandingColor.black: 'black',
    BrandingColor.yellow: 'yellow',
    BrandingColor.blue: 'blue',
    BrandingColor.green: 'green',
    BrandingColor.orange: 'orange',
    BrandingColor.red: 'red',
    BrandingColor.purple: 'purple',
    BrandingColor.grayDark: 'gray-dark',
  }[this]!;

  static BrandingColor fromJson(String value) => const {
    'white': BrandingColor.white,
    'black': BrandingColor.black,
    'yellow': BrandingColor.yellow,
    'blue': BrandingColor.blue,
    'green': BrandingColor.green,
    'orange': BrandingColor.orange,
    'red': BrandingColor.red,
    'purple': BrandingColor.purple,
    'gray-dark': BrandingColor.grayDark,
  }[value]!;
}
