// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

import 'branding.dart';
import 'inputs.dart';
import 'runs.dart';
import 'validation_error.dart';

class RootSchema {
  /// The name of the action's author.
  final String? author;

  /// You can use a color and Feather icon to create a badge to personalize and distinguish your action. Badges are shown next to your action name in GitHub Marketplace.
  final Branding? branding;

  /// A short description of the action.
  final String description;

  /// Input parameters allow you to specify data that the action expects to use during runtime. GitHub stores input parameters as environment variables. Input ids with uppercase letters are converted to lowercase during runtime. We recommended using lowercase input ids.
  final Inputs? inputs;

  /// The name of your action. GitHub displays the `name` in the Actions tab to help visually identify actions in each job.
  final String name;
  final dynamic outputs;
  final Runs runs;

  const RootSchema({
    this.author,
    this.branding,
    required this.description,
    this.inputs,
    required this.name,
    this.outputs,
    required this.runs,
  });

  factory RootSchema.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final author = json['author'] as String?;
    remaining.remove('author');
    final branding = json['branding'] == null
        ? null
        : Branding.fromJson((json['branding'] as Map).cast<String, dynamic>());
    remaining.remove('branding');
    final description = json['description'] as String;
    remaining.remove('description');
    final inputs = json['inputs'] == null
        ? null
        : Inputs.fromJson((json['inputs'] as Map).cast<String, dynamic>());
    remaining.remove('inputs');
    final name = json['name'] as String;
    remaining.remove('name');
    final outputs = json['outputs'];
    remaining.remove('outputs');
    final runs = Runs.fromJson((json['runs'] as Map).cast<String, dynamic>());
    remaining.remove('runs');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return RootSchema(
      author: author,
      branding: branding,
      description: description,
      inputs: inputs,
      name: name,
      outputs: outputs,
      runs: runs,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (author != null) map['author'] = author;
    if (branding != null) map['branding'] = branding!.toJson();
    map['description'] = description;
    if (inputs != null) map['inputs'] = inputs!.toJson();
    map['name'] = name;
    if (outputs != null) map['outputs'] = outputs;
    map['runs'] = runs.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'author');
    final _value0 = author;
    if (_value0 != null) {
      context?.markProperty(pointer, 'author');
    }
    final _ptr1 = appendJsonPointer(pointer, 'branding');
    final _value1 = branding;
    if (_value1 != null) {
      context?.markProperty(pointer, 'branding');
    }
    final _ptr2 = appendJsonPointer(pointer, 'description');
    final _value2 = description;
    context?.markProperty(pointer, 'description');
    final _ptr3 = appendJsonPointer(pointer, 'inputs');
    final _value3 = inputs;
    if (_value3 != null) {
      context?.markProperty(pointer, 'inputs');
    }
    final _ptr4 = appendJsonPointer(pointer, 'name');
    final _value4 = name;
    context?.markProperty(pointer, 'name');
    final _ptr5 = appendJsonPointer(pointer, 'outputs');
    final _value5 = outputs;
    if (_value5 != null) {
      context?.markProperty(pointer, 'outputs');
    }
    final _ptr6 = appendJsonPointer(pointer, 'runs');
    final _value6 = runs;
    context?.markProperty(pointer, 'runs');
    final _jsonp6 = _value6.toJson();
    final _constraintp6c0_0 = context == null ? null : ValidationContext();
    var _constraintp6m0_0 = false;
    try {
      final context = _constraintp6c0_0;
      final _constraintp6v0_0 = RunsJavascript.fromJson(
        (_jsonp6 as Map).cast<String, dynamic>(),
      );
      _constraintp6m0_0 = true;
    } on ValidationError {
    } catch (_) {}
    final _constraintp6c0_1 = context == null ? null : ValidationContext();
    var _constraintp6m0_1 = false;
    try {
      final context = _constraintp6c0_1;
      final _constraintp6v0_1 = RunsComposite.fromJson(
        (_jsonp6 as Map).cast<String, dynamic>(),
      );
      _constraintp6v0_1.validate(pointer: _ptr6, context: context);
      _constraintp6m0_1 = true;
    } on ValidationError {
    } catch (_) {}
    final _constraintp6c0_2 = context == null ? null : ValidationContext();
    var _constraintp6m0_2 = false;
    try {
      final context = _constraintp6c0_2;
      final _constraintp6v0_2 = RunsDocker.fromJson(
        (_jsonp6 as Map).cast<String, dynamic>(),
      );
      _constraintp6v0_2.validate(pointer: _ptr6, context: context);
      _constraintp6m0_2 = true;
    } on ValidationError {
    } catch (_) {}
    final _constraintp6matches0 = <bool>[
      _constraintp6m0_0,
      _constraintp6m0_1,
      _constraintp6m0_2,
    ];
    final _constraintp6count0 = _constraintp6matches0
        .where((value) => value)
        .length;
    if (_constraintp6count0 != 1) {
      throwValidationError(
        _ptr6,
        'oneOf',
        'Expected exactly one subschema in #/properties/runs/oneOf to validate.',
      );
    }
    if (context != null && _constraintp6m0_0 && _constraintp6c0_0 != null) {
      context.mergeFrom(_constraintp6c0_0!);
    }
    if (context != null && _constraintp6m0_1 && _constraintp6c0_1 != null) {
      context.mergeFrom(_constraintp6c0_1!);
    }
    if (context != null && _constraintp6m0_2 && _constraintp6c0_2 != null) {
      context.mergeFrom(_constraintp6c0_2!);
    }
  }
}
