// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// Prevents a job from failing when a step fails. Set to true to allow a job to pass when this step fails.
sealed class RunsCompositeStepContinueOnError {
  const RunsCompositeStepContinueOnError();

  void validate({String pointer = '', ValidationContext? context});

  factory RunsCompositeStepContinueOnError.fromJson(dynamic json) {
    if (json is bool) return RunsCompositeStepContinueOnErrorBool(json);
    if (json is String) return RunsCompositeStepContinueOnErrorString(json);
    throw ArgumentError(
      'Invalid RunsCompositeStepContinueOnError value type: ${json.runtimeType}',
    );
  }

  dynamic toJson();
}

class RunsCompositeStepContinueOnErrorBool
    extends RunsCompositeStepContinueOnError {
  final bool value;

  const RunsCompositeStepContinueOnErrorBool(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class RunsCompositeStepContinueOnErrorString
    extends RunsCompositeStepContinueOnError {
  final String value;

  const RunsCompositeStepContinueOnErrorString(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
