// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

import 'runs_docker_env_object_additional_property.dart';
import 'validation_error.dart';

/// Specifies a key/value map of environment variables to set in the container environment.
sealed class RunsDockerEnv {
  const RunsDockerEnv();

  void validate({String pointer = '', ValidationContext? context});

  factory RunsDockerEnv.fromJson(dynamic json) {
    if (json is String) return RunsDockerEnvString(json);
    if (json is! Map<String, dynamic>) {
      throw ArgumentError('Invalid RunsDockerEnv value: ${json.runtimeType}');
    }
    final keys = json.keys.toSet();
    final sortedKeys = keys.toList()..sort();
    return RunsDockerEnvObject.fromJson(json);
  }

  dynamic toJson();
}
class RunsDockerEnvObject extends RunsDockerEnv {
  final Map<String, RunsDockerEnvObjectAdditionalProperty>? additionalProperties;

  const RunsDockerEnvObject({
    this.additionalProperties,
  }) : super();

  factory RunsDockerEnvObject.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    var unmatched = Map<String, dynamic>.from(remaining);
    Map<String, RunsDockerEnvObjectAdditionalProperty>? additionalPropertiesValue;
    if (unmatched.isNotEmpty) {
      final additionalPropertiesMap = <String, RunsDockerEnvObjectAdditionalProperty>{};
      for (final entry in unmatched.entries) {
        final value = entry.value;
        additionalPropertiesMap[entry.key] = RunsDockerEnvObjectAdditionalProperty.fromJson((value as Map).cast<String, dynamic>());
      }
      additionalPropertiesValue = additionalPropertiesMap.isEmpty ? null : additionalPropertiesMap;
      unmatched = <String, dynamic>{};
    } else {
      additionalPropertiesValue = null;
    }
    return RunsDockerEnvObject(
      additionalProperties: additionalPropertiesValue,
    );
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (additionalProperties != null) {
      additionalProperties!.forEach((key, value) {
        map[key] = value.toJson();
      });
    }
    return map;
  }

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
class RunsDockerEnvString extends RunsDockerEnv {
  final String value;

  const RunsDockerEnvString(this.value) : super();

  @override
  dynamic toJson() => value;
}
