// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

import 'runs_composite_step_shell_variant2.dart';
import 'validation_error.dart';

/// The shell where you want to run the command.
sealed class RunsCompositeStepShell {
  const RunsCompositeStepShell();

  void validate({String pointer = '', ValidationContext? context});

  factory RunsCompositeStepShell.fromJson(dynamic json) {
    if (json is String)
      return RunsCompositeStepShellValue2(
        RunsCompositeStepShellVariant2Json.fromJson(json),
      );
    throw ArgumentError(
      'Invalid RunsCompositeStepShell value type: ${json.runtimeType}',
    );
  }

  dynamic toJson();
}

class RunsCompositeStepShellValue extends RunsCompositeStepShell {
  final dynamic value;

  const RunsCompositeStepShellValue(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class RunsCompositeStepShellValue2 extends RunsCompositeStepShell {
  final RunsCompositeStepShellVariant2 value;

  const RunsCompositeStepShellValue2(this.value) : super();

  @override
  dynamic toJson() => value.toJson();

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
