// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

sealed class RunsDockerEnvObjectAdditionalProperty {
  const RunsDockerEnvObjectAdditionalProperty();

  void validate({String pointer = '', ValidationContext? context});

  factory RunsDockerEnvObjectAdditionalProperty.fromJson(dynamic json) {
    if (json is String)
      return RunsDockerEnvObjectAdditionalPropertyString(json);
    if (json is num)
      return RunsDockerEnvObjectAdditionalPropertyNum(json.toDouble());
    if (json is bool) return RunsDockerEnvObjectAdditionalPropertyBool(json);
    throw ArgumentError(
      'Invalid RunsDockerEnvObjectAdditionalProperty value type: ${json.runtimeType}',
    );
  }

  dynamic toJson();
}

class RunsDockerEnvObjectAdditionalPropertyString
    extends RunsDockerEnvObjectAdditionalProperty {
  final String value;

  const RunsDockerEnvObjectAdditionalPropertyString(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class RunsDockerEnvObjectAdditionalPropertyNum
    extends RunsDockerEnvObjectAdditionalProperty {
  final double value;

  const RunsDockerEnvObjectAdditionalPropertyNum(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}

class RunsDockerEnvObjectAdditionalPropertyBool
    extends RunsDockerEnvObjectAdditionalProperty {
  final bool value;

  const RunsDockerEnvObjectAdditionalPropertyBool(this.value) : super();

  @override
  dynamic toJson() => value;

  @override
  void validate({String pointer = '', ValidationContext? context}) {}
}
